### ISSUE TITLE
Starting the app removes the Alias

### ISSUE THREAD

**Issue by darko1002001** [urbanairship/android-library#10]
When using the android SDK, we associate an alias to a channel, what happens is that every time the application is killed and reopened the alias is being reset to None.

We using the 8.2.X version of the SDK.
We only use the following code in the application class:

AirshipConfigOptions options = new AirshipConfigOptions.Builder()
                .setInProduction(isProduction)
                .setGcmSender(getString(R.string.ua_gcm_sender))
                .setDevelopmentAppKey(getString(R.string.ua_AppKey))
                .setDevelopmentAppSecret(getString(R.string.ua_AppSecret))
                .setProductionAppKey(getString(R.string.ua_AppKey))
                .setProductionAppSecret(getString(R.string.ua_AppSecret))
                .setDevelopmentLogLevel(Log.ERROR)
                .build();

 UAirship.takeOff(this, options, new UAirship.OnReadyCallback() {}

I saw in the docs that the alias is deprecated but we have no way at the moment to switch to using a named user since it would require work on backend + android and ios.

**Comment by rlepinski** [comment]
Aliases will continue to work. We persist aliases in a local database, so I don't see how it would be cleared unless the app's data is being cleared.

Could you try to reproduce with the sample app without any modifications?
Post code on setting the alias?
Verbose logs for each run (setting it, killing the app, starting it)?

**Comment by darko1002001** [comment]
Hey, 
This is how our flow happens, i think the issue is because the mobile app never sets the Alias, it never touches that, we only do a takeOff call as mentioned in the code above. So its quite hard to just reproduce it with a sample code.

1. Mobile app is launched. Airship takeOff called (settings above)
2. User opens login screen
3. We submit login info together with the UAirship channel ID to our backend
4. Backend authenticates the user and generates an Alias.
5. Backend calls urban airship and sets up an alias for the channel
6. returns Success as response to mobile app.
7. Thats it, we don't actually interact with Urban airship at this time or any way further.
8. after some time user kills the app
9. opens the app next time, when takeOff is being called, the alias is being set to None inside urban airship.

I believe you sending an empty alias every time we open the app
Regards,
Darko

**Comment by rlepinski** [comment]
so you are setting the alias through a server call and not through the SDK?

**Comment by darko1002001** [comment]
Yes correct

**Comment by rlepinski** [comment]
Ok, so I don't believe thats ever been supported to set an alias outside of the SDK since we introduced channels several years ago. Whats happening is every time we do a channel registration update, we are clearing the alias because we send up the alias in that call. However this is a perfect use case for named user, which is basically alias v2. I would recommend contacting support if need more help.

**Comment by darko1002001** [comment]
Ok thanks

**Comment by rlepinski** [comment]
Here is a link to the named user api - https://docs.urbanairship.com/api/ua/#api-named-users
