### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by BishwajithBN** [urbanairship/android-library#105]
##  java.lang.NullPointerException
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.firebase.iid.FirebaseInstanceId.a(java.lang.String, java.lang.String)' on a null object reference
       at com.urbanairship.push.fcm.FcmPushProvider.getRegistrationToken(FcmPushProvider.java:58)
       at com.urbanairship.push.PushManagerJobHandler.onUpdatePushRegistration(PushManagerJobHandler.java:206)
       at com.urbanairship.push.PushManagerJobHandler.performJob(PushManagerJobHandler.java:123)
       at com.urbanairship.push.PushManager.onPerformJob(PushManager.java:403)
       at com.urbanairship.job.Job$1.run(Job.java:91)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

[Fabric Link ](http://crashes.to/s/9838ebbe922)
## Firebase Message Verions : 17.3.4

**Comment by BrianBatchelder** [comment]
@BishwajithBN : Please provide your Urban Airship dependencies and their versions. Your Firebase dependencies and versions might also be helpful. 

In the future, please follow the issue template when submitting an issue, as the information you provide is very helpful for our analysis.

**Comment by joaotfernandes** [comment]
@BrianBatchelder I'm getting the same crash when using a release build with proguard enabled. I'm using `urbanairship-fcm:9.3.1`, `firebase-core:16.0.6`, `firebase-messaging:17.3.4`, `google-services:4.0.0`. This issue happens on startup and it looks like no methods of the urban airship SDK need to be called to trigger it. It is also possible that this is an issue with the firebase configuration as I can see in the logs before crashing `W/FA: Failed to retrieve Firebase Instance Id`. However it works fine on debug and I don't think there are separate configs for debug and release on firebase.

**Comment by joaotfernandes** [comment]
I've done some more investigation on this and it doesn't seem to be related to the urban airship sdk. When calling `FirebaseInstanceId.getInstance(app)` at any point in the application, even without urban airship included, it always returns null when proguard is enabled. I've managed to fix it by adding `-keep class com.google.firebase.** { *; }` to the proguard config which probably keeps more than necessary but so far this is what I have.

It does crash in the urban airship sdk though when no instance ID is returned from Firebase, so maybe that could be handled in a different way.

**Comment by rlepinski** [comment]
We can add a null check in the next release but this issue should be reported to Firebase.

**Comment by rlepinski** [comment]
Added a check in SDK 9.6.1

**Comment by shashi0291** [comment]
> -keep class com.google.firebase.** { *; }
I am also facing similar issue when i run proguard on my build. Even after adding `-keep class com.google.firebase.** { *; }` the issue is not resolved. Any suggestion?
