### ISSUE TITLE
Problem: 'class file for com.google.android.gms.internal.zzbfm not found'

### ISSUE THREAD

**Issue by tsakmalis** [urbanairship/android-library#108]
UrbanAirship version: 9.5.2

Whenever I try to add the latest Urban Airship dependencies I have the following error after the build:
/........: cannot access zzbfm arguments.putParcelableArrayList("points", listLatLng);
  class file for com.google.android.gms.internal.zzbfm not found

**Comment by BrianBatchelder** [comment]
@tsakmalis : It is unclear to me with which SDK version you are seeing the problem. Are you trying to add version 9.5.2, or are you trying to upgrade from version 9.5.2 to our current version (9.7.0)?

You might take a look at [this issue](https://github.com/urbanairship/android-library/issues/101). It is possible that your firebase dependencies are causing the problem. [This stackoverflow](https://stackoverflow.com/questions/51610283/error-cannot-access-zzbfm-class-file-for-com-google-android-gms-internal-zzbfm) might also help.

**Comment by rlepinski** [comment]
Could you post your build.gradle file?

**Comment by tsakmalis** [comment]
`buildscript {
    repositories {
        maven {
            url 'https://maven.fabric.io/public'
           }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'


    }
}

allprojects {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
        maven {
            url "https://jitpack.io"
        }
    }
}

apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
apply plugin: 'realm-android'

repositories {
    maven { url 'https://maven.fabric.io/public' }
}

android {

    useLibrary 'org.apache.http.legacy'

    signingConfigs {
        release {
                   //////////
        }
    }
    compileSdkVersion 27
    buildToolsVersion '28.0.3'
    dexOptions {
        dexInProcess = false
        javaMaxHeapSize "4g"
    }
    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }
    defaultConfig {
        applicationId "............"
        minSdkVersion 18
        targetSdkVersion 26
        multiDexEnabled true
        signingConfig signingConfigs.release

        javaCompileOptions {
            annotationProcessorOptions {
                includeCompileClasspath = true
            }
        }
    }
    /* signingConfigs {


         release {

         }
     }*/
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
            signingConfig signingConfigs.release
        }
        debug {
            minifyEnabled false
            debuggable true
        }
    }
    dataBinding.enabled = true
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
    }
    flavorDimensions "default"
    productFlavors {
        mmt365 {
            minSdkVersion 18
            signingConfig signingConfigs.release
            targetSdkVersion 27
            manifestPlaceholders = [appIcon: "@drawable/icon"]
            dimension "default"
        }
        hybrid {
            minSdkVersion 18
            signingConfig signingConfigs.release
            targetSdkVersion 27
            manifestPlaceholders = [appIcon: "@drawable/iconhybrid"]
            dimension "default"
        }
        alpinerX {
            minSdkVersion 18
            signingConfig signingConfigs.release
            targetSdkVersion 27
            manifestPlaceholders = [appIcon: "@drawable/iconalpinerx"]
            dimension "default"
        }
    }
}



dependencies {
    api 'com.android.support:support-v4:27+'
    api 'org.twitter4j:twitter4j-core:4.0.2'
    api 'com.android.volley:volley:1.1.0'
    implementation('joda-time:joda-time:2.9.4') {
        exclude module: 'joda-time'
    }
    api 'com.parse.bolts:bolts-tasks:1.4.0'
    implementation('com.facebook.android:facebook-android-sdk:3.22.0') {
        exclude module: 'bolts-android'
        exclude module: 'support-v4'
    }
    api 'org.apache.httpcomponents:httpclient-android:4.3.5.1'
    implementation('org.apache.httpcomponents:httpmime:4.3') {
        exclude module: "httpclient"
    }
    api 'org.xeustechnologies:jtar:1.1'
    api 'com.sun.mail:javax.mail:1.5.0'
    implementation('com.crashlytics.sdk.android:crashlytics:2.9.4@aar') {
        transitive = true;
    }
    api fileTree(include: ['*.jar'], dir: 'libs')
    api 'com.android.support:multidex:1.0.3'
    api 'com.android.support:appcompat-v7:27.1.1'
    api 'com.android.support:recyclerview-v7:27.1.1'
    api 'fr.avianey.com.viewpagerindicator:library:2.4.1@aar'
    api 'com.android.support:appcompat-v7:27.1.1'
    api 'com.android.support:multidex:1.0.3'
    api 'com.android.support:appcompat-v7:27.1.1'
    api 'com.android.support:design:27.1.1'
    api 'com.android.support:cardview-v7:27.1.1'
    api 'com.mikepenz:iconics-core:2.8.2@aar'
    api 'com.mikepenz:material-design-iconic-typeface:2.2.0.2@aar'
    implementation('com.mikepenz:aboutlibraries:5.9.4@aar') { transitive = true }
    api project(':library')
    api 'com.google.code.gson:gson:2.8.5'
    api 'com.github.kanytu:android-parallax-recyclerview:v1.7'
    api 'pl.droidsonroids.gif:android-gif-drawable:1.2.3'
    api 'com.github.vipulasri:timelineview:1.0.6'
    api 'com.jakewharton:butterknife:9.0.0-rc1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:9.0.0-rc1'
    //this is using for the Demo Image Slider
    api 'com.github.bumptech.glide:glide:4.8.0'
    api 'com.google.android.gms:play-services-location:11.8.0'
    api 'com.google.android.gms:play-services:11.8.0'
    api 'io.realm:android-adapters:2.1.1'
    api 'com.evernote:android-job:1.2.6'
    api 'com.google.maps.android:android-maps-utils:0.5+'
    api 'com.google.android.gms:play-services-fitness:11.8.0'
    api 'com.google.android.gms:play-services-auth:11.8.0'
    api 'com.roomorama:caldroid:3.0.1'
    configurations.all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            def requested = details.requested
            if (requested.group == 'com.android.support') {
                if (!requested.name.startsWith("multidex")) {
                    details.useVersion '27.1.0'
                }
            }
        }
    }

    implementation 'com.github.lecho:hellocharts-library:1.5.8@aar'
    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0-alpha'

}

apply plugin: 'com.google.gms.google-services'`

**Comment by rlepinski** [comment]
That version of the SDK uses 15.0.1 of Google Play services and you are using 11.8.0. You should really update to modern versions of Google Play Services and the google-services plugin.

**Comment by anurag-176** [comment]
Hello poor souls,
Just update versions of libraries "......gms:play-services....." to the latest
To check the latest versions, refer this [https://developers.google.com/android/guides/releases](link)
