### ISSUE TITLE
App startup time performance

### ISSUE THREAD

**Issue by vaniakerer** [urbanairship/android-library#110]
### What Urban Airship dependencies are you using?

`com.urbanairship.android:urbanairship-sdk:8.9.6`

### What are the versions of any relevant development tools you are using?

`com.google.android.gms:play-services-gcm:16.0.0`
`support library - 28.0.`

### What unexpected behavior are you seeing?

Low app startup time performance. I removed all usages of UAirship.java in project, and use only initialise code in Application class:

```
   UAirship.takeOff(this, (UAirship uAirship) -> {
           Log.d("TAG", "Callback");
        });
```

Without this code my app starts faster for 500-700 ms

Is it OK? Because it's seems like not default behaviour

**Comment by crow** [comment]
@vaniakerer This seems to be a long enough delay to raise suspicions - but I'm going to want to reproduce this on my end before jumping to any conclusions. Thanks for reporting.

**Comment by rlepinski** [comment]
@vaniakerer could you see if the issue is still a problem with `urbanairship-gcm:9.7.0`? Are you calling UAirship.shared() anywhere?

**Comment by vaniakerer** [comment]
@rlepinski Yes, I tried to use `urbanairship-gcm:9.7.0`, buе delay did not disappear.

And now I'm not using UAirship.shared() anywhere

**Comment by rlepinski** [comment]
@vaniakerer We need more information to help you. Could you provide logs, metrics, sample code, sample app, or anything else?  How are you measuring it?

**Comment by rlepinski** [comment]
I just built a new app with urbanairship-gcm: 9.7.0. I launched the app 3 times for each type of takeOff situation (no takeOff, in application, with autopilot) and recorded the results of the intial time to display.

No TakeOff:
ActivityManager: Displayed com.urbanairship.sample/.MainActivity: +461ms
ActivityManager: Displayed com.urbanairship.sample/.MainActivity: +441ms
ActivityManager: Displayed com.urbanairship.sample/.MainActivity: +437ms

TakeOff in Application.onCreate()
ActivityManager: Displayed com.urbanairship.sample/.MainActivity: +490ms
ActivityManager: Displayed com.urbanairship.sample/.MainActivity: +476ms
ActivityManager: Displayed com.urbanairship.sample/.MainActivity: +528ms

Autopilot:
ActivityManager: Displayed com.urbanairship.sample/.MainActivity: +447ms
ActivityManager: Displayed com.urbanairship.sample/.MainActivity: +443ms
ActivityManager: Displayed com.urbanairship.sample/.MainActivity: +446ms

|                                  | Average Startup Time  | 
|-------------------  |----------------------- |
|No TakeOff               | 446 ms                          | 
|TakeOff Application | 498 ms                          |
|Autopilot                   | 445 ms                          |

By calling takeOff in the application it only resulted in 52ms increase while using autopilot had almost no effect on it.

**Comment by rlepinski** [comment]
Going to close for now. If you have more info we can reopen the issue.

**Comment by vaniakerer** [comment]
Thanks for your feedback and sorry for my so late feedback. Really, it wasn`t urbanairship.
