### ISSUE TITLE
Application package name restriction doesn't work

### ISSUE THREAD

**Issue by pietrini** [urbanairship/android-library#112]
# Preliminary Info

### What Urban Airship dependencies are you using?
implementation "com.urbanairship.android:urbanairship-fcm:9.7.0"

### What are the versions of any relevant development tools you are using?
Android Studio 3.3.1
Build #AI-182.5107.16.33.5264788, built on January 29, 2019
JRE: 1.8.0_152-release-1248-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

# Report

### What unexpected behavior are you seeing?
In Airship configuration channel, package name is omitted when sending notification. We have multiple flavors debug/nightly/beta/release in our app, and for now the only way to be sure nothing will be send in production instead of dev is to have a specific fcm project with a different fcmSenderId.

With this param omitted, we can misunderstand airship logic and think we are secure with this param correctly set. But in reality everything depends on airship credentials.

### What is the expected behavior?
use: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#AndroidConfig with restricted_package_name param if package is set, or remove this param from airship channel config to clarify usage.

**Comment by marc-scig** [comment]
Hi @pietrini, 

To be clear, are you asking that we add this feature to our REST API? Unless there's something we can do for you entirely in the SDK, you may be better off contacting support.

**Comment by pietrini** [comment]
Oh ok I get it sorry. Yes I'll contact support directly !

Have a nice day !
