### ISSUE TITLE
RateAppActivity is exported 

### ISSUE THREAD

**Issue by richardmuttett** [urbanairship/android-library#114]
# Please fill out this template when submitting an issue.
All lines beginning with an ℹ symbol indicate information that's important for you to provide to ensure your issue is resolved as quickly and efficiently as possible.

❗For how-to inquiries involving Urban Airship functionality or use cases, please
contact (support)[https://support.urbanairship.com/hc/en-us].

# Preliminary Info

### What Urban Airship dependencies are you using?
com.urbanairship.android:urbanairship-fcm:9.7.0

### What are the versions of any relevant development tools you are using?
N/A

# Report

### What unexpected behavior are you seeing?
com.urbanairship.actions.RateAppActivity is exported

### What is the expected behavior?
That it not be exported. Does it need to be?

### What are the steps to reproduce the unexpected behavior?
Via a Bug Bounty program, we learned that a rogue Android app could include the following code. For the purposes of this illustration, com.our.LaunchActivity is the launch activity for our app.

        Intent main = new Intent();
        main.setClassName(appPackage, "com.our.LaunchActivity");
        startActivity(main);

        new Handler().postDelayed(new Runnable() {

            @Override
            public void run() {
                Intent intent = new Intent();
                intent.setClassName(appPackage, "com.urbanairship.actions.RateAppActivity");
                intent.putExtra("title", "Fake title");
                intent.putExtra("body", "Fake body");
                intent.putExtra("store_uri", Uri.parse("http://www.this-could-be-bad.com/"));

                startActivity(intent);
            }
        }, 3000);

As you can imagine, this results in our app being launched and the user is given the impression that the themed alert they are presented with is trustworthy and they would therefore be lured to load the bad URL.

### Do you have logging for the issue?
N/A

**Comment by rlepinski** [comment]
We can remove it from being exported. I will do a release tomorrow with the fix. Thanks for the report.

**Comment by rlepinski** [comment]
Going to close this for now, release is coming ASAP. In the future please send any security concerns to security@urbanairship.com.

Here is a workaround if you want to avoid updated the SDK:

```
     <activity
            android:name="com.urbanairship.actions.RateAppActivity"
            android:exported="false"
           tools:node="merge-only-attributes" />
```

You should verify the merged manifest sets `android:exported="false"` for the RateAppActivity

**Comment by richardmuttett** [comment]
Thank you for the quick turn-around on this.

**Comment by sankartringapps** [comment]
@rlepinski using tools:node="merge-only-attributes" throws error -
No enum constant com.android.manifmerger.NodeOperationType.MERGE-ONLY-ATTRIBUTES

**Comment by rlepinski** [comment]
You are right, the merge-only-attributes seems to be outdated docs. Looks like you can just do:
```
<activity
            android:name="com.urbanairship.actions.RateAppActivity"
            android:exported="false" />
```
And it will merge the exported="false". We did release 9.7.1 with the fix so if you can please update.
