### ISSUE TITLE
Wakelock - not released?

### ISSUE THREAD

**Issue by cnordvik** [urbanairship/android-library#12]
We have a user saying that he experiences partial wakelocks in our app when receiving push alerts. Here for a single day he has wakelocks for almost 26min. 

Can you review the wakelocks part of the SDK and see if there are any potential wakelock issues there? I tried to review them and only thing I could see is that if exceptions occurred then there might be some issues with wakelocks not being released? 

![wakelock](https://cloud.githubusercontent.com/assets/584549/25608330/bbd4e638-2f1a-11e7-86ac-7ae0fd55edbb.jpg)

**Comment by rlepinski** [comment]
What SDK version are you using?

Assuming its a newer 8.x version, we only acquire a wakelock when handling GCM/ADM registration changes or processing push notifications. I would not expect that count to be 66, that seems like an obsessive amount.

That only method that actually creates  a wakelock is through our [internal Job framework](https://github.com/urbanairship/android-library/blob/master/urbanairship-sdk/src/main/java/com/urbanairship/job/JobDispatcher.java#L73), and that uses the support libraries startWakefulService which creates wakelocks with a 1 min timeout. If you take a look at t the started [AirshipService](https://github.com/urbanairship/android-library/blob/master/urbanairship-sdk/src/main/java/com/urbanairship/AirshipService.java), it does not catch any exceptions, however if exceptions were occurring it would be taking down the entire app, so you would have several crash reports.

Do you know how many notifications you are sending to that user in the span of 11 hours? Are you sending big picture images or doing anything that requires downloading a large amount of data when receiving a push during that time? Is this an ongoing issue or a 1 time occurrence?

**Comment by cnordvik** [comment]
We are using 8.0.4 of the SDK. 

66 alerts seems fine as this is a score alert app so we are sending a lot of alerts and this user had enabled alerts for an entire league so 66 seems within reason. 

In the alerts we are downloading a player image with Picasso but it is fairly small. We are also downloading a 640x320 image on news alerts but user probably hasn't had more than 1-5 of those. 

We do tend to wrap a lot of stuff in try/catch on our side so maybe there is something that is catched on our side and wakelock isn't released? Sounds a bit far fetched though.

**Comment by rlepinski** [comment]
I can't find any place in the SDK that would be fail to release a wake lock. 66 wakelocks for 26m 26s = 24s per wake lock. Our default wakelock timeout is 1 min, so it seems that we are not letting them expire. Maybe take a look at the default timeouts when doing the image fetching. Thats all I can really think of.

We just did a 8.4.0 release that uses GCMNetworkManager to do all of our job retries. It wont really help out with the above wakelocks but it should save on battery life. 

I am going to close this issue as I cant find a path that it would fail even if exceptions where thrown (we catch them when calling user code). If you can find a way to reproduce or have more users with this issue, please reopen.
