### ISSUE TITLE
Support for library androidX

### ISSUE THREAD

**Issue by uziassantosferreira** [urbanairship/android-library#121]
Any plans to support androidX?

**Comment by rlepinski** [comment]
@uziassantosferreira Right now we have a dependency on FCM that has an indirect dependency on the old support library. Even if we were to update our SDK to use AndroidX, you will still have to use the jetifier flag. Using the jetifier flag today should make our library work with AnroidX.

Google announced that Firebase and Google Play Services will be updating to use AndroidX. in June/July. After we have an updated firebase dependency, we will work on migrating our SDK to use AndroidX.

https://android-developers.googleblog.com/2019/06/google-play-services-and-firebase.html

**Comment by rlepinski** [comment]
SDK 11.0.0 supports AndroidX
