### ISSUE TITLE
InApp messages do not auto dismiss

### ISSUE THREAD

**Issue by malloth** [urbanairship/android-library#123]
# Please fill out this template when submitting an issue.
All lines beginning with an ℹ symbol indicate information that's important for you to provide to ensure your issue is resolved as quickly and efficiently as possible.

❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.urbanairship.com/hc/en-us].

# Preliminary Info

### What Airship dependencies are you using?
com.urbanairship.android:urbanairship-fcm:10.0.1

### What are the versions of any relevant development tools you are using?
Android Studio 3.4.1

# Report

### What unexpected behavior are you seeing?
InApp messages do not auto dismiss after a specified amount of time.

### What is the expected behavior?
InApp messages should auto dismiss after a 15 sec (default).

### What are the steps to reproduce the unexpected behavior?
Create an InApp message and wait.

### Do you have logging for the issue?
The issues lies in `BannerView` class in `onResume()`. Instead of checking for `if(!isDismissed)` you check for `if(isDismissed)` which causes `Timer` to not start at all.

**Comment by rlepinski** [comment]
Thanks, I will try to get a fix out ASAP.

**Comment by rlepinski** [comment]
Fixed in 10.0.2
