### ISSUE TITLE
Creating custom BannerView in BannerAdapter

### ISSUE THREAD

**Issue by malloth** [urbanairship/android-library#124]
# Please fill out this template when submitting an issue.
All lines beginning with an ℹ symbol indicate information that's important for you to provide to ensure your issue is resolved as quickly and efficiently as possible.

❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.urbanairship.com/hc/en-us].

# Preliminary Info

### What Airship dependencies are you using?
com.urbanairship.android:urbanairship-fcm:10.0.1

### What are the versions of any relevant development tools you are using?
Android Studio 3.4.1

# Report

### What unexpected behavior are you seeing?
Currently there's (almost) no possibility to create custom BannerView in BannerAdapter, or apply custom styling to the default one.

### What is the expected behavior?
Method `onCreateView(activity: Activity, viewGroup: ViewGroup): BannerView` should be split to two methods: `onCreateView(activity: Activity, viewGroup: ViewGroup): BannerView` and `onViewCreated(view: BannerView, activity: Activity, viewGroup: ViewGroup)`. The first one would give developers an ability to specify their custom view extending from `BannerView`. All the setup code (setting listener, animations, insets etc.) which you do, should be done in `onViewCreated`.

### What are the steps to reproduce the unexpected behavior?
N/A

### Do you have logging for the issue?
N/A

**Comment by rlepinski** [comment]
I like it, unfortunately any api changes will bump the minor/major version so this will have to wait for either 10.1 or 11.0.

**Comment by rlepinski** [comment]
Added changes in 11.0.0 (with AndroidX migration)
