### ISSUE TITLE
Listener in BannerAdapter is passing wrong ResolutionInfo for onTimedOut

### ISSUE THREAD

**Issue by malloth** [urbanairship/android-library#125]
# Please fill out this template when submitting an issue.
All lines beginning with an ℹ symbol indicate information that's important for you to provide to ensure your issue is resolved as quickly and efficiently as possible.

❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.urbanairship.com/hc/en-us].

# Preliminary Info

### What Airship dependencies are you using?
com.urbanairship.android:urbanairship-fcm:10.0.1

### What are the versions of any relevant development tools you are using?
Android Studio 3.4.1

# Report

### What unexpected behavior are you seeing?
In `BannerAdapter.onCreateView` method listener for `onTimedOut` is passing `ResolutionInfo.messageClicked()` to `displayHandler.finished`  instead of `ResolutionInfo.timedOut()`.

### What is the expected behavior?
Listener should be passing `ResolutionInfo.timedOut()` to `displayHandler.finished`.

### What are the steps to reproduce the unexpected behavior?
N/A

### Do you have logging for the issue?
N/A

**Comment by rlepinski** [comment]
Good catch. This class clearly needs more unit tests. Thanks!

**Comment by rlepinski** [comment]
Fixed in 10.0.2
