### ISSUE TITLE
Inbox for different named user

### ISSUE THREAD

**Issue by luispereira** [urbanairship/android-library#126]
I'm trying to show only the inbox messages to a specific user depending on its login. 
If userA logs in, he will only view his push notifications in the inbox. However if he logs out and another userB logs in, UserB should not be able to see userA notifications in the inbox.

So, we are introducing the concept of multi user for inbox. 

Is it possible to do this? If so how?
I'm seeing that inbox creation depends on `password` and `user.id`, however how can we supply these features if the app was already takeOff UrbanAirship?

**Comment by rlepinski** [comment]
Currently not supported. Please contact support to request this feature. 

The best you can do ATM is to add a key in the message extras and then use that extra to filter what message the logged in user has access to.

**Comment by luispereira** [comment]
Ok, I can filter them every time I do the getMessages(), but isn't the channel ID is directly related with inbox messages? So if my channel id changes I will lose the all inbox messages right?

**Comment by rlepinski** [comment]
Correct. The channel ID will only change on a new install. Please contact support to request a named user inbox listing.
