### ISSUE TITLE
App getting launch again even if it is already running when user tap on Notification

### ISSUE THREAD

**Issue by Shivamgarg1528** [urbanairship/android-library#127]
# Preliminary Info

### What Airship dependencies are you using?
com.urbanairship.android:urbanairship-fcm:10.0.0

### What are the versions of any relevant development tools you are using?
Android Studio 3.3.1

# Report

### What unexpected behavior are you seeing?
App getting launch again even if it is already running when user tap on Notification

### What is the expected behavior?
App should launch only if it is not running.

### What are the steps to reproduce the unexpected behavior?
1-  Put your app in foreground
2- Send push
3- Tapping on push, starting my launcher activity then executing (deeplink) action if any

### Do you have logging for the issue?
https://github.com/urbanairship/android-library/issues/127

**Comment by rlepinski** [comment]
This behavior only happens if you launch the app android studio. If you close the app then retry your test everything should work fine.
