### ISSUE TITLE
Notification id is -1 when opening a push notification.

### ISSUE THREAD

**Issue by woxblom** [urbanairship/android-library#128]
# Preliminary Info
Notification id is -1 when opening a push notification.

### What Airship dependencies are you using?
implementation 'com.urbanairship.android:urbanairship-fcm:11.0.3'

### What are the versions of any relevant development tools you are using?
Android studio 3.4.2

# Report

### What unexpected behavior are you seeing?
When opening a received push notification the following method is called in NotificationInfo

    @Nullable
    static NotificationInfo fromIntent(Intent intent) {
        PushMessage message = PushMessage.fromIntent(intent);
        if (message == null) {
            return null;
        } else {
            int id = intent.getIntExtra("com.urbanairship.push.NOTIFICATION_ID", -1);
            String tag = intent.getStringExtra("com.urbanairship.push.NOTIFICATION_TAG");
            return new NotificationInfo(message, id, tag);
        }
    }

The problem is that com.urbanairship.push.NOTIFICATION_ID is never found so it defaults to -1. So when onNotificationOpened is called in my NotificationListener the id is -1 and not the id that was generated when creating the notification.

### What is the expected behavior?
The notification id that was created by getNextId when creating the notification should be set in the NotificationInfo when opening. 
When dismissing a notification the id is correct however. It is only when opening a notification it can't find the com.urbanairship.push.NOTIFICATION_ID in the intent.

### What are the steps to reproduce the unexpected behavior?
Receive a push notification and then click on it.

### Do you have logging for the issue?
No

**Comment by marc-scig** [comment]
Hi @woxblom,

Thanks for bringing this to our attention. We'll take a look and get back to you as soon as possible.

**Comment by marc-scig** [comment]
OK, I think I see the bug. I'll get some work prioritized to put out a patch, most likely in the next week. If this is an emergency and you need a fix sooner than that let us know, otherwise I'll ping you when the update is out. Thanks again.

**Comment by BrianBatchelder** [comment]
@woxblom : SDK 11.0.4 is out with a fix for your issue. 

Thanks, and let us know if you have further issues.
