### ISSUE TITLE
IllegalArgumentException: the bind value at index 1 is null

### ISSUE THREAD

**Issue by hazemhamadaqa** [urbanairship/android-library#131]
this problem when receive notification on android 8 & 9 

### What Airship dependencies are you using?
 implementation('com.urbanairship.android:urbanairship-fcm:11.0.5') {
        exclude group: "com.android.support"
   }

### Do you have logging for the issue?
Fatal Exception: java.lang.IllegalArgumentException: the bind value at index 1 is null
       at android.database.sqlite.SQLiteProgram.bindString + 192(SQLiteProgram.java:192)
       at android.database.sqlite.SQLiteProgram.bindAllArgsAsStrings + 228(SQLiteProgram.java:228)
       at android.database.sqlite.SQLiteDirectCursorDriver.query + 49(SQLiteDirectCursorDriver.java:49)
       at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory + 1865(SQLiteDatabase.java:1865)
       at android.database.sqlite.SQLiteDatabase.queryWithFactory + 1712(SQLiteDatabase.java:1712)
       at android.database.sqlite.SQLiteDatabase.query + 1583(SQLiteDatabase.java:1583)
       at android.database.sqlite.SQLiteDatabase.query + 1789(SQLiteDatabase.java:1789)
       at com.urbanairship.util.DataManager.query + 312(DataManager.java:312)
       at com.urbanairship.util.DataManager.query + 300(DataManager.java:300)
       at com.urbanairship.push.notifications.NotificationChannelRegistryDataManager.getChannel + 123(NotificationChannelRegistryDataManager.java:123)
       at com.urbanairship.push.notifications.NotificationChannelRegistry$1.run + 87(NotificationChannelRegistry.java:87)
       at com.urbanairship.util.SerialExecutor$1.run + 40(SerialExecutor.java:40)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1167(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 641(ThreadPoolExecutor.java:641)
       at com.urbanairship.util.AirshipThreadFactory$1.run + 49(AirshipThreadFactory.java:49)
       at java.lang.Thread.run + 764(Thread.java:764)

**Comment by marc-scig** [comment]
@hazemhamadaqa are you using a custom notification factory or notification provider? anything that uses the NotificationArguments class?

**Comment by hazemhamadaqa** [comment]
yes i am using AirshipNotificationProvider

and this my code 

 @Override
    public void onAirshipReady(UAirship airship) {
        SharedPreferences preferences = UAirship.getApplicationContext().getSharedPreferences(NO_BACKUP_PREFERENCES, Context.MODE_PRIVATE);

        boolean isFirstRun = preferences.getBoolean(FIRST_RUN_KEY, true);
        if (isFirstRun) {
            preferences.edit().putBoolean(FIRST_RUN_KEY, false).apply();

            // Enable user notifications on first run
            airship.getPushManager().setUserNotificationsEnabled(true);
        }

        AirshipListener airshipListener = new AirshipListener();
        airship.getPushManager().addPushListener(airshipListener);
        airship.getPushManager().addRegistrationListener(airshipListener);
        airship.getPushManager().setNotificationListener(airshipListener);

        NotificationChannelCompat channelCompat = new NotificationChannelCompat("customChannel",
                "Breaking News!",
                NotificationManagerCompat.IMPORTANCE_DEFAULT);

        airship.getPushManager()
                .getNotificationChannelRegistry()
                .createNotificationChannel(channelCompat);

        airship.getPushManager()
                .setNotificationProvider(new CustomAirshipNotificationProvider( UAirship.getApplicationContext(),airship.getAirshipConfigOptions()));


//        notificationFactory = new CustomNotificationFactory(UAirship.getApplicationContext());
//        airship.getPushManager().setNotificationFactory(notificationFactory);
    }

and this my CustomAirshipNotificationProvider

public class CustomAirshipNotificationProvider extends AirshipNotificationProvider {

    public CustomAirshipNotificationProvider(@NonNull Context context, @NonNull AirshipConfigOptions configOptions) {
        super(context, configOptions);
    }


    @Override
    protected int getNextId(@NonNull Context context, @NonNull PushMessage message) {
        return super.getNextId(context, message);
    }

    @WorkerThread
    @NonNull
    @Override
    public NotificationArguments onCreateNotificationArguments(@NonNull Context context, @NonNull PushMessage message) {
        String channel = message.getNotificationChannel("defaultChannel");
        return NotificationArguments.newBuilder(message)
                .setNotificationChannelId(channel)
                .setNotificationId(message.getNotificationTag(), NotificationIdGenerator.nextID())
                .build();
    }

    @WorkerThread
    @NonNull
    @Override
    public NotificationResult onCreateNotification(@NonNull Context context, @NonNull NotificationArguments arguments) {
        // do not display a notification if there is not an alert
        if (UAStringUtil.isEmpty(arguments.getMessage().getAlert())) {
            return NotificationResult.cancel();
        }


        Log.e("createNotification","createNotification");
        String type=arguments.getMessage().getExtra("type",null);
        if(type.equals("booking")){
            String notification= arguments.getMessage().getExtra("notification","{}");
            if (UAStringUtil.isEmpty(notification)) {
                return null;
            }
            Log.e("createNotification1","createNotification1");
            try {
                JSONObject jsonObject =new JSONObject(notification);

                JSONObject notification_obj=jsonObject.getJSONObject("notification");
                String title_val=notification_obj.getString("title");
                String message_val=notification_obj.getString("message");

                Intent intent = new Intent(context, SplashActivity.class);
                intent.putExtra("action","open_notification");
                intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
                PendingIntent pendingIntent = PendingIntent.getActivity(context, 0, intent, 0);

                Log.e("createNotification2","createNotification2");

                // Build the notification
                NotificationCompat.Builder builder = new NotificationCompat.Builder(context)
                        .setContentTitle(title_val)
                        .setContentText(message_val)
                        .setAutoCancel(true)
                        .setContentIntent(pendingIntent)
                        .setSmallIcon(R.mipmap.ic_launcher);

                builder.setSound(Uri.parse("android.resource://" + context.getPackageName() + "/" + R.raw.quiteimpressed));
                // Notification action buttons
                builder.extend(new ActionsNotificationExtender(context, arguments.getMessage(),  arguments.getNotificationId()));

                Log.e("createNotification3","createNotification3");
                return NotificationResult.notification(builder.build());
//                return builder.build();
            } catch (Exception e) {
                e.printStackTrace();
                Log.e("Exception",""+e.getMessage());
            }
        }

//        // Build the notification
//        NotificationCompat.Builder builder = new NotificationCompat.Builder(context)
//                .setContentTitle("Notification title")
//                .setContentText(arguments.getMessage().getAlert())
//                .setAutoCancel(true)
//                .setSmallIcon(R.mipmap.ic_launcher);

        // Notification action buttons
//        builder.extend(new ActionsNotificationExtender(context, arguments.getMessage(), arguments.getNotificationId()));

        return null;
    }


}

**Comment by marc-scig** [comment]
Thank you. There's nothing that jumps out at me at the moment, but I'll take your code and see if I can reproduce the problem first.

**Comment by marc-scig** [comment]
Has this code changed recently? the reason I'm asking is that the only way I can see this error occurring is if the notification channel ID set on NotificationArguments ends up null. That doesn't appear to be happening in this code, but I also can see you're not checking `message.getNotificationChannel` for null either, which should cause a compiler warning since the return type is marked nullable.

Is the error happening all the time, or just sometimes? Something you can reproduce reliably?

**Comment by hazemhamadaqa** [comment]
this error not happen on android 6 
but when i am test it on android 8 appear 

> Has this code changed recently?  
yes i am upgrade to last version of your library and then this error happen ?
is my code complete or there is a lack ?!
if i must add another code to avoid this problem please tell me ?!

**Comment by hazemhamadaqa** [comment]
how i can ensure channel not null ?
are you mean i will use getNotificationChannel() and it will not null ?
please explain more !

**Comment by rlepinski** [comment]
@hazemhamadaqa The current code looks fine, but since getNotificaitonChannel is technically nullable, you should do this instead:
```
@WorkerThread
@NonNull
@Override
public NotificationArguments onCreateNotificationArguments(@NonNull Context context, @NonNull PushMessage message) {
    String channel = message.getNotificationChannel();
    if (channel == null) {
        channel = "defaultChannel";
    }
    return NotificationArguments.newBuilder(message)
            .setNotificationChannelId(channel)
            .setNotificationId(message.getNotificationTag(), NotificationIdGenerator.nextID())
            .build();
}
```

If you are having any more issues please contact support.

**Comment by hazemhamadaqa** [comment]
problem still appear after use your code

**Comment by BrianBatchelder** [comment]
We use Github mostly for internal SDK issues. For help with using the SDK, please contact support at https://support.airship.com/

**Comment by rlepinski** [comment]
@hazemhamadaqa I am unable to reproduce your issue. Are you able to reproduce it everytime? Do you have clear steps I could follow?

**Comment by rlepinski** [comment]
Any updates?
