### ISSUE TITLE
App initialization crash related to FCM setup

### ISSUE THREAD

**Issue by harishrpatel** [urbanairship/android-library#133]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

com.urbanairship.android:urbanairship-fcm:11.0.5
com.urbanairship.android:gimbal-adapter:3.0.0
com.google.firebase:firebase-core:16.0.5
com.google.firebase:firebase-messaging:15.0.0

### What are the versions of any relevant development tools you are using?

Android Studio 3.5.1

# Report

### What unexpected behavior are you seeing?

- We are not seeing this on most devices, but one device (Samsung Galaxy Note 9 - Android 9.0) exhibits this crash.
- Once it gets in this state, every launch crashes with same logs. Then, we remove app and reinstall same version, may run successfully.

### What is the expected behavior?

- Crashes during launch. We do not explicitly initialize Firebase programmatically.
`Application.onCreate (....) {
....
        Autopilot.automaticTakeOff(this)
}
`
### What are the steps to reproduce the unexpected behavior?

Simply run the app and it crashes during initialization.

### Do you have logging for the issue?

Here are some excerpts from logcat. We can provide full log on a private channel (if needed).
10-30 13:45:06.787 21966 22054 I XyzApp - UALib: Airship taking off!
10-30 13:45:06.787 21966 22054 I XyzApp - UALib: Airship log level: 2
10-30 13:45:06.787 21966 22054 I XyzApp - UALib: UA Version: 11.0.5 / App key = SAd-6JB1Srew3Yzr0xQGqQ Production = false
10-30 13:45:06.787 21966 22054 V XyzApp - UALib: !SDK-VERSION-STRING!:com.urbanairship.android:urbanairship-core:11.0.5

10-30 13:45:06.790 21966 22054 V XyzApp - UALib: Found provider: FCM Push Provider version: !SDK-VERSION-STRING!:com.urbanairship.android:urbanairship-fcm:11.0.5

10-30 13:45:06.797 21966 22054 E XyzApp - UALib: Unable to register with FCM.

10-30 13:45:06.797 21966 22054 E XyzApp - UALib: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.abcdcorp.xyzapp. Make sure to call FirebaseApp.initializeApp(Context) first.
10-30 13:45:06.797 21966 22054 E XyzApp - UALib:       at com.google.firebase.FirebaseApp.getInstance(SourceFile:5)
10-30 13:45:06.797 21966 22054 E XyzApp - UALib:       at com.urbanairship.push.fcm.FcmPushProvider.isAvailable(SourceFile:3)
10-30 13:45:06.797 21966 22054 E XyzApp - UALib:       at com.urbanairship.K.a(SourceFile:11)
10-30 13:45:06.797 21966 22054 E XyzApp - UALib:       at com.urbanairship.K.a(SourceFile:2)
10-30 13:45:06.797 21966 22054 E XyzApp - UALib:       at com.urbanairship.UAirship.F(SourceFile:3)
10-30 13:45:06.797 21966 22054 E XyzApp - UALib:       at com.urbanairship.UAirship.c(SourceFile:15)
10-30 13:45:06.797 21966 22054 E XyzApp - UALib:       at com.urbanairship.UAirship.a(SourceFile:1)
10-30 13:45:06.797 21966 22054 E XyzApp - UALib:       at com.urbanairship.ba.run(SourceFile:1)
10-30 13:45:06.797 21966 22054 E XyzApp - UALib:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-30 13:45:06.797 21966 22054 E XyzApp - UALib:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-30 13:45:06.797 21966 22054 E XyzApp - UALib:       at com.urbanairship.util.b.run(SourceFile:3)
10-30 13:45:06.797 21966 22054 E XyzApp - UALib:       at java.lang.Thread.run(Thread.java:764)
10-30 13:45:06.799 21966 22054 I XyzApp - UALib: Setting platform to android for push provider: FCM Push Provider
10-30 13:45:06.809 21966 22054 I XyzApp - UALib: Using push provider: FCM Push Provider

10-30 13:45:06.812 21966 22061 V XyzApp - UALib: PreferenceDataStore - Saving preference: com.urbanairship.application.device.PLATFORM value: 2

10-30 13:45:06.815 21966 22061 E XyzApp - UALib: Failed to insert in UrbanAirshipProvider.
10-30 13:45:06.815 21966 22061 E XyzApp - UALib: java.lang.IllegalArgumentException: Unknown URL content://com.abcdcorp.xyzapp.urbanairship.provider/preferences
10-30 13:45:06.815 21966 22061 E XyzApp - UALib:       at android.content.ContentResolver.insert(ContentResolver.java:1589)
10-30 13:45:06.815 21966 22061 E XyzApp - UALib:       at com.urbanairship.ca.a(SourceFile:7)
10-30 13:45:06.815 21966 22061 E XyzApp - UALib:       at com.urbanairship.I$a.d(SourceFile:11)
10-30 13:45:06.815 21966 22061 E XyzApp - UALib:       at com.urbanairship.I$a.a(SourceFile:2)
10-30 13:45:06.815 21966 22061 E XyzApp - UALib:       at com.urbanairship.H.run(SourceFile:1)
10-30 13:45:06.815 21966 22061 E XyzApp - UALib:       at com.urbanairship.util.F.run(SourceFile:1)
10-30 13:45:06.815 21966 22061 E XyzApp - UALib:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
10-30 13:45:06.815 21966 22061 E XyzApp - UALib:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
10-30 13:45:06.815 21966 22061 E XyzApp - UALib:       at com.urbanairship.util.b.run(SourceFile:3)
10-30 13:45:06.815 21966 22061 E XyzApp - UALib:       at java.lang.Thread.run(Thread.java:764)
10-30 13:45:06.815 21966 22061 V XyzApp - UALib: PreferenceDataStore - Saving preference: com.urbanairship.application.device.PUSH_PROVIDER value: class com.urbanairship.push.fcm.FcmPushProvider

**Comment by rlepinski** [comment]
`com.google.firebase:firebase-messaging:15.0.0` is out of date and incompatible with Android O+, however I would be suprised if you are actually using that one since our plugin requires a newer one. Could you run `./gradlew app:dependencies` and provide the output? 

Is this an older version of your app by chance? We already catch that exception that you are experiencing - https://github.com/urbanairship/android-library/blob/master/urbanairship-fcm/src/main/java/com/urbanairship/push/fcm/FcmPushProvider.java#L101

**Comment by harishrpatel** [comment]
@rlepinski I am working on an app from one of our clients, so can I provide the dependencies output non-publically? You can email me instructions directly if you like to harishpateldfw@gmail.com

BTW this crash is from 11.0.5. As you can see from UALib entries from logcat. The four dependencies I pasted above did come from Android Studio->Gradle->androidDependencies output.
