### ISSUE TITLE
How to build a synthetic/fake TaskStackBuilder using UA for Push Notifications for Android?

### ISSUE THREAD

**Issue by perrygarg** [urbanairship/android-library#134]
# Preliminary Info

## What Airship dependencies are you using?
 ℹ com.urbanairship.android:urbanairship-sdk:9.0.+ 

## What are the versions of any relevant development tools you are using?
 ℹ Android Studio 3.5

# Report

### What unexpected behavior are you seeing?
 ℹ Not able to make a synthetic/fake Task stack in order to provide good user experience after opening the notification. On the latest Android version, activity needs to be started with FLAG_NEW_TASK when opened from the notification.

## What is the expected behavior?
 ℹ I should be able to specify a fake Task stack containing parent activity to ensure a good user flow. 

## What are the steps to reproduce the unexpected behavior?
ℹ Send notification using UA and receive in Android app 

## Do you have logging for the issue?
 ℹ Not applicable.

**Comment by rlepinski** [comment]
You will want to set the [notification listener](https://docs.airship.com/platform/android/push-notifications/#listening-for-notification-events) on PushManager and use `onNotificationOpened` and `onNotificationForegroundAction` to launch your app with whatever intent you would like. Make sure to return `true` in both those methods to prevent Airship from launching the main activity by default.

```
@Override
public void onAirshipReady(@NonNull UAirship airship) {

    ...

    // Notification listener
    airship.getPushManager().setNotificationListener(new NotificationListener() {
        
        @Override
        public boolean onNotificationOpened(@NonNull NotificationInfo notificationInfo) {
            // Start app with synthetic/fake task stack
            return true;
        }

        @Override
        public boolean onNotificationForegroundAction(@NonNull NotificationInfo notificationInfo, @NonNull NotificationActionButtonInfo actionButtonInfo) {
            // Start app with synthetic/fake task stack
            return true;
        }

        @Override
        public void onNotificationPosted(@NonNull NotificationInfo notificationInfo) {
            Log.i(TAG, "Notification posted. Alert: " + notificationInfo.getMessage().getAlert() + ". NotificationId: " + notificationInfo.getNotificationId());
        }

        @Override
        public void onNotificationBackgroundAction(@NonNull NotificationInfo notificationInfo, @NonNull NotificationActionButtonInfo actionButtonInfo) {
            Log.i(TAG, "Notification background action. Button ID: " + actionButtonInfo.getButtonId() + ". NotificationId: " + notificationInfo.getNotificationId());
        }

        @Override
        public void onNotificationDismissed(@NonNull NotificationInfo notificationInfo) {
            Log.i(TAG, "Notification dismissed. Alert: " + notificationInfo.getMessage().getAlert() + ". Notification ID: " + notificationInfo.getNotificationId());
        }
    });
}

```
