### ISSUE TITLE
device-api.urbanairship.com/api/channels errors

### ISSUE THREAD

**Issue by tszpinda** [urbanairship/android-library#135]
### What Airship dependencies are you using?
`com.urbanairship.android:urbanairship-fcm:9.7.2`

# Report

### What unexpected behavior are you seeing?
Firebase reporting 95% of requests failing - for `device-api.urbanairship.com/api/channels`
and 18% `for remote-data.urbanairship.com/api/remote-data/app...`

<img width="857" alt="trend-30-days" src="https://user-images.githubusercontent.com/1911579/70150002-25538e00-16a1-11ea-9ea1-29e0d8125310.png">

This doesn't look like expected behaviour and we are not sure what effect this has on our users, are you able to advise?

**Comment by crow** [comment]
This is almost certainly not an issue with the Android SDK.  The primary error code is a 403 - which broadly signals that you are not allowed to access the endpoint. This probably indicates a change in your account status with Airship. Please contact [support](https://support.airship.com/hc/en-us) for further assistance.
