### ISSUE TITLE
Landing Page customization not available in latest version

### ISSUE THREAD

**Issue by bhaumik2712** [urbanairship/android-library#136]
Hi,
We are using your library in our project. We recently updated library version to 
`implementation 'com.urbanairship.android:urbanairship-fcm:12.1.0'`
from
`implementation 'com.urbanairship.android:urbanairship-fcm:9.7.1'`
and we are not able to customize landing page. We found below lines are showing error and no more available 
```
<activity
android:name="com.urbanairship.actions.LandingPageActivity"
tools:node="remove" />
```
We are following below document for landing page customization
https://docs.airship.com/tutorials/api/android/landing-page/#layout

Kindly help us on how we can customize landing page with your latest SDK version.

Thanks.

**Comment by rlepinski** [comment]
We replaced the landing page implementation to use our In-App Automation module to schedule landing pages as HTML In-App Messages. This makes the landing page more flexible, as you can control exactly how it displays, (prevent it from displaying on any launch screens)[https://docs.airship.com/platform/android/in-app-automation/#excluding-activities], and it no longer collides with other In-App messages.

The docs page you pointed to is very out of date, I will make sure it gets addressed. Also, it looks like we missed the landing page change in our migration guide.


What customizations are you trying to do to the landing page? If its minor styling, you might want to see if those customizations are available by modifying the generated In-App message:

```
LandingPageAction landingPageAction = new LandingPageAction() {
    @NonNull
    @Override
    protected InAppMessage.Builder extendMessage(InAppMessage.Builder builder) {
        // Customize appearance and display behavior
        return builder;
    }

    @NonNull
    @Override
    protected InAppMessageScheduleInfo.Builder extendSchedule(InAppMessageScheduleInfo.Builder builder) {
        // Customize any triggering behavior with the schedule info
        return builder;
    }
};

airship.getActionRegistry().registerAction(landingPageAction,
        LandingPageAction.DEFAULT_REGISTRY_NAME,
        LandingPageAction.DEFAULT_REGISTRY_SHORT_NAME);

```

If you need extended style changes, you might be able to (modify the style sheet)[https://docs.airship.com/platform/android/in-app-automation/#styles].

If that is not enough, you can either replace the landing page action all together to do any custom behavior, or you might look into providing a (custom HTML display adapter)[https://docs.airship.com/platform/android/in-app-automation/#custom-adapters].

**Comment by bhaumik2712** [comment]
Hi,
Thanks for the reply.

I have followed the steps given at https://docs.airship.com/platform/android/in-app-automation/#customization

I want to display in-app message dialog as given below but with latest SDK in-app message, dialog is displaying in full screen so please advice how to implement custom activity for in-app message?

![image](https://user-images.githubusercontent.com/11713742/71391193-31d86000-2629-11ea-8a8b-bfdda506ee53.png)

Can you please advice where I need to set this lines of code?
```
UAirship.shared()
.getInAppMessagingManager()
.setAdapterFactory(InAppMessage.TYPE_MODAL, message -> {
return new CustomInAppMessageAdapter(message);
});
```
I tried above code but custom adapter did not invoke.

I will wait for your reply.

Thanks.

**Comment by marc-scig** [comment]
Hi @bhaumik2712,

The example code you posted shows how to set a custom adapter for the modal in-app message type. Landing pages in the lastest SDK are the HTML in-app message type, so you'd want to pass InAppMessage.TYPE_HTML in the setAdapterFactory call. This will make it so that all HTML in-app messages, including landing pages, display using your custom adapter.
