### ISSUE TITLE
Duplicate in app messages if Activity uses NEW_TASK and CLEAR_TOP

### ISSUE THREAD

**Issue by nishtahir** [urbanairship/android-library#137]
# Preliminary Info

### What Airship dependencies are you using?
 urbanairship-fcm:11.0.5

### What are the versions of any relevant development tools you are using?

Android Studio 3.5

# Report

### What unexpected behavior are you seeing?

Multiple banners are created for the sample in-app message. Sometimes these banners are not dismissed

### What is the expected behavior?
There should be a single banner per task/Activity

### What are the steps to reproduce the unexpected behavior?
* Launch a new activity that inits airship, send an in-app message, 
* start an activity with the flags
`Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TOP | Intent.FLAG_ACTIVITY_SINGLE_TOP`
* Observer that duplicate banners are created

We've created a sample project that reproduces this behavior
https://github.com/evant/airship-issue-clear-top

### Do you have logging for the issue?
No relevant logs

**Comment by rlepinski** [comment]
Thank you for the report and the sample project. We will take a look.

**Comment by rlepinski** [comment]
@nishtahir I have a fix, just testing to make sure it does not introduce regressions with other activity usage. I hope to have a patch by the end of the week, early next week.

**Comment by rlepinski** [comment]
Released in 12.1.1, here is a migration guide for 11 -> 12 https://github.com/urbanairship/android-library/blob/master/documentation/migration/migration-guide-11-12.md

The only real breaking changes are package changes, which should be quick to fix in your app. The rest is deprecations, but if you want to address those it is also minor.
