### ISSUE TITLE
Fatal Exception: java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by halysongoncalves** [urbanairship/android-library#138]
Hello,

We have identified crash in `com.urbanairship.job.AirshipService.onCreate` that has affected our users.

![Captura de Tela 2020-02-07 às 09 31 39](https://user-images.githubusercontent.com/5872045/74029975-ac1c3400-498c-11ea-8afc-8888db19fa83.png)

`
Fatal Exception: java.lang.OutOfMemoryError
pthread_create (1040KB stack) failed: Try again
java.lang.Thread.nativeCreate (Thread.java)
java.lang.Thread.start (Thread.java:733)
com.urbanairship.job.AirshipService.onCreate (AirshipService.java:75)
android.app.ActivityThread.handleCreateService (ActivityThread.java:3598)
android.app.ActivityThread.access$1400 (ActivityThread.java:216)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1729)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:235)
android.app.ActivityThread.main (ActivityThread.java:6760)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:911)`

**Comment by crow** [comment]
Thanks for reporting @halysongoncalves. 

Out of memory exceptions can happen for various reasons, some of which we have no control over. 

Some more context would be useful for troubleshooting the issue:
- Do you have a general idea of how often this exception is occurring?
- What Urban Airship dependencies (with versions) are you currently using? 
- Do you have any additional context that might aid in constructing steps to reproduce the issue?

Thanks again!

**Comment by halysongoncalves** [comment]
Hi,

We are currently using version 11.0.5. 


`class UrbanAutoPilot : Autopilot() {
    override fun onAirshipReady(airship: UAirship) {
        PreferenceManager.initialize(UAirship.getApplicationContext())

        val urbanListener = UrbanListener()
        airship.deepLinkListener = urbanListener

        airship.pushManager.setNotificationListener(urbanListener)
        airship.pushManager.userNotificationsEnabled =
            PreferenceManager.get(PreferenceManager.Key.KEY_PUSH_ENABLE, true) ?: true

        airship.analytics
            .editAssociatedIdentifiers()
            .addIdentifier(ANALYTICS_CID, Tracking.clientId)


        if (AuthenticationManagerMobile.isLogged()) {
            PushManager.updateTagUserState(
                if (AuthenticationManagerMobile.isSubscriber()) Dimensions.SUBSCRIBER.value
                else Dimensions.NOT_SUBSCRIBER.value
            )
            PushManager.updateUser(AuthenticationManagerMobile.getGloboId())
        } else {
            PushManager.updateTagUserState(Dimensions.UNKNOWN.value)
        }

        super.onAirshipReady(airship)
    }

    override fun createAirshipConfigOptions(context: Context): AirshipConfigOptions? =
        builderConfigAmbient(DEBUG, AirshipConfigOptions.Builder())
            .setFcmSenderId(FCM_ID)
            .setNotificationLargeIcon(R.mipmap.ic_launcher)
            .setNotificationIcon(R.drawable.ic_notification)
            .setNotificationAccentColor(ContextCompat.getColor(context, R.color.torch_red))
            .setNotificationChannel(NOTIFICATION_CHANNEL)
            .build()

    internal fun builderConfigAmbient(isDebug: Boolean, builder: AirshipConfigOptions.Builder) =
        if (isDebug) {
            builder
                .setInProduction(false)
                .setDevelopmentAppKey(URBAN_KEY)
                .setDevelopmentAppSecret(URBAN_SECRET)

        } else {
            builder
                .setInProduction(true)
                .setProductionAppKey(URBAN_KEY)
                .setProductionAppSecret(URBAN_SECRET)

        }
}`

**Comment by BrianBatchelder** [comment]
> When using `UAirship.shared()` do you recommend using with Looper or without?

Either way is valid and depends on your needs. Calling [`UAirship.shared()`](https://docs.airship.com/reference/libraries/android/latest/reference/com/urbanairship/UAirship.html#shared()) will return the instance synchronously. Calling [`UAirship.shared(looper, callback)`](https://docs.airship.com/reference/libraries/android/latest/reference/com/urbanairship/UAirship.html#shared(android.os.Looper,%20com.urbanairship.UAirship.OnReadyCallback)) returns the instance asynchronously. 

Your code example looks fine. I don't think it would be causing this issue.

**Comment by halysongoncalves** [comment]
It happens on the device: moto e 6 plus

**Comment by rlepinski** [comment]
This is not something we can reproduce of fix. The user is out of memory, so the app is going to crash ssomewhere, it just so happens to be on starting our service.
