### ISSUE TITLE
com.urbanairship.automation.AutomationDataManager.generateSchedules

### ISSUE THREAD

**Issue by halysongoncalves** [urbanairship/android-library#139]
Hello,

We have identified crash in `com.urbanairship.automation.AutomationDataManager.generateSchedules` that has affected our users.

<img width="649" alt="Captura de Tela 2020-02-19 às 10 02 28" src="https://user-images.githubusercontent.com/5872045/74836863-060ee900-52ff-11ea-8708-5f4f4ab55c72.png">

<img width="1123" alt="Captura de Tela 2020-02-19 às 10 02 36" src="https://user-images.githubusercontent.com/5872045/74836868-07401600-52ff-11ea-9df3-d13c8a3fa25e.png">

<img width="1137" alt="Captura de Tela 2020-02-19 às 10 06 33" src="https://user-images.githubusercontent.com/5872045/74837178-abc25800-52ff-11ea-841c-6ad9f564221a.png">

`Fatal Exception: android.database.CursorWindowAllocationException
Cursor window allocation of 2048 kb failed. # Open Cursors=1 (# cursors opened by this proc=1)
android.database.CursorWindow.<init> (CursorWindow.java:108)
android.database.AbstractCursor.moveToFirst (AbstractCursor.java:258)
com.urbanairship.automation.AutomationDataManager.generateSchedules (AutomationDataManager.java:735)
com.urbanairship.automation.AutomationDataManager.getScheduleEntries (AutomationDataManager.java:621)
com.urbanairship.automation.AutomationEngine.restoreIntervalAlarms (AutomationEngine.java:1021)
com.urbanairship.automation.AutomationEngine.access$1300 (AutomationEngine.java:60)
com.urbanairship.automation.AutomationEngine$4.run (AutomationEngine.java:325)
android.os.Handler.handleCallback (Handler.java:751)
android.os.HandlerThread.run (HandlerThread.java:61)
com.urbanairship.util.AirshipHandlerThread.run (AirshipHandlerThread.java:27)`

**Comment by BrianBatchelder** [comment]
This issue is most likely due to cursor leaks or out-of-memory situations, often outside of the Airship SDK. Cursors can be debugged using StrictMode, as described in [this StackOverflow page](https://stackoverflow.com/questions/32599856/whats-best-way-to-trace-down-sqlite-open-cursor-leak). 

If you would like further assistance, please provide us with the following:
- What Urban Airship dependencies (with versions) are you using in the app versions exhibiting the issue? 
- What are the versions of any relevant development tools you are using?
- Do you have any additional context that might aid in constructing steps to reproduce the issue?

**Comment by halysongoncalves** [comment]
1- We are currently using the version: 11.0.5

2- 
    final constraintVersion = '1.1.3'
    final daggerVersion = '2.26'
    final javaxAnnotationVersion = '1.0'
    final javaxInjectVersion = '1'
    final archVersion = '2.0.0'
    final lifecycleVersion = '2.2.0'
    final fragmentkTXVersion = '1.2.0'
    final multidexVersion = '2.0.1'
    final permissionVersion = '3.3.2'
    final fabricVersion = '2.9.1@aar'
    final coroutinesVersion = '1.3.2'
    final playServiceVersion = '16.1.0'
    final firebaseAnalyticsVersion = '17.0.1'
    final firebaseIidVersion = '18.0.0'
    final firebasePerformanceVersion = '17.0.2'
    final playerServiceTagManagerVersion = '16.0.8'
    final viewPager2Version = "1.0.0"
    final materialVersion = "1.1.0-rc01"

    //Player
    final exoPlayerVersion = '2.10.7'
    final interactiveMediaVersion = '3.8.5'
    final playServicesCastVersion = '16.1.2'
    final googleAnalyticsVersion = '16.0.8'
    final playServicesAdsVersion = '15.0.1'

  
    //GloboId
    final globoIdVersion = '1.13.1'
    final firebaseMessageVersion = '18.0.0'
    final playServicesLocationVersion = '16.0.0'
    final playServicesIidVersion = '16.0.1'
    final playServicesAuthVersion = '16.0.1'

    //Http
    final retrofitVersion = '2.6.1'
    final okHttpVersion = '3.12.1'
    final rxJavaVersion = '2.1.16'
    final rxRelayVersion = '2.1.0'
    final rxAndroidVersion = '2.0.2'
    final okioVersion = '1.13.0'

    //Others
    final gsonVersion = '2.8.5'
    final frescoVersion = '1.2.0'
    final picassoVersion = '2.5.2'
    final horizonVersion = '1.3.2'
    final canarinhoVersion = '1.2.0'
    final comScoreVersion = '5.7.3'
    final urbanVersion = '11.0.5'
    final facebookVersion = '4.34.0'
    final appsFlyerVersion = '4.8.19'
    final installReferrerVersion = '1.0'
    final glideVersion = '4.11.0'
    final salesForceVersion = '6.4.0'
    final hawkVersion = '2.0.1'
    final materialCalendarViewVersion = '1.7.0'
    final globocastVersion = '1.8.1'

**Comment by rlepinski** [comment]
We wont be able to reproduce this. This is probably related to your other OOM issue you reported. Services and cursors take more memory than small objects, so its most likely going to fail here. You probably have a memory leak in your application that you will need to trace https://developer.android.com/studio/profile/memory-profiler
