### ISSUE TITLE
com.urbanairship.automation.AutomationDataManager.getActiveTriggerEntries

### ISSUE THREAD

**Issue by halysongoncalves** [urbanairship/android-library#141]
Hello,

We have identified crash in `com.urbanairship.remotedata.RemoteDataStore.generatePayloadEntries
` that has affected our users.

![Captura de Tela 2020-02-19 às 10 12 11](https://user-images.githubusercontent.com/5872045/74837471-58043e80-5300-11ea-906f-1f0b79c3cef4.png)

![Captura de Tela 2020-02-19 às 10 12 07](https://user-images.githubusercontent.com/5872045/74837479-5a669880-5300-11ea-986a-b732a940764d.png)

![Captura de Tela 2020-02-19 às 10 12 18](https://user-images.githubusercontent.com/5872045/74837482-5b97c580-5300-11ea-9928-cd975fd51d24.png)

`Fatal Exception: android.database.sqlite.SQLiteDiskIOException
disk I/O error (code 266)
android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow (SQLiteConnection.java)
android.database.AbstractCursor.moveToFirst (AbstractCursor.java:258)
com.urbanairship.automation.AutomationDataManager.getActiveTriggerEntries (AutomationDataManager.java:701)
com.urbanairship.automation.AutomationDataManager.getActiveTriggerEntries (AutomationDataManager.java:681)
com.urbanairship.automation.AutomationEngine$23.run (AutomationEngine.java:1075)
android.os.Handler.handleCallback (Handler.java:751)
android.os.HandlerThread.run (HandlerThread.java:61)
com.urbanairship.util.AirshipHandlerThread.run (AirshipHandlerThread.java:27)`

**Comment by BrianBatchelder** [comment]
This issue is most likely due to the disk running out of space or becoming corrupted. It is most likely unrelated to the Airship SDK.

If you would like further assistance, please provide us with the following:
- What Urban Airship dependencies (with versions) are you using in the app versions exhibiting the issue? 
- What are the versions of any relevant development tools you are using?
- Do you have any additional context that might aid in constructing steps to reproduce the issue?

**Comment by halysongoncalves** [comment]
Hi @BrianBatchelder,

The error is different from the issue #144

**Comment by halysongoncalves** [comment]
Fatal Exception: android.database.sqlite.SQLiteDatabaseCorruptException database disk image is malformed (code 11)

**Comment by halysongoncalves** [comment]
Currently this error happens because users install our application on pirated devices

**Comment by halysongoncalves** [comment]
1- We are currently using the version: 11.0.5

2- 
    final constraintVersion = '1.1.3'
    final daggerVersion = '2.26'
    final javaxAnnotationVersion = '1.0'
    final javaxInjectVersion = '1'
    final archVersion = '2.0.0'
    final lifecycleVersion = '2.2.0'
    final fragmentkTXVersion = '1.2.0'
    final multidexVersion = '2.0.1'
    final permissionVersion = '3.3.2'
    final fabricVersion = '2.9.1@aar'
    final coroutinesVersion = '1.3.2'
    final playServiceVersion = '16.1.0'
    final firebaseAnalyticsVersion = '17.0.1'
    final firebaseIidVersion = '18.0.0'
    final firebasePerformanceVersion = '17.0.2'
    final playerServiceTagManagerVersion = '16.0.8'
    final viewPager2Version = "1.0.0"
    final materialVersion = "1.1.0-rc01"

    //Player
    final exoPlayerVersion = '2.10.7'
    final interactiveMediaVersion = '3.8.5'
    final playServicesCastVersion = '16.1.2'
    final googleAnalyticsVersion = '16.0.8'
    final playServicesAdsVersion = '15.0.1'

  
    //GloboId
    final globoIdVersion = '1.13.1'
    final firebaseMessageVersion = '18.0.0'
    final playServicesLocationVersion = '16.0.0'
    final playServicesIidVersion = '16.0.1'
    final playServicesAuthVersion = '16.0.1'

    //Http
    final retrofitVersion = '2.6.1'
    final okHttpVersion = '3.12.1'
    final rxJavaVersion = '2.1.16'
    final rxRelayVersion = '2.1.0'
    final rxAndroidVersion = '2.0.2'
    final okioVersion = '1.13.0'

    //Others
    final gsonVersion = '2.8.5'
    final frescoVersion = '1.2.0'
    final picassoVersion = '2.5.2'
    final horizonVersion = '1.3.2'
    final canarinhoVersion = '1.2.0'
    final comScoreVersion = '5.7.3'
    final urbanVersion = '11.0.5'
    final facebookVersion = '4.34.0'
    final appsFlyerVersion = '4.8.19'
    final installReferrerVersion = '1.0'
    final glideVersion = '4.11.0'
    final salesForceVersion = '6.4.0'
    final hawkVersion = '2.0.1'
    final materialCalendarViewVersion = '1.7.0'
    final globocastVersion = '1.8.1'

**Comment by rlepinski** [comment]
We will catch this exception in the next release.
