### ISSUE TITLE
com.urbanairship.reactive.Observable.subscribeOn

### ISSUE THREAD

**Issue by halysongoncalves** [urbanairship/android-library#143]
Hello,

We have identified crash in `com.urbanairship.reactive.Observable.subscribeOn` that has affected our users.

![Captura de Tela 2020-02-19 às 10 15 49](https://user-images.githubusercontent.com/5872045/74837713-dd87ee80-5300-11ea-8483-3cbe5ce3d98d.png)

![Captura de Tela 2020-02-19 às 10 15 54](https://user-images.githubusercontent.com/5872045/74837717-df51b200-5300-11ea-9cc2-f80364eb9c01.png)

![Captura de Tela 2020-02-19 às 10 16 05](https://user-images.githubusercontent.com/5872045/74837718-dfea4880-5300-11ea-9805-2a6c271a506c.png)

`Fatal Exception: java.lang.IncompatibleClassChangeError
The method 'void com.urbanairship.reactive.Observable$ObservableTracker$1.a(java.lang.Exception)' was expected to be of type static but instead was found to be of type virtual (declaration of 'com.urbanairship.reactive.Observable' appears in /data/app/com.globo.globotv-1/base.apk:classes4.dex)
com.urbanairship.reactive.Observable.subscribeOn (Observable.java:344)
com.urbanairship.automation.TriggerObservables.newSession (TriggerObservables.java:76)
com.urbanairship.automation.AutomationEngine.createEventObservable (AutomationEngine.java:730)
com.urbanairship.automation.AutomationEngine.restoreCompoundTriggers (AutomationEngine.java:779)
com.urbanairship.automation.AutomationEngine.start (AutomationEngine.java:330)
com.urbanairship.automation.Automation.init (Automation.java:76)
com.urbanairship.UAirship.init (UAirship.java:748)
com.urbanairship.UAirship.executeTakeOff (UAirship.java:409)
com.urbanairship.UAirship.access$000 (UAirship.java:61)
com.urbanairship.UAirship$2.run (UAirship.java:368)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
com.urbanairship.util.AirshipThreadFactory$1.run (AirshipThreadFactory.java:49)
java.lang.Thread.run (Thread.java:761)`

**Comment by BrianBatchelder** [comment]
The signature for `ObservableTracker` has always been static. It looks like this problem only occurred once for one user. Please let us know if it happens again, and provide us with the following information:
- What Urban Airship dependencies (with versions) are you using in the app versions exhibiting the issue? 
- What are the versions of any relevant development tools you are using?
- Do you have any additional context that might aid in constructing steps to reproduce the issue?
