### ISSUE TITLE
Adding style for in-app message

### ISSUE THREAD

**Issue by ivanessence** [urbanairship/android-library#149]
What Airship dependencies are you using?

implementation 'com.urbanairship.android:urbanairship-fcm:12.2.0'

What are the versions of any relevant development tools you are using?

Android Studio 3.6
Build #IU-201.6668.121, built on April 8, 2020
Runtime version: 1.8.0_212-release-1589-b04 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Win7

Report

I was trying to customize in-app message and set custom adapter to it. But when I tried to set a new adapter, in-app message style was not changed. I tried to investigate tutorial on official UA site but it did not help.

What unexpected behavior are you seeing?

New in-app message style does not accepted.

What is the expected behavior?

I want to change in-app message style and instead of it I want to show to user android SnackBar with InAppMessage text.

What are the steps to reproduce the unexpected behavior?

I tried to set adapter in the following way
`
airship.inAppMessagingManager.setAdapterFactory(InAppMessage.TYPE_CUSTOM) { inAppMessage -> CustomInAppMessageAdapter(inAppMessage) }
`
And how can I use Assets class in UA SDK?

**Comment by rlepinski** [comment]
Are you trying to replace modal types? Could you share your custom adapter?

**Comment by ivanessence** [comment]
> Are you trying to replace modal types? Could you share your custom adapter?

I just tried to add empty adapter like this, but no one overridden methods were not be called

` class CustomInAppMessageAdapter(message: InAppMessage): InAppMessageAdapter {

        override fun onFinish(p0: Context) {

        }
        @MainThread
        override fun isReady(p0: Context): Boolean {
            return true
        }
        @MainThread
        override fun onDisplay(p0: Context, p1: DisplayHandler) {
            Toast.makeText(p0, "TEXT", Toast.LENGTH_LONG).show()
        }

        @WorkerThread
        @InAppMessageAdapter.PrepareResult
        override fun onPrepare(p0: Context, p1: Assets): Int {
            return OK
        }`

Also I tried to set different types such InAppMessage.TYPE_CUSTOM, InAppMessage.TYPE_BANNER and it did not help

**Comment by rlepinski** [comment]
Depending on the type of message being displayed, you need to set the right type. Snackbar is closest to banner so I would assume TYPE_BANNER is what you want. Where are you setting the adapter factory?

**Comment by ivanessence** [comment]
@rlepinski I used setAdapterFactory() here 

`override fun onAirshipReady(airship: UAirship) {
//some code
        airship.inAppMessagingManager.setAdapterFactory(InAppMessage.TYPE_CUSTOM) { inAppMessage -> CustomInAppMessageAdapter(inAppMessage) 
    }
`

**Comment by rlepinski** [comment]
I just tested this adapter:

```
     InAppMessageManager.shared().setAdapterFactory(InAppMessage.TYPE_BANNER) {
            object : InAppMessageAdapter {
                override fun onFinish(context: Context) {
                }

                override fun isReady(context: Context): Boolean {
                    return true
                }

                override fun onDisplay(context: Context, displayHandler: DisplayHandler) {
                    Toast.makeText(context, "TEXT", Toast.LENGTH_LONG).show();

                    // Should be called on finish, but for now we will just call it immediately
                    // allows displaying the next message
                    displayHandler.finished(ResolutionInfo.timedOut(), 3000);
                }

                override fun onPrepare(context: Context, assets: Assets): Int {
                    return InAppMessageAdapter.OK;
                }
            }
        }
```

I added it in the onAirshipReady callback in Autopilot. I set it for banner and made sure I had a banner IAM ready to display.

**Comment by ivanessence** [comment]
@rlepinski Thank you, it really works, maybe the problem was with InAppMessage type... But now when I send the second message after 5min and the third message after 30min they are not displayed again and methods in adapter do not triggered. I have to restart app and then I'll see one previous message. What is the problem?

**Comment by rlepinski** [comment]
How are you sending the in-app message? Through the push api/composer or are you sending them as an in app automation?

Most likely you are missing a call to the display handler. The display handler is used to notify the IAM manager when a message is finished displaying so it can queue up the next message to display. In my example I had a call in onDisplay:

```
            // Should be called when the message is finished to unlock the display
            // Calling immediately for now since Toast does not have a callback
            displayHandler.finished(ResolutionInfo.timedOut(), 3000);
```

**Comment by ivanessence** [comment]
@rlepinski I sent in-app messages in UA admin panel, and also I always called finished() method like you do it in example

**Comment by rlepinski** [comment]
I just tried it and I am also blocked. I think we probably have a bug where if you call finished in onDisplay its not ready for it yet. This is working:
```
    Handler(Looper.getMainLooper()).postDelayed({
                    displayHandler.finished(ResolutionInfo.timedOut(), 3000);
                }, 3000)
```

**Comment by rlepinski** [comment]
Yeah found the issue, will be fixed in the next patch release. A workaround is just to make sure the onFinished is called on the next run loop.

**Comment by ivanessence** [comment]
@rlepinski Yes, using finished() method in main thread really work. Note that in official documentation method onDisplay() has annotation @MainThread. Thanks a lot for help.
