### ISSUE TITLE
Fatal Exception: android.database.CursorWindowAllocationException Cursor window allocation of 2048 kb failed.

### ISSUE THREAD

**Issue by halysongoncalves** [urbanairship/android-library#150]
Hello,

We have identified crash in `CursorWindow.java ` that has affected our users.
 

`   android.database.CursorWindow.<init> (CursorWindow.java:108)
android.database.AbstractWindowedCursor.clearOrCreateWindow (AbstractWindowedCursor.java:225)
android.database.sqlite.SQLiteCursor.fillWindow (SQLiteCursor.java:149)
android.database.sqlite.SQLiteCursor.getCount (SQLiteCursor.java:143)
android.database.AbstractCursor.moveToPosition (AbstractCursor.java:219)
android.database.AbstractCursor.moveToFirst (AbstractCursor.java:258)
androidx.work.impl.model.SystemIdInfoDao_Impl.getSystemIdInfo (SystemIdInfoDao_Impl.java:93)
androidx.work.impl.background.systemjob.SystemJobScheduler.schedule (SystemJobScheduler.java:104)
androidx.work.impl.Schedulers.schedule (Schedulers.java:91)
androidx.work.impl.utils.ForceStopRunnable.run (ForceStopRunnable.java:100)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
java.lang.Thread.run (Thread.java:761)`

![Captura de Tela 2020-04-23 às 09 42 10](https://user-images.githubusercontent.com/5872045/80100769-cd7dcc80-8546-11ea-95af-d57c68dc56a1.png)
![Captura de Tela 2020-04-23 às 09 42 06](https://user-images.githubusercontent.com/5872045/80100772-ceaef980-8546-11ea-99b1-dc9638b2c717.png)
![Captura de Tela 2020-04-23 às 09 41 45](https://user-images.githubusercontent.com/5872045/80100774-cf479000-8546-11ea-9848-69802a09afa0.png)

**Comment by rlepinski** [comment]
That stack trace is an exception in work manager which our SDK does not use. I dont think this is our crash.  Its hard for me to know for sure with the limited info but I believe the airship threads are unrelated.
