### ISSUE TITLE
App is opening on top of external resource opened by Push Notification with action OpenExternalUrlAction

### ISSUE THREAD

**Issue by mutaquihadev** [urbanairship/android-library#154]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

 com.urbanairship.android:urbanairship-fcm:13.1.2
com.urbanairship.android:urbanairship-message-center:13.1.2
com.urbanairship.android:urbanairship-automation:13.1.2
### What are the versions of any relevant development tools you are using?

 Android Studio 4.0
# Report

### What unexpected behavior are you seeing?

 When I open a push notification sent with the action *OpenExternalUrlAction*, the browser opens first and then the app opens on top of the browser (or another app opened by the link contained in the action). 

### What is the expected behavior?

I would like to process the link after the app opening. The expected flow is: click notification, open app, and then open the external resource (browser or app) 
### What are the steps to reproduce the unexpected behavior?

To reproduce the unexpected behavior I'm following the steps:
1. Close App
2. Send Push Notification using Dashboard, with the Action *Web Page* 
3. Click on the push notification received
The issue also occurs with the app on foreground in emulator
### Do you have logging for the issue?

Not Applicable

I tried to *override* the behaviour of OpenExternalUrlAction by implementing a CustomAction with the same name, but I ran into some issues that I struggled to understand while reading the documentation, I couldn't get which place was the ideal to implement the predicate to prevent OpenExternalUrl to run (The AutoPilot?, My Launcher Activity?).

**Comment by crow** [comment]
@mutaquihadev Currently looking into this. Thanks for reporting.

**Comment by rlepinski** [comment]
@mutaquihadev Thats normally how the links work. We launch the app then run any actions. Could you provide your notification listener? Are you using any kind of threading in your launcher activity?

**Comment by mutaquihadev** [comment]
I'm not using any kind of threading in my launcher activity. 
I'm not using the NotificationListener provided in the Urbar SDK.

My autopilot is implemented as follows: 

`public class UAAutopilot extends Autopilot {

    @Override
    public void onAirshipReady(@NonNull UAirship airship) {
        airship.getPushManager().setUserNotificationsEnabled(true);
        airship.getPushManager().addPushListener(new UAPushListener());

        // Define actions for the group
        NotificationActionButton actionButtonPost = new NotificationActionButton.Builder("post")
                .setLabel(R.string.bt_urban_post)
                .setPerformsInForeground(true)
                .build();
        NotificationActionButton actionButtonVerify = new NotificationActionButton.Builder("verify")
                .setLabel(R.string.bt_urban_verify)
                .setPerformsInForeground(true)
                .build();
        NotificationActionButton actionButtonAsk = new NotificationActionButton.Builder("ask")
                .setLabel(R.string.bt_urban_ask)
                .setPerformsInForeground(true)
                .build();
        NotificationActionButton actionButtonCancel = new NotificationActionButton.Builder("cancel")
                .setLabel(R.string.bt_urban_cancel)
                .setPerformsInForeground(true)
                .build();

        NotificationActionButtonGroup btGroupPostCancel = new NotificationActionButtonGroup.Builder()
                .addNotificationActionButton(actionButtonPost)
                .addNotificationActionButton(actionButtonCancel)
                .build();
        airship.getPushManager().addNotificationActionButtonGroup("homer_post_cancel", btGroupPostCancel);

        NotificationActionButtonGroup btGroupVerifyCancel = new NotificationActionButtonGroup.Builder()
                .addNotificationActionButton(actionButtonVerify)
                .addNotificationActionButton(actionButtonCancel)
                .build();
        airship.getPushManager().addNotificationActionButtonGroup("homer_verify_cancel", btGroupVerifyCancel);

        NotificationActionButtonGroup btGroupAskCancel = new NotificationActionButtonGroup.Builder()
                .addNotificationActionButton(actionButtonAsk)
                .addNotificationActionButton(actionButtonCancel)
                .build();
        airship.getPushManager().addNotificationActionButtonGroup("homer_ask_cancel", btGroupAskCancel);
    }
}
`

**Comment by rlepinski** [comment]
What is the default activity you are launching? Could you share that? What about UAPushListener?

I was unable to reproduce in our sample.

**Comment by mutaquihadev** [comment]
Here is my Launcher Activity 

`package com.corretorvip.app.br.activities.entrance;

import android.animation.Animator;
import android.animation.AnimatorListenerAdapter;
import android.annotation.SuppressLint;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.graphics.Color;
import android.os.Bundle;
import android.os.SystemClock;
import android.view.View;
import android.widget.TextView;

import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.app.NotificationManagerCompat;

import com.corretorvip.app.br.R;
import com.corretorvip.app.br.activities.MainActivity;
import com.corretorvip.app.br.app.App;
import com.corretorvip.app.br.app.Const;
import com.corretorvip.app.br.app.PrefsManager;
import com.corretorvip.app.br.customview.SingleClickListener;
import com.corretorvip.app.br.enums.AppOpenMethod;
import com.corretorvip.app.br.enums.JoinedBy;
import com.corretorvip.app.br.helpers.PropertyTypeHelper;
import com.corretorvip.app.br.helpers.ToastHelper;
import com.corretorvip.app.br.mixpanel.Mixpanel;
import com.corretorvip.app.br.mixpanel.MixpanelPrefs;
import com.corretorvip.app.br.mixpanel.PropertyValuePair;
import com.corretorvip.app.br.rest.CustomCallback;
import com.corretorvip.app.br.rest.homer.HomerService;
import com.corretorvip.app.br.rest.homer.model.User;
import com.corretorvip.app.br.rest.homer.response.FullPropertyTypeResponse;
import com.corretorvip.app.br.rest.homer.response.UserResponse;
import com.corretorvip.app.br.utils.LogUtils;
import com.corretorvip.app.br.widget.HomerProgressBar;
import com.google.firebase.crashlytics.FirebaseCrashlytics;

import org.json.JSONException;
import org.json.JSONObject;

import java.util.Timer;
import java.util.TimerTask;

import io.branch.referral.Branch;

public class SplashActivity extends AppCompatActivity {

    /**
     * Constants
     */
    public static final int DELAY_TO_SHOW_SLOW_CONNECTION_MSG = 7000;
    public static final int MIN_MILLIS_TO_SHOW_RETRY_BUTTON = 30000;

    /**
     * Views
     */
    private HomerProgressBar progress;
    private View viewTryAgain;

    /**
     * Attributes
     */
    private Timer timerToShowSlowConnectionMsg;
    private Timer timerToShowRetryButton;
    private long startRequestMillis;
    private boolean onlyLoadInitialData;
    private Branch.BranchReferralInitListener branchReferralInitListener = (referringParams, error) -> {
        if (error != null) {
            FirebaseCrashlytics.getInstance().log("Branch.BranchReferralInitListener.onInitFinished ERROR: " + error);
        }

        handleBranchInitFinished(referringParams);
    };

    public static void startSplash(Context context, User user, JoinedBy joinedBy) {
        Intent intent = new Intent(context, SplashActivity.class);
        if (!(context instanceof Activity)) {
            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        }
        intent.putExtra(Const.KEY_USER, user);
        intent.putExtra(Const.KEY_JOINED_BY, joinedBy);
        intent.putExtra(Const.KEY_ONLY_LOAD_INITIAL_DATA, true);
        context.startActivity(intent);
    }

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_splash);

        startRequestMillis = 0;
        onlyLoadInitialData = getIntent().getBooleanExtra(Const.KEY_ONLY_LOAD_INITIAL_DATA, false);

        viewTryAgain = findViewById(R.id.actSplash_viewTryAgain);
        viewTryAgain.setVisibility(View.GONE);

        TextView tvTryAgain = findViewById(R.id.actSplash_tvTryAgain);
        tvTryAgain.setOnClickListener(new SingleClickListener() {
            @Override
            public void onSingleClick(View v) {
                startRequestMillis = SystemClock.elapsedRealtime();

                progress.setAlpha(0f);
                progress.setVisibility(View.VISIBLE);
                progress.animate()
                        .alpha(1f)
                        .setDuration(Const.SHORT_ANIM_TIME)
                        .setListener(null);

                viewTryAgain.setAlpha(1f);
                viewTryAgain.animate()
                        .alpha(0f)
                        .setDuration(Const.SHORT_ANIM_TIME)
                        .setListener(new AnimatorListenerAdapter() {
                            @Override
                            public void onAnimationEnd(Animator animation) {
                                viewTryAgain.setVisibility(View.GONE);
                            }
                        });

                requestInitialData();
            }
        });

        progress = findViewById(R.id.actSplash_progress);
        progress.setColor(Color.WHITE);
        progress.setVisibility(View.VISIBLE);

        if (onlyLoadInitialData) {
            requestInitialData();

        } else {
            PrefsManager.getInstance().setDeeplink(null);
            PrefsManager.getInstance().setBranchReferral(false);

            checkSystemDeeplink();

            startTimerToShowSlowConnectionMsg();
        }

        trackAppOpen();
    }

    @Override
    protected void onStart() {
        super.onStart();
        if (onlyLoadInitialData) {
            return;
        }

        Branch.sessionBuilder(this).withCallback(branchReferralInitListener).withData(getIntent() != null ? getIntent().getData() : null).init();
    }

    @SuppressLint("MissingSuperCall")
    @Override
    protected void onNewIntent(Intent intent) {
        if (onlyLoadInitialData) {
            return;
        }

        setIntent(intent);
        Branch.sessionBuilder(this).withCallback(branchReferralInitListener).reInit();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();

        cancelTimerToShowSlowConnectionMsg();
        cancelTimerToShowRetryButton();
    }

    private void startTimerToShowSlowConnectionMsg() {
        timerToShowSlowConnectionMsg = new Timer();
        timerToShowSlowConnectionMsg.schedule(new TimerTask() {
            @Override
            public void run() {
                runOnUiThread(() -> ToastHelper.show(R.string.msg_internet_connection_slow));
            }
        }, DELAY_TO_SHOW_SLOW_CONNECTION_MSG);
    }

    private void cancelTimerToShowSlowConnectionMsg() {
        if (timerToShowSlowConnectionMsg != null) {
            timerToShowSlowConnectionMsg.cancel();
        }
    }

    private void handleBranchInitFinished(@Nullable JSONObject referringParams) {
        LogUtils.e("handleBranchInitFinished referringParams: " + referringParams);
        if (PrefsManager.getInstance().isLogged()) {
            // Metrics
            MixpanelPrefs.getInstance().setAppOpenMethod(AppOpenMethod.REGULAR);

            checkBranchDeeplinkAndReferralCampaign(referringParams);

            requestInitialData();

        } else {
            App.getInstance().logout(); // Force logout/unregister on APIs

            checkBranchDeeplinkAndReferralCampaign(referringParams);

            Intent intent = new Intent(getBaseContext(), JoinActivity.class);
            startActivity(intent);

            finish();
        }
    }

    private void checkBranchDeeplinkAndReferralCampaign(JSONObject referringParams) {
        if (referringParams == null) {
            checkSystemDeeplink();
            return;
        }

        // Manage referral
        String campaign = null;
        try {
            if (referringParams.has(Const.BRANCH_KEY_CAMPAIGN)) {
                campaign = referringParams.getString(Const.BRANCH_KEY_CAMPAIGN);
            }
        } catch (JSONException e) {
            LogUtils.e("Error parsing Branch campaign.", e);
        }
        LogUtils.e("handleBranchInitFinished campaign: " + campaign);
        if (Const.BRANCH_CAMPAIGN_REFERRAL.equals(campaign)) {
            PrefsManager.getInstance().setBranchReferral(true);
        }

        // Manage deeplink
        String deeplink = null;
        try {
            if (referringParams.has(Const.BRANCH_KEY_DEEPLINK_PATH)) {
                deeplink = referringParams.getString(Const.BRANCH_KEY_DEEPLINK_PATH);
            }
        } catch (JSONException e) {
            LogUtils.e("Error parsing Branch deeplink.", e);
        }
        if (deeplink == null || deeplink.isEmpty()) {
            try {
                if (referringParams.has(Const.BRANCH_KEY_ANDROID_DEEPLINK_PATH)) {
                    deeplink = referringParams.getString(Const.BRANCH_KEY_ANDROID_DEEPLINK_PATH);
                }
            } catch (JSONException e) {
                LogUtils.e("Error parsing Branch deeplink.", e);
            }
        }
        LogUtils.d("checkBranchDeeplinkAndReferralCampaign deeplink: " + deeplink);

        if (deeplink == null || deeplink.isEmpty()) {
            checkSystemDeeplink();
        } else {
            PrefsManager.getInstance().setDeeplink(deeplink);
        }
    }

    private void checkSystemDeeplink() {
        Intent intent = getIntent();
        if (intent != null && intent.getData() != null) {
            String deeplink = intent.getData().getPath();
            if (deeplink != null && !deeplink.isEmpty()) {
                String query = intent.getData().getQuery();
                if (query != null && !query.isEmpty()) {
                    deeplink = deeplink + "?" + query;
                }

                LogUtils.d("checkSystemDeeplink deeplink: " + deeplink);
                PrefsManager.getInstance().setDeeplink(deeplink);
            }
        }
    }

    private void requestInitialData() {
        User user = (User) getIntent().getSerializableExtra(Const.KEY_USER);
        if (user == null) {
            requestUserDetails();

        } else {
            handleUserReceived(user);
        }
    }

    private void requestUserDetails() {
        HomerService.getUser(PrefsManager.getInstance().getUserId(), new CustomCallback.OnResult<UserResponse>() {
            @Override
            public void onSuccess(UserResponse response) {
                onRequestUserDetailsSuccess(response);
            }

            @Override
            public void onFailure() {
                LogUtils.e("Error requesting user details.");
                onRequestFailure();
            }
        });
    }

    private void onRequestUserDetailsSuccess(UserResponse response) {
        if (response == null) {
            LogUtils.e("Error requesting user details: response == null");
            onRequestFailure();

        } else if (response.getError() != null) {
            LogUtils.e("Error requesting user details: " + response.getError().getMessage());
            onRequestFailure();

        } else if (response.getResult() == null) {
            LogUtils.e("Error requesting user details: response.result == null");
            onRequestFailure();

        } else {
            handleUserReceived(response.getResult());
        }
    }

    private void handleUserReceived(User user) {
        PrefsManager.getInstance().setUser(user);

        Mixpanel.getInstance().setUser(user, false);

        requestPropertyTypes(user);
    }

    private void requestPropertyTypes(final User user) {
        HomerService.getPropertyTypes(new CustomCallback.OnResult<FullPropertyTypeResponse>() {
            @Override
            public void onSuccess(FullPropertyTypeResponse response) {
                onRequestPropertyTypesSuccess(user, response);
            }

            @Override
            public void onFailure() {
                LogUtils.e("Error requesting property types.");
                onRequestFailure();
            }
        });
    }

    private void onRequestPropertyTypesSuccess(User user, FullPropertyTypeResponse response) {
        if (response == null) {
            LogUtils.e("Error requesting property types: response == null");
            onRequestFailure();

        } else if (response.getError() != null) {
            LogUtils.e("Error requesting property types: " + response.getError().getMessage());
            onRequestFailure();

        } else if (response.getResult() == null) {
            LogUtils.e("Error requesting property types: response.result == null");
            onRequestFailure();

        } else if (response.getResult().isEmpty()) {
            LogUtils.e("Error requesting property types: response.result is empty");
            onRequestFailure();

        } else {
            cancelTimerToShowRetryButton();

            PropertyTypeHelper.getInstance().cachePropertyTypes(response.getResult());

            Intent intent = new Intent(getBaseContext(), MainActivity.class);
            intent.putExtra(Const.KEY_JOINED_BY, getIntent().getSerializableExtra(Const.KEY_JOINED_BY));
            intent.putExtra(Const.KEY_USER, user);
            startActivity(intent);
            finish();
        }
    }

    private void onRequestFailure() {
        cancelTimerToShowSlowConnectionMsg();

        long elapsedMillis = SystemClock.elapsedRealtime() - startRequestMillis;
        if (elapsedMillis < MIN_MILLIS_TO_SHOW_RETRY_BUTTON) {
            startTimerToShowRetryButton(MIN_MILLIS_TO_SHOW_RETRY_BUTTON - elapsedMillis);

        } else {
            viewTryAgain.setAlpha(0f);
            viewTryAgain.setVisibility(View.VISIBLE);
            viewTryAgain.animate()
                    .alpha(1f)
                    .setDuration(Const.SHORT_ANIM_TIME)
                    .setListener(null);

            progress.setAlpha(1f);
            progress.animate()
                    .alpha(0f)
                    .setDuration(Const.SHORT_ANIM_TIME)
                    .setListener(new AnimatorListenerAdapter() {
                        @Override
                        public void onAnimationEnd(Animator animation) {
                            progress.setVisibility(View.GONE);
                        }
                    });
        }
    }

    private void startTimerToShowRetryButton(long delay) {
        timerToShowRetryButton = new Timer();
        timerToShowRetryButton.schedule(new TimerTask() {
            @Override
            public void run() {
                runOnUiThread(() -> onRequestFailure());
            }
        }, delay);
    }

    private void cancelTimerToShowRetryButton() {
        if (timerToShowRetryButton != null) {
            timerToShowRetryButton.cancel();
        }
    }

    private void trackAppOpen() {
        boolean isNotificationEnabled = NotificationManagerCompat.from(this).areNotificationsEnabled();
        Mixpanel.getInstance().track(R.string.event_app_open,
                new PropertyValuePair(getString(R.string.property_notification), String.valueOf(isNotificationEnabled)));
    }
}`

**Comment by mutaquihadev** [comment]
Im using UAPushListener only to handle DeepLinks

`package com.corretorvip.app.br.uairship;

import android.net.Uri;

import androidx.annotation.NonNull;

import com.corretorvip.app.br.app.PrefsManager;
import com.corretorvip.app.br.helpers.DeepLinkHelper;
import com.corretorvip.app.br.helpers.SystemListeners;
import com.corretorvip.app.br.receiver.FirstStepsReceiver;
import com.corretorvip.app.br.receiver.MyPostsReceiver;
import com.corretorvip.app.br.receiver.ProfileReceiver;
import com.corretorvip.app.br.receiver.VisitStatusReceiver;
import com.corretorvip.app.br.utils.LogUtils;
import com.google.firebase.crashlytics.FirebaseCrashlytics;
import com.urbanairship.actions.ActionValue;
import com.urbanairship.push.PushListener;
import com.urbanairship.push.PushMessage;

public class UAPushListener implements PushListener {

    @Override
    public void onPushReceived(@NonNull PushMessage message, boolean notificationPosted) {
        LogUtils.i("UAPushListener - Received push message. Alert: " + message.getAlert() + ". posted notification: " + notificationPosted);

        final String keyUADeeplink = "^d";

        if (message.getActions().containsKey(keyUADeeplink)) {
            ActionValue value = message.getActions().get(keyUADeeplink);
            if (value != null && value.getString() != null) {
                Uri uri = Uri.parse(value.getString());

                String path = DeepLinkHelper.removePrefixSplash(uri.getPath());
                if (path == null) {
                    return;
                }

                switch (path) {
                  //handling deeplink
                }
            }
        }
    }
}
`

**Comment by rlepinski** [comment]
I think what is happening is your SplashActivity is asynchronous and starts the activity from a task kicked off during onStart:

SplashActivity.onStart -> Branch.sessionBuilder(this).withCallback(branchReferralInitListener) -> startActivity

I am not super familiar with branch, but it looks like it does a request before calling the callback, so what you are probably seeing is:

Notification Click -> SplashActivity.onCreate -> SplashActivity.onStart -> Open external URL -> Branch Callback -> startActivity

You can either change your SplashActivity to stop branch during onStop, or you can just route the open external url action behavior through the SplashActivity with a custom action:

During onAirshipReady in your Autopilot:
```
 airship.getActionRegistry().getEntry(OpenExternalUrlAction.DEFAULT_REGISTRY_NAME)
               .setDefaultAction(new OpenExternalUrlAction() {
                   @NonNull
                   @Override
                   public ActionResult perform(@NonNull ActionArguments arguments) {
                       Intent intent = new Intent(UAirship.getApplicationContext(), SplashActivity.class)
                               .putExtra("airship_open_external_url", arguments.getValue().toString())
                               .addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                       
                       UAirship.getApplicationContext().startActivity(intent);
                       return ActionResult.newResult(arguments.getValue());
                   }
               });
```
              
Then in your splash activity you will need to look for the extra `airship_open_external_url` or however you want to route the data to your activity.

**Comment by mutaquihadev** [comment]
Thanks @rlepinski, 
I will make some adjustments and test the suggestions you made.
I will report the results. 
Thank you very much for being so helpful!

**Comment by mutaquihadev** [comment]
@rlepinski @crow I was able to solve the issue following the suggestion made by @rlepinski.
I implemented the entry of OpenExternalUrlAction.DEFAULT_REGISTRY_NAME, and made some adjustments to route the value (URL) to another activity, and then I opened the browser "manually". 
After this, I got the expected behavior.
