### ISSUE TITLE
ANR:  urbanairship-location 13.2.0

### ISSUE THREAD

**Issue by ZhangShuFly** [urbanairship/android-library#155]
### ℹ When I test, I click the app icon to start the app. When the splash page is closed and the main page is displayed, "UALib: Location update took too long, ending broadcast." will be printed in the log.

# Preliminary Info

### What Airship dependencies are you using?
ℹ   def airshipVersion = "13.2.0"
    api "com.urbanairship.android:urbanairship-fcm:$airshipVersion"
    api "com.urbanairship.android:urbanairship-message-center:$airshipVersion"
    api "com.urbanairship.android:urbanairship-automation:$airshipVersion"
    api "com.urbanairship.android:urbanairship-location:$airshipVersion"

    Integration using autopilot.
### What are the versions of any relevant development tools you are using?
 ℹAndroid Studio 4.0

# Report

### What unexpected behavior are you seeing?

ℹANR in LocationReceiver

### What is the expected behavior?

ℹNo ANR

### What are the steps to reproduce the unexpected behavior?

ℹ  This can be seen from Google play console

### Do you have logging for the issue?

ℹ[anr_1.txt](https://github.com/urbanairship/android-library/files/4901287/anr_1.txt)
ℹ[anr_2.txt](https://github.com/urbanairship/android-library/files/4901340/anr_2.txt)

**Comment by rlepinski** [comment]
Can you provide the other logs when you are able to reproduce with `UALib: Location update took too long, ending broadcast` in the logs? Have you tried enabling strict mode to verify no network or disk io is happening on the main thread? You mention `autopilot` but in the previous ticket you were not using it. Could you provide more details on how you are integrating with Airship.

**Comment by ZhangShuFly** [comment]
ℹWhen I saw "UALib: Location update took too long, ending broadcast"." APP did not have ANR, so I did not save the log.

ℹThe previous version and the latest version, I used StrictMode to verify,  everything is OK.

ℹIn the previous version of the app (UA version 12.2.0), I used UAirship.takeOff to integrate in Application.onCreate. Because I am not sure whether it has anything to do with the integration method, in the latest version (UA version 13.2.0) I use Autopilot instead. 
`



    override fun onAirshipReady(airship: UAirship)
    {
        super.onAirshipReady(airship)
        val preferences = UAirship.getApplicationContext().getSharedPreferences(PREFERENCES_NAME, Context.MODE_PRIVATE)
        val isFirstRun = preferences.getBoolean(FIRST_RUN_KEY, true)
        if (isFirstRun)
        {
            preferences.edit().putBoolean(FIRST_RUN_KEY, false).apply()
            enablePushNotification()
        }

        val airshipListener = AirshipListener()
        airship.pushManager.addPushListener(airshipListener)
        airship.pushManager.addPushTokenListener(airshipListener)
        airship.pushManager.notificationListener = airshipListener
        airship.channel.addChannelListener(airshipListener)

        setDeepLinkPredicate()
        setLandingPagePredicate()
    }

    private fun enablePushNotification()
    {
        val pushManager = UAirship.shared().pushManager
        pushManager.isPushEnabled = true
        pushManager.userNotificationsEnabled = true
        AirshipLocationManager.shared().isLocationUpdatesEnabled = true
        AirshipLocationManager.shared().isBackgroundLocationAllowed = true
    }

    private fun setDeepLinkPredicate()
    {
        val lp = UAirship.shared().actionRegistry.getEntry(DeepLinkAction.DEFAULT_REGISTRY_NAME)
        lp?.predicate = rejectDeepLinkPushOpenedPredicate
    }

    private fun setLandingPagePredicate()
    {
        val lp = UAirship.shared().actionRegistry.getEntry(LandingPageAction.DEFAULT_REGISTRY_NAME)
        lp?.predicate = rejectPushOpenedPredicate
    }


`

ℹ I also read the code in "LocalReceiver" class , which has set a timeout of 9 seconds, and then print the log UALib: Location update took too long, ending broadcast".

ℹSo I want to know that there is already a timeout setting of 9 seconds in "LocalReceiver.onReceiver()", why is there still ANR related to LocalReceiver. Or you have determined that the code in Application.onCreate caused the thread to be suspended?

ℹFrom the Google Play console, more than 90% of current ANRs are related to "com.urbanairship.location.LocationReceiver". If there are other possible reasons for this ANR, please let me know.  I'll verify it.

**Comment by rlepinski** [comment]
When the intent is received, it hits more than just our LocaleReceiver:
ContentProviders.onCreate -> Application.onCreate -> LocaleChangeReceiver.onReceive. If you have any deadlocks in your code, or if your application takes too long to start up you might receive an ANR. I made a change to the `LocaleChangeReceiver.onReceive` to only take 9 seconds max, but thats after Application.onCreate is called. The change would handle slow takeOffs but can't do anything about an application that is hung or taking more than 10 seconds. 

I believe you have a deadlock somewhere in your code that is unrelated to Airship. If you can, please benchmark your application startup time and see if you can reduce the amount of work you do in `Application#onCreate`.

**Comment by ZhangShuFly** [comment]
ℹI also believe that it has nothing to do with LocalReceiver. It should be caused by the long time of oncreate or deadlock.  I will continue to check the code in Application.onreate. 

ℹPlease help me look at this log([anr_3.txt](https://github.com/urbanairship/android-library/files/4922763/anr_3.txt)), the main thread is blocked by takeoff.

ℹ So please help me determine again if the ANR is not caused by Airship.takeoff.

**Comment by rlepinski** [comment]
Looks like its a deadlock on AssetManager but its not clear to me whats blocked in Airship. Do you have an easy way to reproduce? What about other ANR reports? For ANR 3 could you give me the device & OS breakdown and how many users are experiencing it?

**Comment by ZhangShuFly** [comment]
ℹI can't reproduce at all. There are less than 100 users reporting the ANR 3 in the last seven days.
ℹDevice & OS for example :
> LGE LG Stylo 3 Plus (sf340n), 2048MB RAM, Android 7.0
> Verizon Wireless Ellipsis 8 (QTAQZ3), 1024MB RAM, Android 5.1
> Coolpad 3705A (lithium), 3072MB RAM, Android 9
> Samsung` Galaxy J3 Emerge (j3popltespr), 1536MB RAM, Android 6.0

ℹ Look at this kind of [anr_4.txt](https://github.com/urbanairship/android-library/files/4931889/anr_4.txt). The main thread is blocked, but the airship thread has ended.

ℹSo I want to make sure, is  [anr_1.txt](https://github.com/urbanairship/android-library/files/4901287/anr_1.txt)  related to this?

**Comment by rlepinski** [comment]
So anr_4 looks the same as anr_3, but instead of a deadlock i think you are having an issue with slow app start time. Assuming its related, anr_1 is probably the total time to process the intent was longer than 10 seconds due to slow app start up time. 

Is there any work you can delay until the app is foregrounded (moving it out of Applicaiton#onCreate)?

**Comment by ZhangShuFly** [comment]
Thanks. I'll keep checking Applicaion.oncreate code.
