### ISSUE TITLE
can't find info for `ActionService.runActions()` Migrating from 9 -> 13

### ISSUE THREAD

**Issue by ForrestTracy** [urbanairship/android-library#157]
Migrating an enterprise Android application from UAirship from from 9.4.1 -> 13.3.1
ℹ  `com.urbanairship.actions.ActionService;` is missing and there is no clear replacement that I can find in the migration docs. I have looked through all migration docs (9->10, 10->11, 11->12, 12->13) and found nothing. 
Any help would be greatly appreciated. Thanks in advance!
   - Forrest 

# Preliminary Info

### What Airship dependencies are you using?
ℹ  UAirship from from 9.4.1 -> 13.3.1

### What are the versions of any relevant development tools you are using?
ℹ  N/A Android studio version shouldn't impact this

# Report

### What unexpected behavior are you seeing?
 ℹ  Trying to call ActionService.runActions() , specifically, and not able to find the new method that should be called in its place. 

### What is the expected behavior?
N/A

### What are the steps to reproduce the unexpected behavior?
N/A

### Do you have logging for the issue?
N/A

**Comment by rlepinski** [comment]
Where are you trying to call ActionService.runActions, in what context? I believe we abandoned that service because of background restrictions in Android O.

We replaced internally with running actions inline on an executor (execution happens on a thread pool executor by default):
```
    for (Map.Entry<String, ActionValue> action : actions.entrySet()) {
            ActionRunRequest.createRequest(action.getKey())
                            .setMetadata(metadata)
                            .setValue(action.getValue())
                            .setSituation(Action.SITUATION_PUSH_RECEIVED)
                            .run();
        }
```

**Comment by ForrestTracy** [comment]
Thanks so much for the quick response. 
In my app, a custom `InboxFragment.onMessageOpen()` is calling `ActionService.runActions()`. 
I'm a bit unclear about what this was supposed to be doing and how it should be replaced with new functionality. It looks like it would open another view with greater message detail. Is that correct? If so, is there a clear replacement?

**Comment by rlepinski** [comment]
Yeah, it's not obvious what it's supposed to be doing. Actions are just named functions, so it really depends on what `msg.getAlert()` contains. I assume alert is a string, so based on the[ ActionService method](https://github.com/urbanairship/android-library/blob/9.5.3/urbanairship-core/src/main/java/com/urbanairship/actions/ActionService.java#L114,) the replacement would be:

```
private void runActions(@Nullable String actionsPayload) {
        if (UAStringUtil.isEmpty(actionsPayload)) {
            return;
        }

        JsonMap actionsMap;
        try {
             actionsMap = JsonValue.parseString(actionsPayload).optMap();
        } catch (JsonException e) {
            // Log?
            return;
        }

        for (Map.Entry<String, JsonValue> entry : actionsMap.entrySet()) {
            ActionRunRequest.createRequest(entry.getKey())
                            .setValue(entry.getValue())
                            .setSituation(Action.SITUATION_PUSH_OPENED)
                            .run();
        }
    }
```

```
runActions(msg.getAlert());`
```

If you inspect the msg.getAlert() and it does not contain a JSON object of, then I kinda doubt it ever did anything.

**Comment by ForrestTracy** [comment]
Thanks for your help @rlepinski . Much appreciated.
