### ISSUE TITLE
Android O - AlarmManager won't start service

### ISSUE THREAD

**Issue by filipebatista** [urbanairship/android-library#16]
Hi,

Although you have added the compatibility for Android O in the version 8.6.0 of the SDK doesn't work correctly in that version. 

Analyzing the logcat i see several entries of the ActivityManager trying to start the AirshipService but not being able to. 

`07-04 14:39:06.926 1500-1728/system_process W/ActivityManager: Background start not allowed: service Intent { act=RUN_JOB cmp=com.myapp.superapp/com.urbanairship.AirshipService (has extras) } to com.myapp.superapp/com.urbanairship.AirshipService from pid=3320 uid=10084 pkg=com.myapp.superapp
07-04 14:39:16.933 1500-1557/system_process W/ActivityManager: Background start not allowed: service Intent { act=RUN_JOB cat=[df4af9f8-5e35-4d93-b4d6-44a39af00612] flg=0x4 cmp=com.myapp.superapp/com.urbanairship.AirshipService (has extras) } to com.myapp.superapp/com.urbanairship.AirshipService from pid=-1 uid=10084 pkg=com.myapp.superapp
07-04 14:39:16.934 1500-1557/system_process W/ActivityManager: Background start not allowed: service Intent { act=RUN_JOB cat=[c309b521-9eee-4433-b4b1-18677893c0e5] flg=0x4 cmp=com.myapp.superapp/com.urbanairship.AirshipService (has extras) } to com.myapp.superapp/com.urbanairship.AirshipService from pid=-1 uid=10084 pkg=com.myapp.superapp
07-04 14:39:16.934 1500-1557/system_process W/ActivityManager: Background start not allowed: service Intent { act=RUN_JOB cat=[com.urbanairship.push.ACTION_UPDATE_TAG_GROUPS] flg=0x4 cmp=com.myapp.superapp/com.urbanairship.AirshipService (has extras) } to com.myapp.superapp/com.urbanairship.AirshipService from pid=-1 uid=10084 pkg=com.myapp.superapp
07-04 14:39:16.934 1500-1557/system_process W/ActivityManager: Background start not allowed: service Intent { act=RUN_JOB cat=[com.urbanairship.push.ACTION_UPDATE_NAMED_USER] flg=0x4 cmp=com.myapp.superapp/com.urbanairship.AirshipService (has extras) } to com.myapp.superapp/com.urbanairship.AirshipService from pid=-1 uid=10084 pkg=com.myapp.superapp
07-04 14:39:16.934 1500-1557/system_process W/ActivityManager: Background start not allowed: service Intent { act=RUN_JOB cat=[com.urbanairship.push.ACTION_UPDATE_CHANNEL_REGISTRATION] flg=0x4 cmp=com.myapp.superapp/com.urbanairship.AirshipService (has extras) } to com.myapp.superapp/com.urbanairship.AirshipService from pid=-1 uid=10084 pkg=com.myapp.superapp`

This  is related to the `AlarmManager ` and with the `PendingIntent.getService `
[AlarmScheduler.java#L93](https://github.com/urbanairship/android-library/blob/master/urbanairship-sdk/src/main/java/com/urbanairship/job/AlarmScheduler.java#L93)

The background service limitations are also applied to situations of starting a service through the AlarmManager when creating the Pending Intent with `PendingIntent.getService()`. This is somewhat described here:

https://developer.android.com/reference/android/app/PendingIntent.html#getService(android.content.Context,%20int,%20android.content.Intent,%20int)

>Retrieve a PendingIntent that will start a service, **like calling Context.startService()**.

**Comment by BrianBatchelder** [comment]
@filipebatista: thanks for reporting this. I have a few questions for you:

1. Are you seeing any operational failures, or just the logged warnings?
2. What version of Android O are you testing on?
3. Have you tested with SDK version 8.6.1?

**Comment by filipebatista** [comment]
Hi @BrianBatchelder 

> 1. Are you seeing any operational failures, or just the logged warnings?

I don't see operational failures but i can't be sure since i don't have a way to confirm that. If i run the application in foreground, it seems that the services are initialised correctly, but if the application is started in background, e.g. boot event , the services warning appear. Which makes me wonder that, if the entire app logic is started at boot (like we already do) and we initialise for the first time the app during boot, (e.g.: all logic runs from the start, in background), I don’t know if the logic to properly generate a channel ID and send it to the server is correctly done.

Plus, some of the failing actions concern features that we are using such as tag grouping. I haven’t tested but I guess that tags added in background (like we already do) won’t be sent back to the server because the alarms won’t wake up a service in background.

> 2. What version of Android O are you testing on?

The version is 8.0.0. I have tested in the latest version of the Android Emulator 

>3. Have you tested with SDK version 8.6.1?

Yes i have tested with the latest version of the SDK  - 8.6.1

**Comment by rlepinski** [comment]
@filipebatista We actually use a gcm network manager by default, but fallback to the alarm manager based scheduler if the gcm network manager is unavailable. I think the warnings you are seeing is sometimes we try to run the job immediately if we can, and fallback to scheduling. I did not realize it was logging those warnings, we can fix it in a patch release.

The alarm manager fallback is still an issue though if it does not work with android O. We will look into it and report back our findings.

**Comment by rlepinski** [comment]
@filipebatista Yep, alarm manager based scheduler is broken. Working on a release that falls back to the standard Android JobScheduler.

**Comment by filipebatista** [comment]
@rlepinski  
Excellent, thank you.

**Comment by rlepinski** [comment]
@filipebatista Fixed in 8.7.0. Please reopen if you run into any other issues.

**Comment by newstarbka** [comment]
Use getForegroundService for android O like this :
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
				 pit = PendingIntent.getForegroundService(
						appCtxt, 0, it, PendingIntent.FLAG_CANCEL_CURRENT);
			} else {
				pit = PendingIntent.getService(
						appCtxt, 0, it, PendingIntent.FLAG_CANCEL_CURRENT);
			}
