### ISSUE TITLE
Any reason to not provide sourcesJar ?

### ISSUE THREAD

**Issue by G00fY2** [urbanairship/android-library#161]
Hi everyone, more a question/feature request:

❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?
`implementation "com.urbanairship.android:urbanairship-fcm:13.3.5"`
`implementation "com.urbanairship.android:urbanairship-message-center:13.3.5"`
`implementation "com.urbanairship.android:urbanairship-automation:13.3.5"`

### What are the versions of any relevant development tools you are using?
Android Studio 4.0.1, Gradle 6.6.1

# Report

### What unexpected behavior are you seeing?
When you click on a Airship class Android Studio only shows the decompiled class file

### What is the expected behavior?
From what I can see the code is open source here at GitHub. I would expect the **sourcesJar** [to be available from mavenCentral](https://repo1.maven.org/maven2/com/urbanairship/android/urbanairship-fcm/13.3.5/) so that we can browse the libraries source code inside the IDE.

### What are the steps to reproduce the unexpected behavior?
Open an imported Airship class inside an Android Studio project.

### Do you have logging for the issue?
N/A

**Comment by rlepinski** [comment]
Thanks for the request we will take a look.

**Comment by rlepinski** [comment]
Will be part of the next release. Thanks for the suggestion! It also makes it possible to view javadocs directly in android studio:

<img width="990" alt="Screen Shot 2020-09-01 at 4 22 44 PM" src="https://user-images.githubusercontent.com/3967591/91915618-e8d4b300-ec6f-11ea-8890-be909cc99e5d.png">

**Comment by rlepinski** [comment]
SDK 14.0 should have a sources.jar - https://repo1.maven.org/maven2/com/urbanairship/android/urbanairship-core/14.0.0/

Thanks again
