### ISSUE TITLE
Maximum limit of concurrent alarms 500 reached - NougatScheduler.schedule

### ISSUE THREAD

**Issue by bbarrue** [urbanairship/android-library#163]
### What Airship dependencies are you using?
fcm & automation (Both 14.0.0)

# Report

### What unexpected behavior are you seeing?
A spike in crashes when our App is backgrounded on Samsung devices running Android 10

### What are the steps to reproduce the unexpected behavior?
Samsung Galaxy Tablets running Android 10 have very recently been crashing when backgrounded after updating from ariship 10 to 14.

### Do you have logging for the issue?
[Related Gist](https://gist.github.com/bbarrue/f38c93e3abd80bac45d5dcaa23c17818)

**Comment by rlepinski** [comment]
Fixed in 14.0.1, please update.
