### ISSUE TITLE
App Open Trigger for In App Automation disappears when Splash Screen finishes

### ISSUE THREAD

**Issue by bbarrue** [urbanairship/android-library#168]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?
'com.urbanairship.android:urbanairship-fcm:14.0.1'
'com.urbanairship.android:urbanairship-automation:14.0.1'

# Report

### What unexpected behavior are you seeing?
App Open In App Automation message flickers when App goes through SplashScreen Animation

### What is the expected behavior?
The Modal from In App Automation stays in place as the app loads behind it.

### What are the steps to reproduce the unexpected behavior?
Create an In App Automation modal popup.  
Set the trigger to App Open behavior.  
Open the App.

Notice that the Modal appears and then disappears when the app finishes loading behind it.

**Comment by rlepinski** [comment]
@bbarrue do you have a splash screen activity that loads first?

**Comment by bbarrue** [comment]
> @bbarrue do you have a splash screen activity that loads first?

Yes I do and it throws away the modal.  Wondering if this is the correct use case?

**Comment by rlepinski** [comment]
@bbarrue You just need to [exclude the activity](https://docs.airship.com/platform/android/in-app-automation/#excluding-activities) from showing IAA, you can do that by adding some metadata to the manifest for that activity:

```
        <activity android:name="your.splash.screen.activity">

            <meta-data
                android:name="com.urbanairship.push.iam.EXCLUDE_FROM_AUTO_SHOW"
                android:value="true" />
                
                ....
        </activity>
```

Also please update to [SDK 14.1.1](https://github.com/urbanairship/android-library-dev/blob/main/CHANGELOG.md#version-1411-december-30-2020). We fixed an issue around excluding activities from auto showing where the IAA would not display again until some other condition triggered it, like another foreground.

**Comment by bbarrue** [comment]
@rlepinski Hey thank you so much sir solved my problem.  Will update!
