### ISSUE TITLE
Proguard file configuration

### ISSUE THREAD

**Issue by tugcekeser** [urbanairship/android-library#17]
Hi,
I have implemented Urban Airship in my code. It works well. Now I am planning to put my application in Google store and I need to configure proguard file. I added following code block, but when I click on Generate Signed APK, it is still not working and getting following warnings. Could you help me?

-keep public class * extends com.urbanairship.Autopilot
-keep public class * extends com.urbanairship.actions.Action
-keep public class * implements com.urbanairship.actions.ActionRegistry$Predicate
-dontwarn com.amazon.device.messaging.**

<img width="1163" alt="screen shot 2017-07-21 at 5 41 31 pm" src="https://user-images.githubusercontent.com/17666583/28486857-eb1b7c94-6e3b-11e7-9d1b-44b1e735ac66.png">

**Comment by rlepinski** [comment]
Assuming you are using Gradle, the lib adds the proguard automatically. The errors you are seeing are added calls for Android O support. Make sure the compile sdk version is 26. Updating the compile sdk version is safe, just be sure to not update the target sdk version without extensive testing.

**Comment by tugcekeser** [comment]
Updating compile sdk version worked for me. Thank you!
