### ISSUE TITLE
Fatal Exception: java.lang.SecurityException getIccSerialNumber

### ISSUE THREAD

**Issue by halysongoncalves** [urbanairship/android-library#170]
Hello,

We have identified crash in `Fatal Exception: java.lang.SecurityException getIccSerialNumber
![Captura de Tela 2021-02-04 às 10 49 41](https://user-images.githubusercontent.com/5872045/106901609-bde70300-66d6-11eb-8e44-abe0ae101ec9.png)
` that has affected our users

`
Fatal Exception: java.lang.SecurityException
getIccSerialNumber
android.os.Parcel.createException (Parcel.java:1949)
android.telephony.TelephonyManager.getNetworkOperatorName (TelephonyManager.java:1762)
com.urbanairship.channel.AirshipChannel.getNextChannelRegistrationPayload (AirshipChannel.java:506)
com.urbanairship.channel.AirshipChannel.onCreateChannel (AirshipChannel.java:660)
com.urbanairship.channel.AirshipChannel.onUpdateChannel (AirshipChannel.java:715)
com.urbanairship.channel.AirshipChannel.onPerformJob (AirshipChannel.java:223)
com.urbanairship.job.Job$1.run (Job.java:90)
com.urbanairship.util.SerialExecutor$1.run (SerialExecutor.java:41)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
com.urbanairship.util.AirshipThreadFactory$1.run (AirshipThreadFactory.java:50)
java.lang.Thread.run (Thread.java:764)
`

**Version: 14.1.1**

![Captura de Tela 2021-02-04 às 10 49 45](https://user-images.githubusercontent.com/5872045/106901600-bb84a900-66d6-11eb-8120-2b92f56f0f0a.png)

**Comment by halysongoncalves** [comment]
What is the reason for the closure?

**Comment by halysongoncalves** [comment]
@rlepinski

**Comment by rlepinski** [comment]
The release just auto closed it. Fixed in 14.1.2, it was a quick, low risk fix so I was able to add it for the release today

**Comment by rlepinski** [comment]
https://github.com/urbanairship/android-library/releases/tag/14.1.2
