### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException - executeTakeOff 

### ISSUE THREAD

**Issue by bossdga** [urbanairship/android-library#177]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

"com.urbanairship.android:urbanairship-fcm:14.1.1"
"com.urbanairship.android:urbanairship-automation:14.1.1"
"com.urbanairship.android:urbanairship-message-center:14.1.1"

### What are the versions of any relevant development tools you are using?

# Report

### What unexpected behavior are you seeing?

I have 1 user with around 500 crashes in the span of 2 hours

### What are the steps to reproduce the unexpected behavior?

I cannot reproduce it, as it is coming from Crashlytics

### Do you have logging for the issue?

Fatal Exception: java.lang.NullPointerException
Attempt to read from field 'java.util.ArrayList android.content.pm.PackageParser$Component.intents' on a null object reference
android.os.Parcel.createException (Parcel.java:2094)
android.os.Parcel.readException (Parcel.java:2056)
android.os.Parcel.readException (Parcel.java:2004)
android.app.IActivityManager$Stub$Proxy.broadcastIntent (IActivityManager.java:5563)
android.app.ContextImpl.sendBroadcast (ContextImpl.java:1092)
android.content.ContextWrapper.sendBroadcast (ContextWrapper.java:454)
com.urbanairship.UAirship.executeTakeOff (UAirship.java:456)
com.urbanairship.UAirship.access$000 (UAirship.java:65)
com.urbanairship.UAirship$2.run (UAirship.java:381)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
com.urbanairship.util.AirshipThreadFactory$1.run (AirshipThreadFactory.java:50)
java.lang.Thread.run (Thread.java:919)

---------------------------------------

Caused by android.os.RemoteException
Remote stack trace: at com.android.server.pm.ComponentResolver$ActivityIntentResolver.queryIntentForPackage(ComponentResolver.java:1120) at com.android.server.pm.ComponentResolver.queryReceivers(ComponentResolver.java:344) at com.android.server.pm.PackageManagerService.queryIntentReceiversInternal(PackageManagerService.java:9827) at com.android.server.pm.PackageManagerService.queryIntentReceivers(PackageManagerService.java:9744) at com.android.server.am.ActivityManagerService.collectReceiverComponents(ActivityManagerService.java:16881)

**Comment by rlepinski** [comment]
Is it still only 1 user? Do you have any way to reproduce it? It looks like a corrupt install issue. The Airship SDK starts earlier than most other components, so when the device is faulty its usually the first to crash.

**Comment by bossdga** [comment]
Hi @rlepinski , thanks for answering. Unfortunately I cannot replicate the issue at all and yes, it is just one user so it might be a device issue indeed. I think I can close the issue, it seems there is nothing else I can do.
