### ISSUE TITLE
14.4.0 not all packages deployed

### ISSUE THREAD

**Issue by G00fY2** [urbanairship/android-library#178]
# Report

Version 14.4.0 is available for `urbanairship-automation` and `urbanairship-message-center` on [MavenCentral](https://search.maven.org/search?q=g:com.urbanairship.android), but some packages like `urbanairship-fcm` are missing.

Is this intended? Sorry if I'm impatient.

Thanks

**Comment by jyaganeh** [comment]
Hi @G00fY2, we ran into a bit of turbulence with the Maven Central gateway during this release and are working on getting the remaining modules synced. The remaining packages should be available via Maven Central later today, barring any further hiccups. In the meantime, all modules for 14.4.0 are currently available via JCenter.

**Comment by jyaganeh** [comment]
All of the 14.4.0 packages have now made it to [Maven Central](https://search.maven.org/search?q=g:com.urbanairship.android), so I'm going to go ahead and close this. Apologies for the delay!
