### ISSUE TITLE
issue Background color of button in in-app message when using Theme.MaterialComponents.DayNight

### ISSUE THREAD

**Issue by WalidMaata** [urbanairship/android-library#179]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?
com.urbanairship.android:urbanairship-automation:14.4.0

### What are the versions of any relevant development tools you are using?
 ℹ AS 4.1.3 .

# Report

### What unexpected behavior are you seeing?
 the background color of button in in-app message is different to custom color defined when i create the push in-app from airship board , in my case i use Theme.MaterialComponents as theme of my app so the background color of button in in-app message is identical to colorPrimary. i notice this issue appear from library version 13.1.1 

### What is the expected behavior?
 the background color of button in in-app message should the same as defined when i create push in-app  from airship board . 

### What are the steps to reproduce the unexpected behavior?
  1. use Theme.MaterialComponents.DayNight as theme of app
  2. create push in-app with custom design of button ( text, background color)
  3. so we receive the push in-app message with background color of button different to color defined when we create push in-app 

### Do you have logging for the issue?
 in my case the background color of button in in-app message should be yellow but it's white(see screenshot) when i receive the push in-app
<img width="547" alt="Capture d’écran 2021-04-29 à 22 28 59" src="https://user-images.githubusercontent.com/25607676/116614716-9486ed80-a93a-11eb-83c0-e69bba35ff3f.png">

**Comment by jyaganeh** [comment]
Hi @WalidMaata, 
I'm seeing similar behavior after following your repro steps and am looking into the issue. I'll update when I've gotten to the bottom of this and know more about fix timing or possible workarounds. Thanks for the clear repro and screenshot! 👍

**Comment by jyaganeh** [comment]
@WalidMaata we've released version `14.4.2` which includes the fix for this issue. I'm going to go ahead and close this, but if you still see any issues with these buttons after updating the SDK, feel free to leave a comment and I'll re-open.
