### ISSUE TITLE
The UAirship.shared() method should also be marked as @Nullable

### ISSUE THREAD

**Issue by breakwhile** [urbanairship/android-library#182]
![image](https://user-images.githubusercontent.com/15830036/120602359-879b7380-c47d-11eb-9224-bf1a105aaeb1.png)
![image](https://user-images.githubusercontent.com/15830036/120602484-a39f1500-c47d-11eb-922e-78fde29ca6ab.png)
In the shared() method in UAirship, it is marked by @NonNull. But the waitForTakeOff(long millis) method returned by the shared() method is marked by @Nullable. These two flags conflict.
I think the UAirship.shared() method should also be marked as @Nullable

**Comment by rlepinski** [comment]
`shared()` will never be null, if you take a look at the code it will wait forever if you pass in `0` until it's ready. However just following the annotations makes it seem like it can be null. We will add an extra null check that throws if null to appease the compiler.

Are you having issues with it?
