### ISSUE TITLE
Fatal Exception: android.database.CursorWindowAllocationException

### ISSUE THREAD

**Issue by gokhan47** [urbanairship/android-library#183]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?
    // Airship - FCM
    implementation 'com.urbanairship.android:urbanairship-fcm:13.0.0'
    implementation 'com.urbanairship.android:urbanairship-message-center:13.0.0'  // Message Center
    implementation 'com.urbanairship.android:urbanairship-automation:13.0.0'     //InApp Message

### What are the versions of any relevant development tools you are using?
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29

# Report

### What unexpected behavior are you seeing?
fatal exception in background

### Do you have logging for the issue?

Fatal Exception: android.database.CursorWindowAllocationException
Could not allocate CursorWindow '/data/user/0/com.testapp/no_backup/com.urbanairship.databases/D7Ke_3OyQuu-HMsrTKCnsg_in-app' of size 2097152 due to error -13.
android.database.CursorWindow.nativeCreate (CursorWindow.java)
android.database.AbstractCursor.moveToFirst (AbstractCursor.java:271)
com.urbanairship.automation.AutomationDataManager.generateSchedules (AutomationDataManager.java:721)
com.urbanairship.automation.AutomationDataManager.fetchSchedules (AutomationDataManager.java:703)
com.urbanairship.automation.AutomationDataManager.getScheduleEntries (AutomationDataManager.java:597)
com.urbanairship.automation.AutomationEngine$22.run (AutomationEngine.java:1057)
android.os.Handler.handleCallback (Handler.java:883)
android.os.HandlerThread.run (HandlerThread.java:67)
com.urbanairship.util.AirshipHandlerThread.run (AirshipHandlerThread.java:29)

**Comment by rlepinski** [comment]
We moved to room in version 14 so this should be fixed if you update. 13.0 is very old at this point.

**Comment by gokhan47** [comment]
I don't think it's because of the library version since we do have previous
version of our official app using version 13 of Airship and hasn't seen
same crash

**Comment by rlepinski** [comment]
We changed a lot of our data access patterns with a move to room. It should be addressed in 14.x.
