### ISSUE TITLE
Fatal Exception: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by WalidMaata** [urbanairship/android-library#184]
### What Airship dependencies are you using?
  "com.urbanairship.android:urbanairship-fcm:14.5.0",
  "com.urbanairship.android:urbanairship-automation:14.5.0"

# Report

### What unexpected behavior are you seeing?
App crash : we got this crash just for single user with : 
Android  : 8.1.0
Device : Galaxy Tab A (2016)

### What are the steps to reproduce the unexpected behavior?
we can't reproduice the crash but we get the log from crashlytics

### Do you have logging for the issue?
Fatal Exception: java.lang.NoSuchMethodError: No static method (Landroid/content/Context;)Landroidx/core/app/NotificationManagerCompat; in class Landroidx/core/app/NotificationManagerCompat; or its super classes (declaration of 'androidx.core.app.NotificationManagerCompat' appears in base.apk)
       at com.urbanairship.push.PushManager.<init>(PushManager.java:269)
       at com.urbanairship.push.PushManager.<init>(PushManager.java:249)
       at com.urbanairship.UAirship.init(UAirship.java:742)
       at com.urbanairship.UAirship.executeTakeOff(UAirship.java:421)
       at com.urbanairship.UAirship.access$000(UAirship.java:64)
       at com.urbanairship.UAirship$2.run(UAirship.java:380)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at com.urbanairship.util.AirshipThreadFactory$1.run(AirshipThreadFactory.java:50)
       at java.lang.Thread.run(Thread.java:764)

**Comment by jyaganeh** [comment]
Has this happened to the single user just once or multiple times? There may be an issue with that specific device or APK install if this isn't happening to any of your other users.

A few more questions for you:
* Does Crashlytics say whether this is happening in the foreground or background?
* Is your app including any play services or firebase dependencies? If so, could you please provide a list with the versions used in this build?
* Do you have multidex enabled?

**Comment by WalidMaata** [comment]
@jyaganeh thanks for your quick response 

1. this happened multiple times for the single user with Galaxy Tab A (2016) ( yep i guess it's specific to specific device or maybe APK install )
2. 100% in background
3. yes we use others firebase dependencies 
            analytics         : "com.google.firebase:firebase-analytics-ktx:18.0.2",
            fcm                  : "com.google.firebase:firebase-messaging:20.2.0",
            firebaseCore   : "com.google.firebase:firebase-core:16.0.8",
            remoteConfigKtx: "com.google.firebase:firebase-config-ktx:19.1.0",
            location       : "com.google.android.gms:play-services-location:16.0.0", 
            crashlytics    : "com.google.firebase:firebase-crashlytics:17.4.0"

4. no multidex not enabled

**Comment by jyaganeh** [comment]
@WalidMaata I tried to reproduce this by adding those dependencies to the sample app and didn't run into any issues in the emulator or on a Galaxy S21 5G. This doesn't seem like this is a problem with the SDK or your app's implementation, since I'd expect this issue to be more widespread if that were the case.

Unfortunately, I don't think there are currently any actionable steps that we can take from the SDK side to resolve this issue, but I'll keep an eye out for similar issues in the on the Google Play SDK Console.
