### ISSUE TITLE
Unable to get system notification permission when user disables notifications

### ISSUE THREAD

**Issue by ds8k** [urbanairship/android-library#189]
# Preliminary Info

### What Airship dependencies are you using?
Urban Airship React Native 11.0.1

# Report

### What unexpected behavior are you seeing?
If a user disables notifications (opts out within Airship dashboard) then there is not way to tell if system permissions are still on or not.

### What is the expected behavior?
The ability to get system level notification permission without requiring user-level notifications enabled

## Relevant code
https://github.com/urbanairship/android-library/blob/27a61106dc543af8a2f453246179958d99feebf5/urbanairship-core/src/main/java/com/urbanairship/push/PushManager.java#L696-L703

**Comment by rlepinski** [comment]
Resolved in the react-native plugin
