### ISSUE TITLE
Does the new Contact needs the ContactPermission to work?

### ISSUE THREAD

**Issue by StefMa** [urbanairship/android-library#192]
In the new [Airship v15](https://github.com/urbanairship/android-library/releases/tag/15.0.0) you mention the deprecation of the NamedUser in favor of the Contact API.
There is even a handy migration guide.
https://github.com/urbanairship/android-library/blob/43dde8152e07aa7c2998f4a60b59311f1d5c6aa0/documentation/migration/migration-guide-14-15.md#named-user-replaced-with-contact

But when I look into the code, it seems that the Contacts needs the "ContactPermisson" to work. 
Is that correct?
Therefore, the migration guide needs in addition a call like this:
```kotlin
UAirship.shared().privacyManager.enable(PrivacyManager.FEATURE_CONTACTS)
```
Am I correct with that?

**Comment by jyaganeh** [comment]
Hi @StefMa, you are correct. That should've been called out in the migration guide and we'll get it updated shortly. Sorry for any confusion this caused!

**Comment by StefMa** [comment]
This was fixed "in the latest relase".
https://github.com/urbanairship/android-library/releases/tag/15.1.0

See also: https://github.com/urbanairship/android-library/commit/25bfcd69e15072f05575e4b8642c3c8711fb2b96
