### ISSUE TITLE
Veracode Volnerability Issue in MediaView.java

### ISSUE THREAD

**Issue by rkaartikeyan** [urbanairship/android-library#207]
# Preliminary Info

### What Airship dependencies are you using?
Android: `airshipVersion = "16.4.0"`

### What are the versions of any relevant development tools you are using?
React Native Framework

# Report

##### Line no: 229
![image](https://user-images.githubusercontent.com/3778591/172129824-e8bd597e-bc0c-4ad1-a819-4d4af3729dde.png)

```
Description: The WebView wv has disabled safe browsing which puts the user at risk of browsing malicious or otherwise undesirable websites. The default is for safe browsing to be enabled.

Remediation: Do not disable safe browsing.
```
### What is the expected behavior?
The above veracode issue should not appear during veracode scan.

### What are the steps to reproduce the unexpected behavior?
1. Build APK
2. Scan with Veracode

### Do you have logging for the issue?
N/A

**Comment by rlepinski** [comment]
Safe browsing defaults to the app settings. Are you override that in your manifest? 

This issue is mitigated by a url allow list on the web view. We can take a look at forcing safe mode on our webviews in a future release, but it does not seem high priority at the moment.
