### ISSUE TITLE
Support bill of materials

### ISSUE THREAD

**Issue by StefMa** [urbanairship/android-library#208]
Since you have spearated a lot of stuff into different modules and publish them separately, I guess it would make sense to provide a bill of materials.

**Comment by rlepinski** [comment]
We keep it simple by versioning all of our modules the same, but will see if there are any other benefits of a BoM

**Comment by rlepinski** [comment]
We do not see any benefit of a BoM since we version everything the same. If we decide to change our release versioning in the future we will add it.
