### ISSUE TITLE
On changing to a new UA app push notifications are received twice

### ISSUE THREAD

**Issue by guntherhoppe** [urbanairship/android-library#21]
We had to change our UA production app. After update an already installed Android app, push notifications received twice, because the Android app still listens to the old UA app. The problem is that we have to continue push notifications also to the old UA app until the adoption of the Android app update is big enough. 
Is is possible to unregister our Android app from the old UA app programmatically on app start? 

We use a standard integration of Urban Airship with Autopilot + AirshipReceiver implementations and airshipconfig.properties for development+production keys/secrets. 

Thanks for help.

**Comment by rlepinski** [comment]
@guntherhoppe I think the main problem is that the apps are sharing the same sender ID, so the SDK will receive notifications from both places under the same sender so we do not know the differences. Our support team might be able to migrate your audience from the old app to the new app so you can avoid messaging both apps.  To do that, please contact support.

If for whatever reason that is not a feasible option, you might try deleting the instance ID and force the new app to generate new one:
```
// only once
InstanceID.getInstance(context).deleteInstanceID();
```

As long as you call that in the Autopilot the SDK should generate a new instance ID right away. You probably only want to do that once for the new app. I have never actually tried deleting the instance ID before in an app, so please test it before deploying.

**Comment by rlepinski** [comment]
Updated the sample to only delete the token instead of the instance ID.

**Comment by guntherhoppe** [comment]
@rlepinski: I'll try and let you know. Thanks!

**Comment by guntherhoppe** [comment]
@rlepinski: It works in my tests but seems to be a dirty hack. Because I have to do so inside an own thread (cannot run in main thread) it may run after airship registration, also when I added it to the Autopilot implementation (before UA is registered). 
Any suggestions to this?

Implementation:
```
    public static void deleteGmsRegistrationOnce(Context context) {
        SharedPreferences sharedPreferences = context.getSharedPreferences(SHARED_PREFS, Context.MODE_PRIVATE);
        if(!sharedPreferences.getBoolean(GMS_REGISTRATION_DELETED_ONCE, false)) {
            InstanceID instanceId = InstanceID.getInstance(context);
            new Thread(() -> {
                try {
                    instanceId.deleteToken("SENDER_ID", GoogleCloudMessaging.INSTANCE_ID_SCOPE);
                    sharedPreferences.edit().putBoolean(GMS_REGISTRATION_DELETED_ONCE, true).commit();
                } catch(Exception e) {
                    Log.e(TAG, "delete token", e);
                }
            }).start();
        }
    }
```

**Comment by rlepinski** [comment]
@guntherhoppe The `onAirshipReady(UAirship airship)` in Autopilot is actually called on a background thread. 

Try:
```
@Override
    public void onAirshipReady(UAirship airship) {

        Context context = UAirship.getApplicationContext();
        SharedPreferences sharedPreferences = context.getSharedPreferences(SHARED_PREFS, Context.MODE_PRIVATE);
        if(!sharedPreferences.getBoolean(GMS_REGISTRATION_DELETED_ONCE, false)) {
            try {
                InstanceID.getInstance(context).deleteToken(airship.getAirshipConfigOptions().gcmSender, GoogleCloudMessaging.INSTANCE_ID_SCOPE);
                sharedPreferences.edit().putBoolean(GMS_REGISTRATION_DELETED_ONCE, true).apply();
            } catch (IOException e) {
                Log.e(TAG, "Failed to delete token", e);
            }
        }
```

**Comment by rlepinski** [comment]
Closing this issue for now. If you still have issues please reopen.
