### ISSUE TITLE
We instantiate the listener but it seems that it is not being listened

### ISSUE THREAD

**Issue by silviamirandastorm** [urbanairship/android-library#213]
Hi guys,
We have a problem in android implementation (**lib version 16.6.1**)
We instantiate the listener but it seems that it is not being listened 

example of adding listener ->> MessageCenter.shared().inbox.addListener(inboxListener)  

Part of previous code for context

  private val inboxListener = InboxListener {
         unreadMessages {
          …….         }
     }
...

fun unreadMessages(callback: (unread: Int) -> Unit) {
    CoroutineScope(Dispatchers.Main).launch {
        val unreadCount = MessageCenter.shared().inbox.unreadCount
        callback.invoke(unreadCount)
    }
}

…  

I can only fetch the unread messages by calling directly —>>
 unreadMessages { countUnreadMessages->
             …..
         }
         
 **Something else must be done to addListener???**

**Comment by rlepinski** [comment]
Could you provide the full listener, its hard to tell what you are doing. The inbox listener only is called when the inbox message list is updated. It has no unreadMessage method.

**Comment by rlepinski** [comment]
Are you still having issue with this?

**Comment by tarekatevenly** [comment]
It doesn't work for me too. I tried with your own android repository and the listener in MainActivity doesn't work. I also tried in my own project and it didn't work. I am using "16.5.1"

**Comment by tarekatevenly** [comment]
` 
  Here is the code snippet I use

    override fun onResume() {
        super.onResume()
        viewModel.load()
        MessageCenter.shared().inbox.addListener(airshipListener)
    }

    override fun onStop() {
        MessageCenter.shared().inbox.removeListener(airshipListener)
        super.onStop()
    }

    private val airshipListener = InboxListener {
        setMessageCenterIndicator()
    }
 
`

**Comment by rlepinski** [comment]
You probably want to add that listener during airship onReady instead of ti being tied to your activity. That way you can deeplink into the right place even if its not setup right.
