### ISSUE TITLE
Problem overriding the empty message style

### ISSUE THREAD

**Issue by silviamirandastorm** [urbanairship/android-library#214]
Hi Guys.

I'm having a problem overriding the empty message style. (**Android lib version 16.6.1**)
The style I apply doesn't work.

**Dosn't center, dosn't apply color correctly**

<img width="336" alt="Captura de Tela 2022-09-02 às 17 07 19" src="https://user-images.githubusercontent.com/60703245/188228589-88cfec13-ec1d-4119-bc0d-10945b749e93.png">

 **am I doing it correctly?**
 
![Captura de Tela 2022-09-02 às 17 01 02](https://user-images.githubusercontent.com/60703245/188227734-994eee02-2d85-4111-a5f6-a7f69f8d9abe.png)
![Captura de Tela 2022-09-02 às 17 01 11](https://user-images.githubusercontent.com/60703245/188227749-a63d0ed8-1c6b-452e-8713-a0a7ce8b817c.png)

**Comment by Ulrico972** [comment]
Hello, I think you forgot to update the `messageCenterStyle` also with your style.
You can find an example here: https://docs.airship.com/platform/android/message-center/#styling-android-mc

If it still doesn't work, please send us your entire message center style and we'll take a look.

**Comment by silviamirandastorm** [comment]
Hi
the three items are the part that I customized and did not apply

  <style name="Theme.MessageCenterUrban.EmptyMessageTextAppearance" parent="MessageCenter.EmptyMessage.TextAppearance">
        <item name="android:textSize">16sp</item>
        <item name="android:color">@color/playkit_alto</item>
        <item name="android:textAlignment">center</item>
    </style>

**Comment by rlepinski** [comment]
![image](https://user-images.githubusercontent.com/3967591/188234176-3a98590a-8cea-412c-90e0-f5e06a112cc2.png)

```
    <!-- Base application theme. -->
    <style name="AppTheme" parent="BaseTheme">
        ...
        <item name="messageCenterStyle">@style/AppTheme.MessageCenter</item>
    </style>
    
    
    <style name="AppTheme.MessageCenter" parent="MessageCenter">
        <item name="messageCenterEmptyMessageText">some really long empty message string</item>
        <item name="messageCenterEmptyMessageTextAppearance">@style/AppTheme.MessageCenter.EmptyMessageTextAppearance</item>
    </style>


    <!-- Custom message title text style -->
    <style name="AppTheme.MessageCenter.EmptyMessageTextAppearance" parent="MessageCenter.EmptyMessage.TextAppearance">
        <item name="android:textSize">44sp</item>
        <item name="android:textColor">#ff00ff</item>
    </style>
```

A few things, for text color you need to use `textColor` not `color`. And unfortunately alignment is not a text appearance attribute. We do not expose that style so you will have to override the actual layout. 

Create a new layout titled `ua_fragment_message_list.xml` with:
```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">


    <androidx.swiperefreshlayout.widget.SwipeRefreshLayout
        android:id="@+id/swipe_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent">


        <ListView
            android:clipToPadding="false"
            android:scrollbarStyle="outsideOverlay"
            android:id="@android:id/list"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

    </androidx.swiperefreshlayout.widget.SwipeRefreshLayout>


    <TextView
        android:id="@android:id/empty"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textAlignment="center"
        android:gravity="center"
        android:layout_gravity="center" />

</FrameLayout>
```

**Comment by silviamirandastorm** [comment]
Ok, thanks ☺️ !

**Comment by rlepinski** [comment]
Let me know if you have any other issues!
