### ISSUE TITLE
Airship incompatible with latest SQLite

### ISSUE THREAD

**Issue by barry-irvine** [urbanairship/android-library#220]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

Airship 16.8.0
FCM, In-app, Message Center

### What are the versions of any relevant development tools you are using?

Android Studio Dolphin Patch 1

# Report

### What unexpected behavior are you seeing?

App fails to build if we upgrade to Room 2.5.0

### What is the expected behavior?

App builds successfully

### What are the steps to reproduce the unexpected behavior?

Just add airship and latest Room dependency to gradle. We suspect it's because of the transitive dependency to SQLite 2.3.0 (released yesterday)
 
### Do you have logging for the issue?

No field mDelegate of type Landroid/database/sqlite/SQLiteStatement; in class Landroidx/sqlite/db/framework/FrameworkSQLiteStatement; or its superclasses (declaration of 'androidx.sqlite.db.framework.FrameworkSQLiteStatement' appears in /data/app/com.gocitypass.debug-z-Xgbcx0q3wMnA3ldbqqRQ==/base.apk!classes8.dex)

**Comment by barry-irvine** [comment]
@rlepinski Any news on this? This is starting to have a knock-on effect because WorkManager 2.8 also relies on Room 2.5...

**Comment by rlepinski** [comment]
@barry-irvine We are working on a release and we will update to latest room and workmanager, hopefully that will resolve this. Hopefully be out either Friday or Monday.

**Comment by rlepinski** [comment]
@barry-irvine Our QA team found a few issues with the 16.9 release that has this update, its looking like a Monday/Tuesday release. Ill keep you updated though.

**Comment by barry-irvine** [comment]
Works with latest. Thanks
