### ISSUE TITLE
v18.0.0 `InAppMessageListener` missing from API

### ISSUE THREAD

**Issue by wezley98** [urbanairship/android-library#239]
Hey, Just looking at the v18.0.0 migration guide but couldn't see anything relating to `InAppMessageListener` no longer been available. 

<img width="487" alt="Screenshot 2024-06-17 at 16 23 08" src="https://github.com/urbanairship/android-library/assets/1488209/0263ad0d-6378-48b8-8e15-85e6764b100f">

Could you please provide instructions on how to migrate these imports in v18.0.0?

**Comment by jyaganeh** [comment]
Hi @wezley98, would you be able to share a snippet (or description) of how you're using those APIs in SDK 17? 
If you'd rather not post it publicly, my email is: josh.yaganeh @ airship.com

**Comment by jyaganeh** [comment]
Thanks @wezley98!

The `DisplayContent` class was restructured into a new sealed class: `InAppMessageDisplayContent`. Here's how to migrate the helpers at the bottom of your listener (the `getMessageContent` helper should no longer be needed):

```kotlin
private fun getInAppMessageText(message: InAppMessage): String {
    val messageText = when (val content = message.displayContent) {
        is InAppMessageDisplayContent.ModalContent -> content.modal.body?.text.orEmpty()
        is InAppMessageDisplayContent.BannerContent -> content.banner.body?.text.orEmpty()
        is InAppMessageDisplayContent.FullscreenContent -> content.fullscreen.body?.text.orEmpty()
        is InAppMessageDisplayContent.HTMLContent -> content.html.url
        else -> "" // Scenes & Surveys, and Custom display content
    }

    Log.d("AirshipListener InAppAutomation message getInAppMessageText message is : $messageText")

    return messageText
}

private fun getInAppMessageTitle(message: InAppMessage): String {
    val title = when (val content = message.displayContent) {
        is InAppMessageDisplayContent.ModalContent -> content.modal.heading?.text.orEmpty()
        is InAppMessageDisplayContent.BannerContent -> content.banner.heading?.text.orEmpty()
        is InAppMessageDisplayContent.FullscreenContent -> content.fullscreen.heading?.text.orEmpty()
        else -> "" // Scenes & Surveys, HTML, and Custom display content
    }

    Log.d("AirshipListener InAppAutomation message getInAppMessageTitle title is : $title")

    return title
}

private fun getInAppMessageButtons(message: InAppMessage): List<String> {
    val buttons: MutableList<String> = mutableListOf()
    val contentButtons = when (val content = message.displayContent) {
        is InAppMessageDisplayContent.ModalContent -> content.modal.buttons
        is InAppMessageDisplayContent.BannerContent -> content.banner.buttons
        is InAppMessageDisplayContent.FullscreenContent -> content.fullscreen.buttons
        else -> null // Scenes & Surveys, HTML, and Custom display content
    }
    contentButtons?.forEach { buttonInfo ->
        buttons.add(buttonInfo.label.text)
    }
    return buttons
}
```

The replacement for `InAppMessageListener` is `InAppMessageDisplayDelegate`, which has the following methods:
* `fun isMessageReadyToDisplay(): Boolean` Called to check if the message is ready to be displayed. Return `true` to use the SDK's default logic for determining if messages are ready to display.
* `fun messageWillDisplay(message: InAppMessage, scheduleId: String)` - called when a message will be displayed
* `fun messageFinishedDisplaying(message: InAppMessage, scheduleId: String)` - called when a message finishes displaying

You can register the display delegate like this: 

```kotlin
InAppAutomation.shared().inAppMessaging.displayDelegate = AirshipListener(...)
```

In the new display delegate, the `messageFinishedDisplaying()` callback doesn't receive the resolution info, but it's still possible to listen to the events `Flow` on the analytics class to get info about InApp resolutions. Here's an example:

```kotlin
scope.launch {
    airship.analytics.events
        .filter { it.type == EventType.IN_APP_RESOLUTION }
        .collect { event ->
            val body = event.body.optMap()
            val messageId = body.opt("id").optMap().opt("message_id").string
            val resolution = body.opt("resolution").optMap()
                    
            Log.i("InApp Message ($messageId) resolution: $resolution")
        }
}
```

I'm not sure what the `onMessageFinished(...)` call on your `InAppNotificationMessage` class is doing with the resolution info that used to be provided on the `InAppMessageListener. onMessageFinished` callback, so let me know if using the analytics event feed doesn't fit your use case.

**Comment by DejanMedicSKY** [comment]
According to the posted code resolution is used to get the actions on the buttons and one which was selected. Which can be useful to know I guess.

```
        val buttonInfo = resolutionInfo.buttonInfo
        val buttonText = buttonInfo?.label?.text.orEmpty()
        val buttonActions: MutableMap<String, String> = mutableMapOf()
        buttonInfo?.actions?.forEach {
            buttonActions[it.key] = it.value.toString()
        }
```

Proposed `airship.analytics.events Flow` observing is a bit different and can happen at different pace and not be available at time when delegate call happens `fun messageFinishedDisplaying(message: InAppMessage, scheduleId: String)`.

**Comment by DejanMedicSKY** [comment]
Also app crashes when takeoff is called and we did not disable analytics with builder AirshipConfigOptions.
App crashes at AppForegroundEvent.getEventData. With it disabled it setup fine `AirshipConfigOptions.Builder().setAnalyticsEnabled(false)`.
```
 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.urbanairship.analytics.Analytics.getConversionSendId()' on a null object reference
	at com.urbanairship.analytics.AppForegroundEvent.getEventData(AppForegroundEvent.java:49)
	at com.urbanairship.analytics.Analytics.addEvent(Analytics.kt:318)
	at com.urbanairship.analytics.Analytics.onForeground(Analytics.kt:354)
	at com.urbanairship.analytics.Analytics.<init>(Analytics.kt:203)
	at com.urbanairship.analytics.Analytics.<init>(Analytics.kt:52)
	at com.urbanairship.analytics.Analytics.<init>(Analytics.kt:176)
	at com.urbanairship.UAirship.init(UAirship.java:732)
	at com.urbanairship.UAirship.executeTakeOff(UAirship.java:428)
	at com.urbanairship.UAirship.access$000(UAirship.java:72)
	at com.urbanairship.UAirship$2.run(UAirship.java:387)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at com.urbanairship.util.AirshipThreadFactory$1.run(AirshipThreadFactory.java:50)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by rlepinski** [comment]
thanks for the report, looking into it

**Comment by rlepinski** [comment]
@DejanMedicSKY @wezley98 Are you working on the same implementation? Any chance we can sync on a call to figure out how we can provide the right info for you?

**Comment by rlepinski** [comment]
I am mostly curious how you are using this data? Yes the flow changes when you get it but if you are just generating reporting from the data then its probably fine and you can replace the listener with the flow. If you can provide more details on these methods then we can hopefully unblock you:

```
 inAppNotification.onMessageDisplayed(
            scheduleId = scheduleId,
            title = contentTitle,
            message = contentMessage,
            buttons = buttons
        )

inAppNotification.onMessageFinished(
            scheduleId = scheduleId,
            title = contentTitle,
            message = contentMessage,
            buttons = buttons,
            selected = buttonText,
            actions = buttonActions
        )
```

**Comment by jyaganeh** [comment]
@wezley98 @DejanMedicSKY, thanks for the email! would one or both of you be able to join a short call to discuss this further? We'd like to make sure that we fully understand your needs, so that we can either make the necessary changes in an upcoming SDK release, or help with an alternate solution that satisfies your use case.

**Comment by jyaganeh** [comment]
I didn't hear back from you re: availability, so I'm going to close this out for now. If you'd still like to schedule a call or have any other questions or concerns, feel free to email me or re-open this issue.
