### ISSUE TITLE
when are you planing to update play-services version?

### ISSUE THREAD

**Issue by Baniares** [urbanairship/android-library#24]
We want to include  `play-services-location:11.2.0` on our app but you are using `11.0.1`

> +--- com.urbanairship.android:urbanairship-sdk:8.8.2
> |    +--- com.android.support:support-v4:25.3.1 -> 26.0.2 (*)
> |    +--- com.android.support:support-annotations:25.3.1 -> 26.0.2
> |    \--- com.google.android.gms:play-services-gcm:11.0.1
> |         +--- com.google.android.gms:play-services-base:[11.0.1] -> 11.2.0 (*)
> |         +--- com.google.android.gms:play-services-basement:[11.0.1] -> 11.2.0 (*)
> |         \--- com.google.android.gms:play-services-iid:[11.0.1] -> 11.0.1
> |              +--- com.google.android.gms:play-services-base:[11.0.1] -> 11.2.0 (*)
> |              \--- com.google.android.gms:play-services-basement:[11.0.1] -> 11.2.0 (*)

**Comment by rlepinski** [comment]
@Baniares You can force our SDK to use a newer version of google play services by also defining the 11.2.0 version of play-services-gcm. An update to our SDK is not required.
