### ISSUE TITLE
Message center fragment 

### ISSUE THREAD

**Issue by Pulkitt3** [urbanairship/android-library#243]
We are working with Airship message center implementation in Android and iOS. But we are wondering is there message center screen is different from iOS. Please find a screenshot of iOS and Android attached below. 
**I am using version 17.8.0**
Android Screenshot
![image](https://github.com/user-attachments/assets/a002e931-96e6-4dd0-8356-ad778fe3b5b6)
**We are using 17.1.2 on iOS**
IOS Screenshot
![image](https://github.com/user-attachments/assets/37a99b42-9896-413a-bec2-7d07a6f366b7)

**Comment by rlepinski** [comment]
We use OOTB components on both iOS and Android. On iOS, we recently rewrote it in swiftUI hence why you get a more modern look and easier methods to customize it. We are working on a rewrite to the Android version to use compose/material 3. I dont have any timeline when that is going to be ready.

For now, if the UI does not meet your requirements I would recommend building your own listing. The listing UI is just a list view, it should be fairly straightforward to create one using a recycler view or compose.

**Comment by Pulkitt3** [comment]
Okay thanks, that means right now it's inconsistent with each other from a UI perspective. they look different.

**Comment by rlepinski** [comment]
They will always look different since they run on different platforms.

**Comment by Pulkitt3** [comment]
Great thanks. So, I need to create a custom design so it looks like iOS.

**Comment by rlepinski** [comment]
Yes, if thats the goal of your app.
