### ISSUE TITLE
Disable the notification from showing

### ISSUE THREAD

**Issue by LLin233** [urbanairship/android-library#31]
The DefaultNotificationFactory now is final, is there another way that I could return ```null``` from ```createNotification()``` without extending the ```NotificationFactory```, some methods are dressed as the default method, and it's kinda a messy way to implement it.

**Comment by rlepinski** [comment]
Most of the logic from DefaultNotificationFactory has been moved into the parent
class NotificationFactory. Here is the [source](https://github.com/urbanairship/android-library/blob/master/urbanairship-sdk/src/main/java/com/urbanairship/push/notifications/DefaultNotificationFactory.java
).

Most of that default factory logic was moved into the parent class. The only real thing you are losing is setting the default style on a notification, but that is easily reproduced:
```
NotificationFactory factory = new NotificationFactory(getContext()) {
    @Nullable
    @Override
    public Notification createNotification(@NonNull PushMessage message, int notificationId) {
        if (UAStringUtil.isEmpty(message.getAlert())) {
            return null;
        }

        NotificationCompat.Style defaultStyle = new NotificationCompat.BigTextStyle().bigText(message.getAlert());
        return createNotificationBuilder(message, notificationId, defaultStyle).build();
    }
};
```
