### ISSUE TITLE
Message Center 

### ISSUE THREAD

**Issue by maheswaranecemohan** [urbanairship/android-library#32]
In message center it shows all the messages that all i created.

but

it is not opening the specific page while tap on the message.

**Comment by rlepinski** [comment]
Could you provide message center implementation details, SDK version, etc...? Thanks.

**Comment by rlepinski** [comment]
Please contact support if you are still having an issue.

**Comment by maheswaranecemohan** [comment]
I am facing the same issue. can you provide support on this

**Comment by maheswaranecemohan** [comment]
compile 'com.urbanairship.android:urbanairship-sdk:7.2.+'

**Comment by rlepinski** [comment]
@maheswaranecemohan We do not have enough information to help you. Please contact support and they will help gather all the information we need to resolve your issue. 

A few things you can try:
- Update to the latest SDK version 8.9.4.
- Reread the docs https://docs.urbanairship.com/platform/android/#android-rich-push-inbox-intents
