### ISSUE TITLE
Gradle 3.0.0 not supported

### ISSUE THREAD

**Issue by jkauppin** [urbanairship/android-library#34]
When try to compile with Gradle 3.0.0 get errors about flavors:

Error:Cannot choose between the following configurations of project 
  - debugApiElements
  - debugRuntimeElements
  - releaseApiElements
  - releaseRuntimeElements
All of them match the consumer attributes:
  - Configuration 'debugApiElements':
      - Found com.android.build.api.attributes.BuildTypeAttr 'debug' but wasn't required.
      - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
      - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
      - Found org.gradle.api.attributes.Usage 'java-api' but wasn't required.
  - Configuration 'debugRuntimeElements':
      - Found com.android.build.api.attributes.BuildTypeAttr 'debug' but wasn't required.
      - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
      - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
      - Found org.gradle.api.attributes.Usage 'java-runtime' but wasn't required.
  - Configuration 'releaseApiElements':
      - Found com.android.build.api.attributes.BuildTypeAttr 'release' but wasn't required.
      - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
      - Found com.android.build.gradle.internal.dependency.VariantAttr 'release' but wasn't required.
      - Found org.gradle.api.attributes.Usage 'java-api' but wasn't required.
  - Configuration 'releaseRuntimeElements':
      - Found com.android.build.api.attributes.BuildTypeAttr 'release' but wasn't required.
      - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
      - Found com.android.build.gradle.internal.dependency.VariantAttr 'release' but wasn't required.
      - Found org.gradle.api.attributes.Usage 'java-runtime' but wasn't required.

**Comment by rlepinski** [comment]
@jkauppin What SDK version are you using? How do you know its our SDK causing the issues? Could you provide a sample project?

**Comment by jkauppin** [comment]
The project that is causing it has just UA but yes, it could be a side effect of something else. The project is not open source so cannot provide it but will gather more info. Build tool is 26.0.2 targeting to SDK 26.

**Comment by jkauppin** [comment]
The UA was the latest 8.9.4.

**Comment by rlepinski** [comment]
I built the sample app in our repo with 3.0.0 and it seemed to work fine. I found this - https://stackoverflow.com/questions/45679847/android-studio-3-0-compile-issue-cannot-choose-between-configurations by googling your issue. Not sure if its from our SDK.

**Comment by jkauppin** [comment]
The issue is elsewhere so close the defect.
