### ISSUE TITLE
Support for support library 27

### ISSUE THREAD

**Issue by benjamin-alderfer-willowtree** [urbanairship/android-library#43]
Attempting to run version 8.9.4 with support library 27 results in a class not found crash in UAWebViewClient. `AsyncTaskCompat` seems to have been removed in support library 27.  Downgrading to support library 26 fixes the crash.

[The docs](https://developer.android.com/reference/android/support/v4/os/AsyncTaskCompat.html) recommend using AsyncTask directly.

**Comment by rlepinski** [comment]
Yep, we released 8.9.5 earlier today that should fix your problem.
