### ISSUE TITLE
Notification issue in Android Oreo

### ISSUE THREAD

**Issue by maheswaranecemohan** [urbanairship/android-library#46]
Device not getting the push notification in Oreo device 

Getting following error message 

"UALib: Posting notification Notification(channel=null pri=0 contentView=null vibrate=default sound=default defaults=0x3 flags=0x10 color=0xff229432 vis=PUBLIC) with ID 1009"

Kindly provide support on this.

**Comment by rlepinski** [comment]
What SDK version are you on? Make sure you are using 8.6 or newer.
