### ISSUE TITLE
Control login/logout in the SDK

### ISSUE THREAD

**Issue by BugsBunnyBR** [urbanairship/android-library#50]
Hi, I could not find a way to flag that a user signed in or out and stop receiving user targed pushes.

My use case is that, when the user executed login we associate the channelId with userId in our server. However if the user executes logout while offline or when the user refresh token becomes invalid ( so the user can't access our server to disassociate the channelId with the userId ).
What should be the right way to deal with this situation? Block the user to logout when offline seems a bad user experience and it still does not solve the problem.

As far as I can understand there should exist a way to set in the lib an id for the current logged user (and a way to clear this info ) and each push that arrives should check if the current logged user is the one in the payload of the push.

**Comment by rlepinski** [comment]
@BugsBunnyBR Are you using our named user feature? You can associate/disassociate a named user to a channel within the SDK, or by hitting this API - https://docs.urbanairship.com/api/ua/#api-named-users. You should avoid doing both, and it sounds like you will have a better experience hitting the API directly.

If you have further questions, please contact support.
