### ISSUE TITLE
Notifications are delayed in Android 8.+

### ISSUE THREAD

**Issue by konaire** [urbanairship/android-library#52]
Hello.

I experience delays with pushes for Android O. Notifications are delayed or even aren't shown at all. But there is no such problem for any other android version. I've enabled notification channels like:
```java
if (Build.VERSION.SDK_INT >= 26) {
    String channelId = "defaultChannel";
    NotificationManager notificationManager = (NotificationManager) context.getSystemService(Context.NOTIFICATION_SERVICE);
    NotificationChannel channel = new NotificationChannel(channelId, context.getString(R.string.notification_default_channel), NotificationManager.IMPORTANCE_HIGH);

    if (notificationManager != null) {
        notificationManager.createNotificationChannel(channel);
        setNotificationChannel(channelId);
    }
}
````

I tried to set different priorities, tried to add vibration etc. But nothing was worked.
Please can you point me what is wrong? Is there any way to fix this?

**Comment by rlepinski** [comment]
@konaire what SDK version are you on. Looks like you are customizing the factory, could you post the entire factory ?

**Comment by konaire** [comment]
I use 8.9.6. Yep, it's factory.
```java
private static class MyNotificationFactory extends DefaultNotificationFactory {
    public MyNotificationFactory(@NonNull Context context) {
        super(context);

        if (Build.VERSION.SDK_INT >= 26) {
            String channelId = "defaultChannel";
            NotificationManager notificationManager = (NotificationManager) context.getSystemService(Context.NOTIFICATION_SERVICE);
            NotificationChannel channel = new NotificationChannel(channelId, context.getString(R.string.notification_default_channel), NotificationManager.IMPORTANCE_DEFAULT);

            channel.setSound(null, null);
            if (notificationManager != null) {
                notificationManager.createNotificationChannel(channel);
                setNotificationChannel(channelId);
            }
        }

        setSmallIconId(R.drawable.ic_notification);
        setColor(ContextCompat.getColor(context, R.color.notification));
    }

    @Override
    public NotificationCompat.Builder extendBuilder(@NonNull NotificationCompat.Builder builder, @NonNull PushMessage message, int notificationId) {
        if (notificationAllowed(message)) {
            return soundBuilder(builder, message);
        } else {
            return null; // preventing notification
        }
    }


    private boolean notificationAllowed(@NonNull PushMessage message) {
        Bundle pushBundle = message.getPushBundle();
        String centerId = pushBundle.getString(CENTER_ID);
        String objectNumber = pushBundle.getString(OBJECT_NUMBER);
        String type = pushBundle.getString(NOTIFICATION_TYPE);

        // not allowed arm_error for currently visible area
        if (TYPE_ARM_ERROR.equals(type) || TYPE_DISARM_ERROR.equals(type)) {
            if (centerId != null && objectNumber != null && (centerId + objectNumber).equals(sCurrentCenterPlusObject)) {
                return false;
            }
        }

        return true; // allowed by default
    }

    private NotificationCompat.Builder soundBuilder(@NonNull NotificationCompat.Builder builder, @NonNull PushMessage message) {
        Bundle pushBundle = message.getPushBundle();
        String sound = pushBundle.getString(SOUND);

        if (TextUtils.isEmpty(sound)) {
            if (Build.VERSION.SDK_INT < 26) {
                builder.setSound(null);
            } else {
                RingtoneManager.getRingtone(getContext(), Settings.System.DEFAULT_NOTIFICATION_URI).play();
            }
        } else {
            Uri uri = Uri.parse("android.resource://" + getContext().getPackageName() + "/raw/" + sound);

            if (Build.VERSION.SDK_INT < 26) {
                builder.setSound(uri);
            } else {
                RingtoneManager.getRingtone(getContext(), uri).play();
            }
        }

        return builder;
    }
}
```

**Comment by konaire** [comment]
And there is method for initialization:
```java
public static void initialize(Application application, String prodAppKey, String prodAppSecret, String gcmSender) {
    AirshipConfigOptions options = new AirshipConfigOptions.Builder()
        .setInProduction(true)
        .setProductionAppKey(prodAppKey)
        .setProductionAppSecret(prodAppSecret)
        .setGcmSender(gcmSender).build();

    UAirship.takeOff(application, options);
    UAirship.shared().getPushManager().setUserNotificationsEnabled(true);
    UAirship.shared().getPushManager().setNotificationFactory(new MyNotificationFactory(application));
}
```

**Comment by rlepinski** [comment]
That looks fine to me.

- What test devices are you using that are having issues posting notifications?
- Could you provide verbose logging for a session that should receive a push?
- Does this only happen when the app is backgrounded?

**Comment by konaire** [comment]
I tried again on different emulator. Unfortunately problem is still there. In my project play services has already been version 11.8.0. And device has used the newest GPS also. I prepared more [logs](https://github.com/urbanairship/android-library/files/1665309/logs2.txt). And I think that it contained some information about receving a push (line 847). Also I added my custom log right in `extendBuilder` and it was called (line 848).

**Comment by rlepinski** [comment]
@konaire could you share the push that you sent? did it include an image or anything?

**Comment by rlepinski** [comment]
Also, is this something you can reproduce in our sample app? If I am unable to reproduce it I wont be much help. Verbose SDK logs, push payload, and any relevant push processing that you might be doing in addition to building the notification. If you need assistance gathering that info, or do not want to share it on github, please contact support.

**Comment by konaire** [comment]
Push was something like that:
{"notification-type":"PANIC_BUTTON_MYALARM_ERROR", "center_id":"91b9b632-bd41-40aa-b058-24aa36477242", "com.urbanairship.push.CANONICAL_PUSH_ID":"2892d5b4-490c-4fe1-a3de-e81b2b633398", "google.sent_time":1516908987023, "com.urbanairship.push.PUSH_ID":"08c7d260-0207-11e8-976f-0242b1b79ada", "from":"367832737549", "com.urbanairship.sound":"sys_attention", "com.urbanairship.push.ALERT":"Air 15.2, Alarm!", "google.message_id":"0:1516908987027856%1bd28073f9fd7ecd", "object_number":2008}

I don't do much with pushes. I pasted all code about pushes earlier. Also I found some strange pattern: first push comes in time after reinstalling the app, but the next one comes with delay.

**Comment by rlepinski** [comment]
Its just a simple text push? Using a similar emulator and setup, my push notifications come in just fine. Occasionally i have experienced delayed or missing notifications, and when that happens its usually caused by my local network. If I reconnect to the network after they stop posting, I usually get a flood of notifications.

The other thing that might be happening is the new background limitations are waiting for an optimal time to deliver the push to the app. You can send a high priority FCM notification, but thats only recommended for certain types of push.

When you are building the push notification, or handling broadcasts you have a limit of 10 seconds. If you are doing any extra processing that takes longer than that, you should instead schedule a job to run at a later time. Again, another Android O limitation.

Most of this is just speculation at this point. I don't have enough info to determine where the problem is.

**Comment by konaire** [comment]
Yes, It's just text push. I have no problem with network. Both emulator and device with Android M connect to the same network. But first gets notification later than second. Also I disabled battery optimization for my app, but it didn't do much. Now I disabled even my custom factory for pushes and no results.

So can it be something with server side? I mean may be something can cause this type of problem when push is generating? I'll try to set high priority but may be there something else?

**Comment by rlepinski** [comment]
Can you reproduce the issue in our sample app? I would still suggest trying a different network and device.

**Comment by konaire** [comment]
I couldn't reproduce it in sample app. But I've finally found a cause of problem. It is google services plugin. I use it for firebase analytics. If I remove it from my `build.gradle`, notifications come just in time.
```
// This line causes the problem
apply plugin: 'com.google.gms.google-services'
```

**Comment by konaire** [comment]
I checked it. This behavior was repeated in emulator.

**Comment by rlepinski** [comment]
Sounds like a Google Play Services issue. I might have a workaround. Could you try adding this to your manifest:
```
<receiver
            android:name="com.urbanairship.push.GcmPushReceiver"
            android:permission="com.google.android.c2dm.permission.SEND">

            <intent-filter android:priority="100">
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name="${applicationId}" />
            </intent-filter>
        </receiver>
```

It will bump the priority of the UA receiver.

**Comment by konaire** [comment]
Thank you very much! It works like a charm!

**Comment by rlepinski** [comment]
@konaire Awesome. We are going to release SDK 9.0.0 next week with the fix, but we are also changing the package to `com.urbanairship.push.gcm.GcmPushReceiver` (added a new sub package `gcm`). If you upgrade make sure to remove the entry.
