### ISSUE TITLE
Changing the associated named user id stops push notifs from being received

### ISSUE THREAD

**Issue by adina-abduraman** [urbanairship/android-library#57]
Hi guys,

I have an issue on an Android client app. After I call takeOff and configure nameUserId and userNotificationsEnabled, everything is ok, the push notifications work. Later on I need to configure another user id (logout for example and login immediately with another user but in the same app session, without restarting it) and push notifs stop working. What I do to disassociate the old user is to set userId to null, and then to a new value. And this way the push notifs stop working. Is there something that I am missing?

Thanks!

**Comment by crow** [comment]
This kind of implementation issue is best handled by contacting support@urbanairship.com or checking out our [community fourms](https://support.urbanairship.com/hc/en-us/community/topics). Support can help you do a deeper dive into your specific implementation to get things working correctly.
