### ISSUE TITLE
Closing the application on Android.

### ISSUE THREAD

**Issue by code0wl** [urbanairship/android-library#6]
Closing the application on Android makes it not receive any notifications anymore. Until the application is reopened all the notifications fire through. This is without force closing the app and happens when one booths the device as well. 

Is this a known issue?

**Comment by rlepinski** [comment]
This is not a known issue. It sounds like takeoff is not being called in the right place. Where are you calling takeoff? Make sure you are using autopilot or calling takeoff in the application class and not the activity.

**Comment by code0wl** [comment]
Thanks for the feedback. That does narrow things down quite a lot. Where you would recommend calling the takeOff function? 

Since I have a NativeScript application. I am using the launchevent, but I am guessing this is not enough for Android. 

Would activityCreated Event be best for Android?

**Comment by code0wl** [comment]
Thank you, that does narrow the search down quite a bit!

**Comment by rlepinski** [comment]
@code0wl Yeah, that was the original reason why we introduced autopilot. Have autopilot call takeOff with the critical pieces - app key, secret, and any notification customization (color, icon, etc..). The rest of UA customization can happen after words.

Are you using airshipconfig.properties ? If so, you can just include the default autopilot class and it will auto takeoff with the proper options.

**Comment by code0wl** [comment]
@rlepinski You have been of great help, thank you very much. I'll adjust my approach to use autopilot instead!

**Comment by rlepinski** [comment]
@code0wl Closing this for now. If you need more help feel free to reopen the issue.
