### ISSUE TITLE
NPE at com.urbanairship.analytics.data.EventResolver.trimDatabase(EventResolver.java:215)

### ISSUE THREAD

**Issue by PeteSesto** [urbanairship/android-library#60]
Hi all, 

We're seeing this crash report in fabric (see below).  I wish I had more info to give.  I'll be happy to share any code you may need.

> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
>        at com.urbanairship.analytics.data.EventResolver.trimDatabase(EventResolver.java:215)
>        at com.urbanairship.analytics.data.EventManager.addEvent(EventManager.java:133)
>        at com.urbanairship.analytics.Analytics$2.run(Analytics.java:182)
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
>        at java.lang.Thread.run(Thread.java:762)

**Top Android Device: Samsung Galaxy S7 (AT&T US)
TOP Android OS ver: 7
Urban Airship SDK ver: 8.9.6**

**Comment by rlepinski** [comment]
Pretty sure we fixed this issue in 8.8.4. Could you verify its from SDK 8.9.6 and not an older version of your app running an older version of the SDK?

**Comment by PeteSesto** [comment]
wow, great catch.  We updated to 8.9.6 on 1/4 but the version in production is 8.7.0

Thank you so much for the quick response.  Feel free to close this :)
