### ISSUE TITLE
How to get fcmSenderId/gcmSenderId in airshipconfig.property

### ISSUE THREAD

**Issue by ww6015132** [urbanairship/android-library#61]
Is there a way to get fcmSenderId/gcmSenderId in airshipconfig.property?
In SDK I see there is UAirship.OnReadyCallback. Can I reuse this in my code and get the fcmSenderId/gcmSenderId in the callback?

Thanks!

**Comment by rlepinski** [comment]
You can access it from the airship config options on the UAirship instance:

```
airship.getAirshipConfigOptions().getFcmSenderId();
```
