### ISSUE TITLE
For issue #61. Not solved

### ISSUE THREAD

**Issue by ww6015132** [urbanairship/android-library#63]
I know you have this method. 
`airship.getAirshipConfigOptions().getFcmSenderId();
`
But if I try to use it when app start it would return empty since the Airship config file hasn't been parsed yet. So I'm asking if there is a callback I can use when Urbanairship framework is ready.

**Comment by rlepinski** [comment]
How are you calling takeOff? Autopilot? You can customize autopilot and get a callback when its ready - https://docs.urbanairship.com/platform/android/#customizing-autopilot
