### ISSUE TITLE
BadParcelableException unmarshalling PushMessage 9.0.3

### ISSUE THREAD

**Issue by darnmason** [urbanairship/android-library#65]
Looks like this has been in there for a while, but noticed it's still happening in the latest version (9.0.3) which I just pushed out to users today. With a slightly different stack trace.

> Fatal Exception: java.lang.RuntimeException
> Unable to start receiver com.urbanairship.CoreReceiver: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.urbanairship.push.PushMessage
> android.app.ActivityThread.handleReceiver (ActivityThread.java:2996)
> android.app.ActivityThread.access$1800 (ActivityThread.java:177)
> android.app.ActivityThread$H.handleMessage (ActivityThread.java:1525)
> android.os.Handler.dispatchMessage (Handler.java:102)
> android.os.Looper.loop (Looper.java:145)
> android.app.ActivityThread.main (ActivityThread.java:5938)
> java.lang.reflect.Method.invoke (Method.java)
> java.lang.reflect.Method.invoke (Method.java:372)
> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1400)
> com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1195)
> 
> Caused by android.os.BadParcelableException
> ClassNotFoundException when unmarshalling: com.urbanairship.push.PushMessage
> android.os.Parcel.readParcelableCreator (Parcel.java:2289)
> android.os.Parcel.readParcelable (Parcel.java:2239)
> android.os.Parcel.readValue (Parcel.java:2146)
> android.os.Parcel.readArrayMapInternal (Parcel.java:2479)
> android.os.BaseBundle.unparcel (BaseBundle.java:221)
> android.os.Bundle.getBundle (Bundle.java:782)
> android.content.Intent.getBundleExtra (Intent.java:5652)
> com.urbanairship.push.PushMessage.fromIntent (PushMessage.java:660)
> com.urbanairship.CoreReceiver.onNotificationDismissedProxy (CoreReceiver.java:186)
> com.urbanairship.CoreReceiver.onReceive (CoreReceiver.java:75)
> android.app.ActivityThread.handleReceiver (ActivityThread.java:2989)
> android.app.ActivityThread.access$1800 (ActivityThread.java:177)
> android.app.ActivityThread$H.handleMessage (ActivityThread.java:1525)
> android.os.Handler.dispatchMessage (Handler.java:102)
> android.os.Looper.loop (Looper.java:145)
> android.app.ActivityThread.main (ActivityThread.java:5938)
> java.lang.reflect.Method.invoke (Method.java)
> java.lang.reflect.Method.invoke (Method.java:372)
> com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1400)
> com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1195)

Android 5.0, 5.1.1 so seems to be limited to Lollipop on devices such as Samsung Galaxy Note3, J1, J2, J3

**Comment by rlepinski** [comment]
Looking at the code, we are not putting any custom classes inside the intent bundle, its just the raw push bundle. It should just be a map<string, string>. Does this only happen on notification dismiss?

**Comment by darnmason** [comment]
Certainly looks to be only on notification dismiss. All of the stack traces I've seen are the same, with `onNotificationDismissedProxy` in there.

**Comment by rlepinski** [comment]
We can catch the exception in the next release to prevent the crash.  Not sure why its throwing in that code, nothing is standing out.

**Comment by rlepinski** [comment]
Fixed in 9.0.5
