### ISSUE TITLE
Getting Push Template Id

### ISSUE THREAD

**Issue by aneemtalukder** [urbanairship/android-library#7]
Is there a way to get a push notification template id? I've been exploring the PushNotification and NotificationInfo in the AirshipReceiver and have not been able to locate this piece of information. I have been looking at the methods onPushReceived and onNotificationOpened.

**Comment by rlepinski** [comment]
@aneemtalukder What do you mean by the template Id? Not everything is sent down in the push notification, so you may have to do custom extras for information. `push.getPushBundle().getString("key")`

**Comment by aneemtalukder** [comment]
@rlepinski by template id I mean this: http://docs.urbanairship.com/api/ua.html#templates

We send pushes by template id, was looking get the template id on the mobile side for tracking

**Comment by rlepinski** [comment]
@aneemtalukder I don't believe that ID is sent down to the device. If you would like to automatically available you should contact support and file a feature request. 

A possible workaround would be to set the template ID as an extra. 

Example Template:
```
{
    "name": "Welcome Message",
    "description": "Our welcome message",
    "variables": [
        {
            "key": "TITLE",
            "name": "Title",
            "description": "e.g. Mr, Ms, Dr, etc.",
            "default_value": ""
        },
        {
            "key": "FIRST_NAME",
            "name": "First Name",
            "description": "Given name",
            "default_value": null
        },
        {
            "key": "LAST_NAME",
            "name": "Last Name",
            "description": "Family name",
            "default_value": null
        }
    ],
    "push": {
        "notification": {
            "alert": "Hello {{TITLE}} {{FIRST_NAME}} {{LAST_NAME}}, this is your welcome message!",
            "android": {
            	"extra": {
            		"template_id": "{{TEMPLATE_ID}}"
            	}
            }
        }
    }
}
```
Example push:
```
{
    "device_types": "all",
    "audience": "all",
    "merge_data": {
        "template_id": "5ac26c47-6715-4bab-959e-5a6fc7012458",
        "substitutions": {
            "FIRST_NAME": "Bob",
            "LAST_NAME": "Smith",
            "TITLE": "",
            "TEMPLATE_ID": "5ac26c47-6715-4bab-959e-5a6fc7012458"
        }
    }
}
```

The template ID should then be available by calling `tionInfo.getMessage().getPushBundle().getString("template_id")`

**Comment by aneemtalukder** [comment]
@rlepinski ahh ok thank you. is this something i can do with the API only plan? we currently are not using the UA web interface

**Comment by rlepinski** [comment]
Thats just a toggle switch for the composer to hide some functionality. I believe extras are available to everyone.
