### ISSUE TITLE
IllegalStateException: Take off must be called before shared()

### ISSUE THREAD

**Issue by darnmason** [urbanairship/android-library#70]
My architecture is that I use a custom Autopilot and override `createAirshipConfigOptions` so there's no asset file. The `com.urbanairship.autopilot` meta-data is added to the manifest.

I use Dagger to inject the shared instance of UAirship for clean dependency management and testability:
`@Provides @Singleton static UAirship provideUrbanAirship() { return UAirship.shared(); }`

My Dagger component is initialised in my Application's onCreate but the UAirship instance is first accessed in my Activity's onCreate, which is where this exception is thrown.

I expect that Autopilot will call takeOff [before the Application's onCreate](https://docs.urbanairship.com/reference/libraries/android/latest/reference/com/urbanairship/Autopilot.html) method so this architecture should work just fine. However I'm seeing a few crashes that takeOff hasn't been called.

It's possible this was introduced in version 9.0.4 as I haven't seen this crash in earlier versions. Android versions affected are 5 and 6. Devices affected are likes of Galaxy J2, J3, S5 and ZTE Blade.

**Comment by rlepinski** [comment]
Are you using crashlytics? Can you share the crash report? Did you change how you call takeOff in the latest version? Is the crash rate going down?

I have seen similar errors in other peoples apps, but the error goes away after the update. For whatever reason some devices seem to not handle updates properly with our autopilot class, still investigating but I have never been able to reproduce the issue.

Without being able to reproduce it, I can only suggest a few possible fixes. It might be worthwhile adding `Autopilot.automaticTakeOff(this);` inside your Application's onCreate method. You can also remote autopilot and call takeOff directly in the Application onCreate method:
```
 UAirship.takeOff(this, configOptions, new UAirship.OnReadyCallback() {
            @Override
            public void onAirshipReady(UAirship airship) {
                
            }
        });
```

**Comment by darnmason** [comment]
I haven't made any changes to my UA implementation since I first released over a month ago, I've just been keeping the library up to date (currently on 9.0.4 with 9.0.5 ready to go in the next release)

I was considering doing away with Autopilot and calling takeOff manually but now I think I'll go with calling automaticTakeOff in my Application as I already have the custom Autopilot class.

We're only seeing 24 crashes affecting 6 users over the past 30 days with 122k monthly users.

The stack traces are very boring, it's all Dagger code as that's how I'm providing the UAirship instance but it goes something like:

> com.urbanairship.UAirship.shared (UAirship.java:151)
> ...ApplicationModule.provideUrbanAirship (ApplicationModule.java:100)
> ...ApplicationModule_ProvideUrbanAirshipFactory.get (ApplicationModule_ProvideUrbanAirshipFactory.java:19)
> ...ApplicationModule_ProvideUrbanAirshipFactory.get (ApplicationModule_ProvideUrbanAirshipFactory.java:8)
> dagger.internal.DoubleCheck.get (DoubleCheck.java:47)
> ...DaggerApplicationComponent$MainActivitySubcomponentImpl.getMainActivityPresenter (DaggerApplicationComponent.java:2747)
> ...DaggerApplicationComponent$MainActivitySubcomponentImpl.injectMainActivity (DaggerApplicationComponent.java:2764)
> ...DaggerApplicationComponent$MainActivitySubcomponentImpl.inject (DaggerApplicationComponent.java:2752)
> ...DaggerApplicationComponent$MainActivitySubcomponentImpl.inject (DaggerApplicationComponent.java:2428)
> dagger.android.DispatchingAndroidInjector.maybeInject (DispatchingAndroidInjector.java:81)
> dagger.android.DispatchingAndroidInjector.inject (DispatchingAndroidInjector.java:102)
> dagger.android.AndroidInjection.inject (AndroidInjection.java:59)
> ...MainActivity.onCreate (MainActivity.java:126)

**Comment by darnmason** [comment]
Something I noticed in your code while I briefly messed up changing my implementation was that in `Autopilot` the static variable `instanceCreated` is set to true regardless of whether the instance was actually created. In case `automaticTakeOff` is called multiple times, which is probably not the case, and it fails to create the instance the first time then it will never try again.

This doesn't affect me now though, I'm initialising UA as follows in my Application's onCreate:

    Autopilot autopilot = new MyAutopilot();
    AirshipConfigOptions options = autopilot.createAirshipConfigOptions(this);
    UAirship.takeOff(this, options, autopilot);

**Comment by rlepinski** [comment]
If it fails to create the instance the first time, I don't see how it would ever succeed again. Unless the application info is somehow null. Maybe thats the issue? We can change it in the next release but its hard to determine what the real issue is here.

**Comment by rlepinski** [comment]
Going to close for now. Ill change the Autopilot in the next release to retry instance creation if the application info is null.
