### ISSUE TITLE
Waiting 10 seconds in Service blocks UI

### ISSUE THREAD

**Issue by mribeiro** [urbanairship/android-library#71]
https://github.com/urbanairship/android-library/blob/e881b859a94dd86500413b34d745261c547d1820/urbanairship-sdk/src/main/java/com/urbanairship/push/PushService.java#L30

In the service there's apparently a wait of 10 seconds. The thread of a Service is the UI Thread and, if this period of wait is triggered, an ANR will occur since Android waits a max of 5 seconds before triggering the ANR.

**Comment by rlepinski** [comment]
Yep, that is correct. However if you are calling takeOff using autopilot or in your application onCreate you should never hit this issue.

**Comment by rlepinski** [comment]
Fixed in 9.0.6

**Comment by mribeiro** [comment]
We've been in contact with Urban Airship's support (rather not disclose much details here) but we found this ANR because our requirements ask us **not** to call `takeOff` during `Application#onCreate` .

**Comment by ralepinski** [comment]
@mribeiro I was just giving context for others. I assume you are delaying takeOff to fetch config, then after takeOff once you call it right away for next app sessions? 

Thanks for pointing out the issue!

**Comment by mribeiro** [comment]
Exactly! This issue became prominent with the following use case:

1. Wait for configs
2. Call `takeOff`
3. Delete app data
4. Launch app
5. Receive push notification **before** calling `takeOff`
