### ISSUE TITLE
ANR raised on some device executing AirshipGcmTaskService

### ISSUE THREAD

**Issue by ech0s7r** [urbanairship/android-library#72]
https://github.com/urbanairship/android-library/blob/fbfbcde094cca307cfd2906a508d4262546d2e37/urbanairship-sdk/src/main/java/com/urbanairship/job/AirshipGcmTaskService.java#L53

On some device like Xiaomi 4mi, Samsung Note4, Samsung S3 and more, ANR is raised Executing service com.mastercard.labs.qkr/com.urbanairship.job.AirshipGcmTaskService.

**Comment by rlepinski** [comment]
AirshipGcmTaskService runs on a bg thread. Most likely your ANR is caused by a deadlock somewhere else. In order to debug this we need a full ANR stack. Please contact support for more help.
