### ISSUE TITLE
UA interferes with migrating to FCM

### ISSUE THREAD

**Issue by cnnranderson** [urbanairship/android-library#73]
GCM and FCM requirements are different, yet several of the UA API documentation pages treat it as though GCM/FCM go hand in hand (as far as just renaming gcm -> fcm). The setup and migration documentation for GCM to FCM provided by Google say we should be using different service classes (see: FirebaseMessagingService and FirebaseInstanceID) and stop using GcmReceiver/Broadcast classes. Because UA uses these classes, I can't remove the GCM sdk dependency in my gradle build file. I get strange issues such as missing methods, and issues subscribing to new FCM topics. 

This hard dependency creates an issue for FCM migrations.

**Comment by rlepinski** [comment]
@cnnranderson Our SDK uses the GCM APIs currently. You can't force it to use APIs from a completely different package/class without other updates. We are working on an SDK update that allows the use of FCM over GCM. It will be out in the next week or so. For now, you can continue to use GCM with our SDK without an issue.

**Comment by rlepinski** [comment]
@cnnranderson We released an update that uses the FCM APIs in SDK 9.1.0. Here is a [migration guide](https://github.com/urbanairship/android-library/blob/master/documentation/migration/migration-guide-fcm.md).
