### ISSUE TITLE
Crash on Android 8 - "Not able to start ServiceIntent, App is in background."

### ISSUE THREAD

**Issue by RizwanSaleem123** [urbanairship/android-library#80]
`
Caused by java.lang.IllegalStateExceptionNot allowed to start service Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x1000010,  app is in background uid UidRecord{234836d u0a576 RCVR idle procs:1 seq(0,0,0)} Raw Text
--
  | android.app.ContextImpl.startServiceCommon (ContextImpl.java:1538)
  | android.app.ContextImpl.startService (ContextImpl.java:1484)
  | android.content.ContextWrapper.startService (ContextWrapper.java:663)
  | android.content.ContextWrapper.startService (ContextWrapper.java:663)
  | GcmBroadcastReceiver.startWakefulService (GcmBroadcastReceiver.java:60)
  | GcmBroadcastReceiver.onReceive (GcmBroadcastReceiver.java:126)
  | android.app.ActivityThread.handleReceiver (ActivityThread.java:3390)
  | android.app.ActivityThread.-wrap18 (Unknown Source)
  | android.app.ActivityThread$H.handleMessage (ActivityThread.java:1780)
  | android.os.Handler.dispatchMessage (Handler.java:105)
  | android.os.Looper.loop (Looper.java:164)
  | android.app.ActivityThread.main (ActivityThread.java:6938)
  | java.lang.reflect.Method.invoke (Method.java)
  | com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
  | com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)

`
GCMBroadcastReceiver is extending GcmPushReceiver. Having this above mentioned crash on Android 8 only.

**Comment by rlepinski** [comment]
Is this the same issue as https://github.com/urbanairship/android-library/issues/79 ? If so, please keep it contained to a single github issue.

I need to know how you extended it, why you extended it, and what SDK version you are on.
