### ISSUE TITLE
Please catch IllegalStateException here

### ISSUE THREAD

**Issue by S1GSEGV** [urbanairship/android-library#82]
https://github.com/urbanairship/android-library/blob/6973bc45ff8852d0838f7a4bbe50008683cf1453/urbanairship-core/src/main/java/com/urbanairship/location/FusedLocationAdapter.java#L212

**Comment by rlepinski** [comment]
We updated to the newer fused location APIs in 9.3.0, so hopefully you will no longer experience the exception.
