### ISSUE TITLE
RichPushInbox.startMessageActivity(msgId) renders HTML, but URL links clicks do nothing

### ISSUE THREAD

**Issue by harishrpatel** [urbanairship/android-library#86]
This functionality works on iOS, but on Android HTML URL links within rich text message with HTML content do not take user to browser. Actual HTML content renders fine.

**Comment by rlepinski** [comment]
SDK version? Logs? Reproduction steps?

**Comment by harishrpatel** [comment]
Here is info you requested:
- Android SDK Version: 9.0.6
- Reproduction Steps:
1. On UA console, Create->Message
2. Pick "Message Center" 
3. On Content tab, click Create button under RICH PAGE
4. Select TEXT template on right hand side
5. Select Content tab
6. Leave Page and Headline as they are
7. In Content dropdown, cut and paste this HTML text (this is just an example with couple of URL links).
-----------8<---------------
<html>
<body>
<p>&nbsp;</p>
<p style='text-align: center;'><strong><a style='color: #ff0000;' href='http://www.google.com'>FAQs</a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a target='_blank' style='color: #ff0000;' href='http://www.yahoo.com'>Terms &amp; Conditions</a></strong></p>
</body>
</html>
-----------8<---------------
8. When the in app message is clicked, this line in UA SDK is called:
UAirship.shared().getInbox().startMessageActivity(message.getMessageId());
9. It opens this message in an activity that is part of UA SDK. So, I don't have any more info.
10. Webpage renders correctly. When we tap on those URL links, nothing happens. It should take user to that URL. This functionality works on iOS SDK (v. 9.2.1)

I hope this helps you reproduce. Thanks.

**Comment by harishrpatel** [comment]
[htmlUATest.txt](https://github.com/urbanairship/android-library/files/2138462/htmlUATest.txt)

Added html as a separate text file as well.

**Comment by harishrpatel** [comment]
@rlepinski Could you please reopen this ticket? I have added repro steps as you asked for. Thanks so much.

**Comment by rlepinski** [comment]
@harishrpatel I am unable to reproduce. The links take me to the proper locations. Did you customize the message center activity? Could you provide verbose logs? Try it out in the sample?

**Comment by harishrpatel** [comment]
@rlepinski Ryan, after testing some more I am able to narrow it down to this:
It is not opening up a **PDF file** URL, i.e.
https://wwwimages2.adobe.com/www.adobe.com/content/dam/acom/en/legal/licenses-terms/pdf/PlatformClients_PC_WWEULA-en_US-20150407_1357.pdf

So, I am attaching another html text file where both links point to a PDF file and you can see that tapping on them does not take you to the document.
[htmlUATest_withAdobePDFlink.txt](https://github.com/urbanairship/android-library/files/2207299/htmlUATest_withAdobePDFlink.txt)
.

**Comment by rlepinski** [comment]
@harishrpatel It looks like webviews do not support pdfs by default in Android. Could you try using the `open_external_url_action` instead ? You can use the URL [uairship://run-basic-actions
](https://docs.urbanairship.com/reference/custom-templates/#uairship-run-basic-actions) to embed actions like a normal link.

**Comment by marc-scig** [comment]
Keep in mind that opening a URL this way requires that the URL string be percent-encded. So for this example PDF, I believe it would be:
```
uairship://run-basic-actions/open_external_url_action?=https%3A%2F%2Fwwwimages2.adobe.com%2Fwww.adobe.com%2Fcontent%2Fdam%2Facom%2Fen%2Flegal%2Flicenses-terms%2Fpdf%2FPlatformClients_PC_WWEULA-en_US-20150407_1357.pdf
```

**Comment by harishrpatel** [comment]
@rlepinski @marc-scig Thank you both for quick responses. It works on Android, but our QA is testing and having difficulties with iOS. So, can you please make sure that it works on iOS? We would not want to send two separate push messages for iOS and Android.

**Comment by rlepinski** [comment]
@harishrpatel We discovered and fixed the issue yesterday. Hopefully we will get the release out today.

**Comment by rlepinski** [comment]
@harishrpatel Fixed the issue in iOS 9.3.2

**Comment by harishrpatel** [comment]
@rlepinski I am confused. Is there a fix for Android as well? If released, can you tell us which version?

**Comment by crow** [comment]
> @rlepinski @marc-scig Thank you both for quick responses. **It works on Android**, but our QA is testing and having difficulties with iOS. So, can you please make sure that it works on iOS? We would not want to send two separate push messages for iOS and Android.

**Comment by crow** [comment]
Webviews do not support pdfs by default in Android. A workaround for this would be to try using the open_external_url_action instead by embedding it like a normal link. The link you provided when properly formatted should resemble the following: 

<a href="uairship://run-basic-actions?open_external_url_action=https%3A%2F%2Fwwwimages2.adobe.com%2Fwww.adobe.com%2Fcontent%2Fdam%2Facom%2Fen%2Flegal%2Flicenses-terms%2Fpdf%2FPlatformClients_PC_WWEULA-en_US-20150407_1357.pdf">Click this to open the PDF</a>

**Comment by rlepinski** [comment]
@harishrpatel The fix was for the issue your QA team found on iOS. Android is working as expected.
