### ISSUE TITLE
com.urbanairship.richpush.RichPushUpdateService is not resolve in manifest. Should I remove this service?

### ISSUE THREAD

**Issue by ghimire-bharat** [urbanairship/android-library#88]

**Comment by rlepinski** [comment]
We removed that service 2 years ago, so yes remove it. Our library defines all the required manifest entries in our manifest, so the only Urban Airship entries you need are an entry for autopilot and an airship receiver if you are using them.

**Comment by ghimire-bharat** [comment]
Thanks for the update
