### ISSUE TITLE
StackOverflowError because of set-/store- getTags()

### ISSUE THREAD

**Issue by BenedictP** [urbanairship/android-library#9]
Hi,

we are receiving a stackOverflowError while urbanairship tries to getTags, setTags and storeTags but storeTags calls getTags:
https://gist.github.com/guntherhoppe/5f4ef650e1001fc621c2faf799826505

Sdk-Version: 8.3.1

**Comment by rlepinski** [comment]
Wow. Yep, I can see the loop. Looks like it will only happen if normalize tags changes the stored set of tags. So I imagine you are migrating from an older SDK version?

We will have this fixed ASAP.

**Comment by BenedictP** [comment]
Yes, we updated the sdk version from 7.2.5 to 8.3.1.
Thanks for the fast response!

**Comment by rlepinski** [comment]
@BenedictP Fixed in 8.3.2
