### ISSUE TITLE
Firebase + UAShip not Working but Apple does!

### ISSUE THREAD

**Issue by gonzalovinas** [urbanairship/android-library#91]
I've an UA account working on a DEVELOPMENT MODE project pushing to both Google and Apple, but only Apples version is working. 

Androids doesn't use UA SDK at all, just raw Firebase SDK. 

Is this possible to let Android receives simple Push Notifications in this way?

Thanks in advance

**Comment by rlepinski** [comment]
If you are not using the UA SDK, then our backend will not have the registration IDs required to push notifications to. Our SDK is compatible with Firebase, they can be used side by side.  See https://docs.urbanairship.com/platform/android/#fcm-setup
