### ISSUE TITLE
proguard build errors with UA lib v9.4.1

### ISSUE THREAD

**Issue by harishrpatel** [urbanairship/android-library#92]
# Preliminary Info

### What Urban Airship dependencies are you using?
UA lib v9.4.1

### What are the versions of any relevant development tools you are using?
Android Studio 3.1.3

# Report

### What unexpected behavior are you seeing?
When building the project in Android Studio (these Proguard errors prevent from building APK).
Warning: com.urbanairship.push.adm.AdmPushProvider: can't find referenced class com.amazon.device.messaging.ADMConstants$LowLevel
Warning: com.urbanairship.push.adm.AdmPushProvider: can't find referenced class com.amazon.device.messaging.ADMConstants
Warning: com.urbanairship.push.adm.AdmPushProvider$RegistrationReceiver: can't find referenced class com.amazon.device.messaging.ADMConstants$LowLevel
Warning: com.urbanairship.push.adm.AdmPushProvider$RegistrationReceiver: can't find referenced class com.amazon.device.messaging.ADMConstants
Warning: com.urbanairship.push.adm.AdmPushReceiver: can't find referenced class com.amazon.device.messaging.ADMConstants$LowLevel
Warning: com.urbanairship.push.adm.AdmPushReceiver: can't find referenced class com.amazon.device.messaging.ADMConstants
Warning: com.urbanairship.push.adm.AdmWrapper: can't find referenced class com.amazon.device.messaging.ADM
Warning: com.urbanairship.push.adm.AdmWrapper: can't find referenced class com.amazon.device.messaging.ADM
Warning: com.urbanairship.push.adm.AdmWrapper: can't find referenced class com.amazon.device.messaging.ADM
Warning: com.urbanairship.push.adm.AdmWrapper: can't find referenced class com.amazon.device.messaging.ADM
Warning: com.urbanairship.push.adm.AdmWrapper: can't find referenced class com.amazon.device.messaging.ADM
Warning: there were 11 unresolved references to classes or interfaces.

### What is the expected behavior?
With UA lib v9.3.2, it was building successfully.

### What are the steps to reproduce the unexpected behavior?
- Please try building UA sample with these two lines enabled in build.gradle.
            minifyEnabled true
            shrinkResources true

### Do you have logging for the issue?
Error logs pasted above.

**Comment by harishrpatel** [comment]
@BrianBatchelder Thanks. I added all the lines except "-libraryjars libs". We don't care about ADM. I assume this is new functionality since v9.3.2. Is there a way to just disable it? We use AirshipConfigOptions.Builder to configure UA. I did not see any method to disable. Or not having ADM jar enough?

**Comment by harishrpatel** [comment]
@marc-scig Thanks. I followed the instructions by Amazon (as suggested by Brian above - it has couple more rules) and it builds successfully. Our QA is testing it today.

**Comment by rlepinski** [comment]
@harishrpatel Working on a release today to update our rules for ADM. What UA dependencies are you pulling in? We moved our push providers into modules, so if you do not need ADM you can pull in just `urbanairship-gcm` or `urbanairship-fcm` instead.

**Comment by rlepinski** [comment]
@harishrpatel Proguard changes are out in 9.4.2
