### ISSUE TITLE
UrbanAirship analytics not working

### ISSUE THREAD

**Issue by uzairaslam1993** [urbanairship/android-library#95]
I am using urban airship 9.0.6 SDK and I believe the analytics are not working. Whenever I open up a notification, the count does not update on the dashboard. Even checking the stats for that particular notification is not working as it says 0% direct opes etc.

**Comment by rlepinski** [comment]
You are on an older SDK version, but even if you updated to latest we do not have any known issues around analytics. Make sure analytics are enabled (can be disabled through airshipConfig as well as the analytics class). If that is not it, please contact support.
