### ISSUE TITLE
Proguard build issue - can't find referenced field 'int content_holder'

### ISSUE THREAD

**Issue by pallikondan** [urbanairship/android-library#96]
# Preliminary Info

### What Urban Airship dependencies are you using?
ℹ UrbanAirship android sdk version '8.2.5'

### What are the versions of any relevant development tools you are using?
ℹ Using UrbanAirship android plugin '6.6.0'

# Report

### What unexpected behavior are you seeing?
ℹ We are facing build failed issue while enabling proguard

Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: there were 11 duplicate class definitions.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#duplicateclass)
Warning: com.urbanairship.actions.LandingPageActivity: can't find referenced field 'int content_holder' in program class com.urbanairship.R$id
Warning: there were 1 unresolved references to program class members.
         Your input classes appear to be inconsistent.
         You may need to recompile the code.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedprogramclassmember)

### What is the expected behavior?
ℹ we are expecting successfull build by applying exact progurad rules without using -dontwarn for urbanAirship in proguard rules

### What are the steps to reproduce the unexpected behavior?
ℹPlease Enable proguard for your sample android cordova project with urbanAirship plugin version '6.6.0'

<img width="1045" alt="screen shot 2018-10-10 at 1 23 02 pm" src="https://user-images.githubusercontent.com/13165415/46721015-a840aa80-cc8f-11e8-8e47-4a2baa6c80d1.png">

**Comment by rlepinski** [comment]
I believe this is fixed in 9.5.2, please update and let me know if you continue to have issues.

**Comment by pallikondan** [comment]
We are using cordova-CLI 6.5.0, unfortunately we cant move to urbanairship 9.5.2 sdk, so do you have any fallback  work around to fix this issue?
Any help greatly appreciated.

**Comment by rlepinski** [comment]
@pallikondan Could you provide your config on how you are enabling proguard?

**Comment by rlepinski** [comment]
@pallikondan You can add a -dontwarn on that class. I believe it will be fine to ignore it. To double check, run this code in JS:
`UAirship.runAction("landing_page_action", "https://urbanairship.com")`
If that pops up a webpage without crashing you are in the clear.

I think this is an existing issue in the cordova plugin.

**Comment by pallikondan** [comment]
Thanks @rlepinski, I ignored this issue by using -dontwarn rule.
