### ISSUE TITLE
favicon.ico being requested in UAWebView

### ISSUE THREAD

**Issue by iankerr** [urbanairship/android-library#97]
# Preliminary Info

### What Urban Airship dependencies are you using?
ℹ Please include Urban Airship dependencies and their versions here.

com.urbanairship.android:urbanairship-fcm:9.5.1

### What are the versions of any relevant development tools you are using?
ℹ If applicable, please include any relevant information about the version of your
IDE, plugin(s), or package manager(s) here.

9.5.1

# Report

### What unexpected behavior are you seeing?
ℹ Please provide a brief description of the unexpected behavior here.

I'm proxying the app with charles, and I've noticed that when I view the contents of a message using the UAWebView, it is making a call to:

https://device-api.urbanairship.com/favicon.ico

...which is returning a 403 (Access Denied)

### What is the expected behavior?
ℹ Please provide a brief description of the expected behavior here.

No request should be made, as the favicon.ico is not required. Alternatively, the backend could be fixed to return the requested resources without error.

### What are the steps to reproduce the unexpected behavior?
ℹ Please provide reproduction steps here.

1. Proxy the app with charles, filtering for calls to device-api.urbanairship.com
1. View the contents of a rich push message
1. Observe the calls

### Do you have logging for the issue?
ℹ Please provide links to gists of any pertinent logs here.
No.

**Comment by rlepinski** [comment]
Thanks for the report. 

Looks like web views do this automatically and there is no easy way to disable it. We will probably end up doing something similar to https://stackoverflow.com/questions/34886582/disable-android-webview-webviewclient-initiated-favicon-ico-request.

I assume this is not really hurting anything in the app, so its going to be a lower priority issue on our backlog.

**Comment by iankerr** [comment]
Understood... not causing us any problems, just thought I'd bring it to your attention.

**Comment by crow** [comment]
Favicon requests will be intercepted in the next release. Thanks for reporting @iankerr
