### ISSUE TITLE
isGooglePlayServicesDependencyAvailable really ? 

### ISSUE THREAD

**Issue by leverdeterre** [urbanairship/android-library#99]
# Please fill out this template when submitting an issue.
All lines beginning with an ℹ symbol indicate information that's important for you to provide to ensure your issue is resolved as quickly and efficiently as possible.

❗For how-to inquiries involving Urban Airship functionality or use cases, please
contact (support)[https://support.urbanairship.com/hc/en-us].

# Preliminary Info

### What Urban Airship dependencies are you using?
    implementation 'com.urbanairship.android:urbanairship-fcm:9.3.1'
    implementation 'com.google.firebase:firebase-core:16.0.1'
    classpath 'com.google.gms:google-services:4.0.1'

### What are the versions of any relevant development tools you are using?
Android studio

# Report

### What unexpected behavior are you seeing?
I was using a S4 mini, running on Android version 4.2
My Google Play Services were out of date
I was able to receive push notification using Google Cloud Messaging
I was not able to receive push using UrbanAirship

The important logs in my console (to explain that behavior) were 

> UALib: Registration failed. Push provider unavailable: FCM Push Provider

After some search, i have found this line in FcmPushProvider.class
`int playServicesStatus = PlayServicesUtils.isGooglePlayServicesAvailable(context);
            if (0 != playServicesStatus) {
                Logger.error("Google Play services is currently unavailable.");
                return false;
            } ` 

### What is the expected behavior?
isGooglePlayServicesAvailable should not be mandatory to receive push from FCM because it works using Firebase

### What are the steps to reproduce the unexpected behavior?
Find a device with Google Play Services Out of date dans try to start using the UrbanAirship SDK

### Do you have logging for the issue?
Sorry, not anymore, i have updated the Google Play Services of my device

**Comment by rlepinski** [comment]
Firebase and Google Play services share a [common core](https://mvnrepository.com/artifact/com.google.firebase/firebase-messaging/17.0.0), and the docs for messaging say to [check for play services.](https://firebase.google.com/docs/cloud-messaging/android/client#sample-play)
